// @ts-nocheck
/**
 * CLI command for query getObjectAtPath
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';
import { getClient } from '../executor';
import { buildSelectFromPaths } from '../utils';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log('get-object-at-path - getObjectAtPath\n\nUsage: get-object-at-path [OPTIONS]\n');
      process.exit(0);
    }
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'dbId',
        message: 'dbId',
      },
      {
        type: 'text',
        name: 'storeId',
        message: 'storeId',
      },
      {
        type: 'text',
        name: 'path',
        message: 'path',
      },
      {
        type: 'text',
        name: 'refname',
        message: 'refname',
      },
    ]);
    const client = getClient();
    const selectFields = buildSelectFromPaths(argv.select ?? '');
    const result = await client.query
      .getObjectAtPath(answers, {
        select: selectFields,
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: getObjectAtPath');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
