/**
 * CLI commands for PlatformAgentRunWorkspace
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
import type {
  CreatePlatformAgentRunWorkspaceInput,
  PlatformAgentRunWorkspacePatch,
  PlatformAgentRunWorkspaceSelect,
  PlatformAgentRunWorkspaceFilter,
  PlatformAgentRunWorkspaceOrderBy,
} from '../../orm/input-types';
import type { FindManyArgs, FindFirstArgs } from '../../orm/select-types';
const fieldSchema: FieldSchema = {
  actorId: 'uuid',
  artifacts: 'json',
  baseBranch: 'string',
  baseCommit: 'string',
  branch: 'string',
  clonedAt: 'string',
  createdAt: 'string',
  headCommit: 'string',
  id: 'uuid',
  lastUsedAt: 'string',
  ordinal: 'int',
  provider: 'string',
  publication: 'string',
  repo: 'string',
  repositoryId: 'uuid',
  runId: 'uuid',
  state: 'string',
  updatedAt: 'string',
  visibility: 'string',
};
const usage =
  '\nplatform-agent-run-workspace <command>\n\nCommands:\n  list                  List platformAgentRunWorkspace records\n  find-first            Find first matching platformAgentRunWorkspace record\n  get                   Get a platformAgentRunWorkspace by ID\n  create                Create a new platformAgentRunWorkspace\n  update                Update an existing platformAgentRunWorkspace\n  delete                Delete a platformAgentRunWorkspace\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      actorId: true,
      artifacts: true,
      baseBranch: true,
      baseCommit: true,
      branch: true,
      clonedAt: true,
      createdAt: true,
      headCommit: true,
      id: true,
      lastUsedAt: true,
      ordinal: true,
      provider: true,
      publication: true,
      repo: true,
      repositoryId: true,
      runId: true,
      state: true,
      updatedAt: true,
      visibility: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<
        PlatformAgentRunWorkspaceSelect,
        PlatformAgentRunWorkspaceFilter,
        PlatformAgentRunWorkspaceOrderBy
      > & {
        select: PlatformAgentRunWorkspaceSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.platformAgentRunWorkspace.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      actorId: true,
      artifacts: true,
      baseBranch: true,
      baseCommit: true,
      branch: true,
      clonedAt: true,
      createdAt: true,
      headCommit: true,
      id: true,
      lastUsedAt: true,
      ordinal: true,
      provider: true,
      publication: true,
      repo: true,
      repositoryId: true,
      runId: true,
      state: true,
      updatedAt: true,
      visibility: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<
        PlatformAgentRunWorkspaceSelect,
        PlatformAgentRunWorkspaceFilter,
        PlatformAgentRunWorkspaceOrderBy
      > & {
        select: PlatformAgentRunWorkspaceSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.platformAgentRunWorkspace.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.platformAgentRunWorkspace
      .findOne({
        id: answers.id as string,
        select: {
          actorId: true,
          artifacts: true,
          baseBranch: true,
          baseCommit: true,
          branch: true,
          clonedAt: true,
          createdAt: true,
          headCommit: true,
          id: true,
          lastUsedAt: true,
          ordinal: true,
          provider: true,
          publication: true,
          repo: true,
          repositoryId: true,
          runId: true,
          state: true,
          updatedAt: true,
          visibility: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'actorId',
        message: 'actorId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'artifacts',
        message: 'artifacts',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'baseBranch',
        message: 'baseBranch',
        required: true,
      },
      {
        type: 'text',
        name: 'baseCommit',
        message: 'baseCommit',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'branch',
        message: 'branch',
        required: true,
      },
      {
        type: 'text',
        name: 'clonedAt',
        message: 'clonedAt',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'headCommit',
        message: 'headCommit',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'lastUsedAt',
        message: 'lastUsedAt',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'ordinal',
        message: 'ordinal',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'provider',
        message: 'provider',
        required: true,
      },
      {
        type: 'text',
        name: 'publication',
        message: 'publication',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'repo',
        message: 'repo',
        required: true,
      },
      {
        type: 'text',
        name: 'repositoryId',
        message: 'repositoryId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'runId',
        message: 'runId',
        required: true,
      },
      {
        type: 'text',
        name: 'state',
        message: 'state',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'visibility',
        message: 'visibility',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(
      answers,
      fieldSchema
    ) as CreatePlatformAgentRunWorkspaceInput['platformAgentRunWorkspace'];
    const client = getClient();
    const result = await client.platformAgentRunWorkspace
      .create({
        data: {
          actorId: cleanedData.actorId,
          artifacts: cleanedData.artifacts,
          baseBranch: cleanedData.baseBranch,
          baseCommit: cleanedData.baseCommit,
          branch: cleanedData.branch,
          clonedAt: cleanedData.clonedAt,
          headCommit: cleanedData.headCommit,
          lastUsedAt: cleanedData.lastUsedAt,
          ordinal: cleanedData.ordinal,
          provider: cleanedData.provider,
          publication: cleanedData.publication,
          repo: cleanedData.repo,
          repositoryId: cleanedData.repositoryId,
          runId: cleanedData.runId,
          state: cleanedData.state,
          visibility: cleanedData.visibility,
        },
        select: {
          actorId: true,
          artifacts: true,
          baseBranch: true,
          baseCommit: true,
          branch: true,
          clonedAt: true,
          createdAt: true,
          headCommit: true,
          id: true,
          lastUsedAt: true,
          ordinal: true,
          provider: true,
          publication: true,
          repo: true,
          repositoryId: true,
          runId: true,
          state: true,
          updatedAt: true,
          visibility: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'actorId',
        message: 'actorId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'artifacts',
        message: 'artifacts',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'baseBranch',
        message: 'baseBranch',
        required: false,
      },
      {
        type: 'text',
        name: 'baseCommit',
        message: 'baseCommit',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'branch',
        message: 'branch',
        required: false,
      },
      {
        type: 'text',
        name: 'clonedAt',
        message: 'clonedAt',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'headCommit',
        message: 'headCommit',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'lastUsedAt',
        message: 'lastUsedAt',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'ordinal',
        message: 'ordinal',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'provider',
        message: 'provider',
        required: false,
      },
      {
        type: 'text',
        name: 'publication',
        message: 'publication',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'repo',
        message: 'repo',
        required: false,
      },
      {
        type: 'text',
        name: 'repositoryId',
        message: 'repositoryId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'runId',
        message: 'runId',
        required: false,
      },
      {
        type: 'text',
        name: 'state',
        message: 'state',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'visibility',
        message: 'visibility',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as PlatformAgentRunWorkspacePatch;
    const client = getClient();
    const result = await client.platformAgentRunWorkspace
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          actorId: cleanedData.actorId,
          artifacts: cleanedData.artifacts,
          baseBranch: cleanedData.baseBranch,
          baseCommit: cleanedData.baseCommit,
          branch: cleanedData.branch,
          clonedAt: cleanedData.clonedAt,
          headCommit: cleanedData.headCommit,
          lastUsedAt: cleanedData.lastUsedAt,
          ordinal: cleanedData.ordinal,
          provider: cleanedData.provider,
          publication: cleanedData.publication,
          repo: cleanedData.repo,
          repositoryId: cleanedData.repositoryId,
          runId: cleanedData.runId,
          state: cleanedData.state,
          visibility: cleanedData.visibility,
        },
        select: {
          actorId: true,
          artifacts: true,
          baseBranch: true,
          baseCommit: true,
          branch: true,
          clonedAt: true,
          createdAt: true,
          headCommit: true,
          id: true,
          lastUsedAt: true,
          ordinal: true,
          provider: true,
          publication: true,
          repo: true,
          repositoryId: true,
          runId: true,
          state: true,
          updatedAt: true,
          visibility: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.platformAgentRunWorkspace
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
