/**
 * GraphQL SDK
 * @generated by @constructive-io/graphql-codegen
 *
 * Tables: Api, ApiSchema, ApiSetting, AstMigration, CheckConstraint, CompositeType, CorsSetting, Database, DatabaseSetting, DatabaseTransfer, DefaultPrivilege, Derive, Domain, DomainEvent, DomainType, DomainVerification, EmailIdentity, EmailProviderAccount, EmailSiteIdentity, EmbeddingChunk, Enum, ExclusionConstraint, FieldBehavior, Field, ForeignKeyConstraintBehavior, ForeignKeyConstraint, FullTextSearch, Function, HostnameBinding, HttpRoute, Index, ManagedDomain, NodeTypeRegistry, Page, Partition, PlatformApi, PlatformApiSchema, PlatformApiSetting, PlatformCorsSetting, PlatformDomain, PlatformDomainEvent, PlatformDomainVerification, PlatformEmailIdentity, PlatformEmailProviderAccount, PlatformEmailSiteIdentity, PlatformManagedDomain, PlatformPage, PlatformSiteAppLink, PlatformSite, PlatformSiteDeepLink, PlatformSiteErrorPage, PlatformSiteMetadatum, PlatformSiteModule, PlatformSiteTheme, PlatformSiteWebConfig, Policy, PrimaryKeyConstraint, PubkeySetting, RlsSetting, RouteBinding, Route, Schema, SchemaGrant, SiteAppLink, Site, SiteDeepLink, SiteErrorPage, SiteMetadatum, SiteModule, SiteTheme, SiteWebConfig, SpatialRelation, SqlAction, TableBehavior, Table, TableGrant, Trigger, TriggerFunction, UniqueConstraintBehavior, UniqueConstraint, ViewBehavior, View, ViewGrant, ViewRule, ViewTable, WebauthnSetting
 *
 * Usage:
 *
 * 1. Configure the client:
 * ```ts
 * import { configure } from './generated';
 *
 * configure({
 *   endpoint: 'https://api.example.com/graphql',
 *   headers: { Authorization: 'Bearer <token>' },
 * });
 * ```
 *
 * 2. Use the hooks:
 * ```tsx
 * import { useCarsQuery, useCreateCarMutation } from './generated';
 *
 * function MyComponent() {
 *   const { data, isLoading } = useCarsQuery({
 *     selection: { fields: { id: true }, first: 10 },
 *   });
 *   const { mutate } = useCreateCarMutation({
 *     selection: { fields: { id: true } },
 *   });
 *   // ...
 * }
 * ```
 */
export * from './client';
export * from './query-keys';
export * from './mutation-keys';
export * from './invalidation';
export * from './queries';
export * from './mutations';
