/**
 * Extension model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildCreateDocument,
  buildUpdateDocument,
  buildDeleteDocument,
} from '../query-builder';
import {
  type ConnectionResult,
  type FindManyArgs,
  type FindFirstArgs,
  type CreateArgs,
  type UpdateArgs,
  type DeleteArgs,
  type InferSelectResult,
} from '../select-types';
import {
  type Extension,
  type ExtensionWithRelations,
  type ExtensionSelect,
  type ExtensionFilter,
  type ExtensionsOrderBy,
  type CreateExtensionInput,
  type UpdateExtensionInput,
  type ExtensionPatch,
} from '../input-types';

// ============================================================================
// Model Class
// ============================================================================
export class ExtensionModel {
  constructor(private client: OrmClient) {}

  findMany<const S extends ExtensionSelect>(
    args?: FindManyArgs<S, ExtensionFilter, ExtensionsOrderBy>
  ): QueryBuilder<{
    extensions: ConnectionResult<InferSelectResult<ExtensionWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Extension',
      'extensions',
      args?.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'ExtensionFilter',
      'ExtensionsOrderBy'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Extension',
      fieldName: 'extensions',
      document,
      variables,
    });
  }

  findFirst<const S extends ExtensionSelect>(
    args?: FindFirstArgs<S, ExtensionFilter>
  ): QueryBuilder<{
    extensions: { nodes: InferSelectResult<ExtensionWithRelations, S>[] };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'Extension',
      'extensions',
      args?.select,
      { where: args?.where },
      'ExtensionFilter'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Extension',
      fieldName: 'extensions',
      document,
      variables,
    });
  }

  create<const S extends ExtensionSelect>(
    args: CreateArgs<S, CreateExtensionInput['extension']>
  ): QueryBuilder<{
    createExtension: {
      extension: InferSelectResult<ExtensionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'Extension',
      'createExtension',
      'extension',
      args.select,
      args.data,
      'CreateExtensionInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Extension',
      fieldName: 'createExtension',
      document,
      variables,
    });
  }

  update<const S extends ExtensionSelect>(
    args: UpdateArgs<S, { id: string }, ExtensionPatch>
  ): QueryBuilder<{
    updateExtension: {
      extension: InferSelectResult<ExtensionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateDocument(
      'Extension',
      'updateExtension',
      'extension',
      args.select,
      args.where,
      args.data,
      'UpdateExtensionInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Extension',
      fieldName: 'updateExtension',
      document,
      variables,
    });
  }

  delete(
    args: DeleteArgs<{ id: string }>
  ): QueryBuilder<{ deleteExtension: { extension: { id: string } } }> {
    const { document, variables } = buildDeleteDocument(
      'Extension',
      'deleteExtension',
      'extension',
      args.where,
      'DeleteExtensionInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Extension',
      fieldName: 'deleteExtension',
      document,
      variables,
    });
  }
}
