/**
 * ForeignKeyConstraint model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildCreateDocument,
  buildUpdateDocument,
  buildDeleteDocument,
} from '../query-builder';
import {
  type ConnectionResult,
  type FindManyArgs,
  type FindFirstArgs,
  type CreateArgs,
  type UpdateArgs,
  type DeleteArgs,
  type InferSelectResult,
} from '../select-types';
import {
  type ForeignKeyConstraint,
  type ForeignKeyConstraintWithRelations,
  type ForeignKeyConstraintSelect,
  type ForeignKeyConstraintFilter,
  type ForeignKeyConstraintsOrderBy,
  type CreateForeignKeyConstraintInput,
  type UpdateForeignKeyConstraintInput,
  type ForeignKeyConstraintPatch,
} from '../input-types';

// ============================================================================
// Model Class
// ============================================================================
export class ForeignKeyConstraintModel {
  constructor(private client: OrmClient) {}

  findMany<const S extends ForeignKeyConstraintSelect>(
    args?: FindManyArgs<
      S,
      ForeignKeyConstraintFilter,
      ForeignKeyConstraintsOrderBy
    >
  ): QueryBuilder<{
    foreignKeyConstraints: ConnectionResult<
      InferSelectResult<ForeignKeyConstraintWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'ForeignKeyConstraint',
      'foreignKeyConstraints',
      args?.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'ForeignKeyConstraintFilter',
      'ForeignKeyConstraintsOrderBy'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'ForeignKeyConstraint',
      fieldName: 'foreignKeyConstraints',
      document,
      variables,
    });
  }

  findFirst<const S extends ForeignKeyConstraintSelect>(
    args?: FindFirstArgs<S, ForeignKeyConstraintFilter>
  ): QueryBuilder<{
    foreignKeyConstraints: {
      nodes: InferSelectResult<ForeignKeyConstraintWithRelations, S>[];
    };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'ForeignKeyConstraint',
      'foreignKeyConstraints',
      args?.select,
      { where: args?.where },
      'ForeignKeyConstraintFilter'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'ForeignKeyConstraint',
      fieldName: 'foreignKeyConstraints',
      document,
      variables,
    });
  }

  create<const S extends ForeignKeyConstraintSelect>(
    args: CreateArgs<S, CreateForeignKeyConstraintInput['foreignKeyConstraint']>
  ): QueryBuilder<{
    createForeignKeyConstraint: {
      foreignKeyConstraint: InferSelectResult<
        ForeignKeyConstraintWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'ForeignKeyConstraint',
      'createForeignKeyConstraint',
      'foreignKeyConstraint',
      args.select,
      args.data,
      'CreateForeignKeyConstraintInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'ForeignKeyConstraint',
      fieldName: 'createForeignKeyConstraint',
      document,
      variables,
    });
  }

  update<const S extends ForeignKeyConstraintSelect>(
    args: UpdateArgs<S, { id: string }, ForeignKeyConstraintPatch>
  ): QueryBuilder<{
    updateForeignKeyConstraint: {
      foreignKeyConstraint: InferSelectResult<
        ForeignKeyConstraintWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildUpdateDocument(
      'ForeignKeyConstraint',
      'updateForeignKeyConstraint',
      'foreignKeyConstraint',
      args.select,
      args.where,
      args.data,
      'UpdateForeignKeyConstraintInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'ForeignKeyConstraint',
      fieldName: 'updateForeignKeyConstraint',
      document,
      variables,
    });
  }

  delete(
    args: DeleteArgs<{ id: string }>
  ): QueryBuilder<{
    deleteForeignKeyConstraint: { foreignKeyConstraint: { id: string } };
  }> {
    const { document, variables } = buildDeleteDocument(
      'ForeignKeyConstraint',
      'deleteForeignKeyConstraint',
      'foreignKeyConstraint',
      args.where,
      'DeleteForeignKeyConstraintInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'ForeignKeyConstraint',
      fieldName: 'deleteForeignKeyConstraint',
      document,
      variables,
    });
  }
}
