/**
 * LevelsModule model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildCreateDocument,
  buildUpdateDocument,
  buildDeleteDocument,
} from '../query-builder';
import {
  type ConnectionResult,
  type FindManyArgs,
  type FindFirstArgs,
  type CreateArgs,
  type UpdateArgs,
  type DeleteArgs,
  type InferSelectResult,
} from '../select-types';
import {
  type LevelsModule,
  type LevelsModuleWithRelations,
  type LevelsModuleSelect,
  type LevelsModuleFilter,
  type LevelsModulesOrderBy,
  type CreateLevelsModuleInput,
  type UpdateLevelsModuleInput,
  type LevelsModulePatch,
} from '../input-types';

// ============================================================================
// Model Class
// ============================================================================
export class LevelsModuleModel {
  constructor(private client: OrmClient) {}

  findMany<const S extends LevelsModuleSelect>(
    args?: FindManyArgs<S, LevelsModuleFilter, LevelsModulesOrderBy>
  ): QueryBuilder<{
    levelsModules: ConnectionResult<
      InferSelectResult<LevelsModuleWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'LevelsModule',
      'levelsModules',
      args?.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'LevelsModuleFilter',
      'LevelsModulesOrderBy'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'LevelsModule',
      fieldName: 'levelsModules',
      document,
      variables,
    });
  }

  findFirst<const S extends LevelsModuleSelect>(
    args?: FindFirstArgs<S, LevelsModuleFilter>
  ): QueryBuilder<{
    levelsModules: { nodes: InferSelectResult<LevelsModuleWithRelations, S>[] };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'LevelsModule',
      'levelsModules',
      args?.select,
      { where: args?.where },
      'LevelsModuleFilter'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'LevelsModule',
      fieldName: 'levelsModules',
      document,
      variables,
    });
  }

  create<const S extends LevelsModuleSelect>(
    args: CreateArgs<S, CreateLevelsModuleInput['levelsModule']>
  ): QueryBuilder<{
    createLevelsModule: {
      levelsModule: InferSelectResult<LevelsModuleWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'LevelsModule',
      'createLevelsModule',
      'levelsModule',
      args.select,
      args.data,
      'CreateLevelsModuleInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'LevelsModule',
      fieldName: 'createLevelsModule',
      document,
      variables,
    });
  }

  update<const S extends LevelsModuleSelect>(
    args: UpdateArgs<S, { id: string }, LevelsModulePatch>
  ): QueryBuilder<{
    updateLevelsModule: {
      levelsModule: InferSelectResult<LevelsModuleWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateDocument(
      'LevelsModule',
      'updateLevelsModule',
      'levelsModule',
      args.select,
      args.where,
      args.data,
      'UpdateLevelsModuleInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'LevelsModule',
      fieldName: 'updateLevelsModule',
      document,
      variables,
    });
  }

  delete(
    args: DeleteArgs<{ id: string }>
  ): QueryBuilder<{ deleteLevelsModule: { levelsModule: { id: string } } }> {
    const { document, variables } = buildDeleteDocument(
      'LevelsModule',
      'deleteLevelsModule',
      'levelsModule',
      args.where,
      'DeleteLevelsModuleInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'LevelsModule',
      fieldName: 'deleteLevelsModule',
      document,
      variables,
    });
  }
}
