/**
 * ModuleOutput model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from "../client";
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildCreateDocument,
  buildUpdateDocument,
  buildDeleteDocument,
} from "../query-builder";
import {
  type ConnectionResult,
  type FindManyArgs,
  type FindFirstArgs,
  type CreateArgs,
  type UpdateArgs,
  type DeleteArgs,
  type InferSelectResult,
} from "../select-types";
import {
  type ModuleOutput,
  type ModuleOutputWithRelations,
  type ModuleOutputSelect,
  type ModuleOutputFilter,
  type ModuleOutputsOrderBy,
  type CreateModuleOutputInput,
  type UpdateModuleOutputInput,
  type ModuleOutputPatch,
} from "../input-types";

// ============================================================================
// Model Class
// ============================================================================
export class ModuleOutputModel {
  constructor(private client: OrmClient) {}

  findMany<const S extends ModuleOutputSelect>(
    args?: FindManyArgs<S, ModuleOutputFilter, ModuleOutputsOrderBy>,
  ): QueryBuilder<{
    moduleOutputs: ConnectionResult<
      InferSelectResult<ModuleOutputWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      "ModuleOutput",
      "moduleOutputs",
      args?.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      "ModuleOutputFilter",
      "ModuleOutputsOrderBy",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "query",
      operationName: "ModuleOutput",
      fieldName: "moduleOutputs",
      document,
      variables,
    });
  }

  findFirst<const S extends ModuleOutputSelect>(
    args?: FindFirstArgs<S, ModuleOutputFilter>,
  ): QueryBuilder<{
    moduleOutputs: { nodes: InferSelectResult<ModuleOutputWithRelations, S>[] };
  }> {
    const { document, variables } = buildFindFirstDocument(
      "ModuleOutput",
      "moduleOutputs",
      args?.select,
      { where: args?.where },
      "ModuleOutputFilter",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "query",
      operationName: "ModuleOutput",
      fieldName: "moduleOutputs",
      document,
      variables,
    });
  }

  create<const S extends ModuleOutputSelect>(
    args: CreateArgs<S, CreateModuleOutputInput["moduleOutput"]>,
  ): QueryBuilder<{
    createModuleOutput: {
      moduleOutput: InferSelectResult<ModuleOutputWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      "ModuleOutput",
      "createModuleOutput",
      "moduleOutput",
      args.select,
      args.data,
      "CreateModuleOutputInput",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "mutation",
      operationName: "ModuleOutput",
      fieldName: "createModuleOutput",
      document,
      variables,
    });
  }

  update<const S extends ModuleOutputSelect>(
    args: UpdateArgs<S, { id: string }, ModuleOutputPatch>,
  ): QueryBuilder<{
    updateModuleOutput: {
      moduleOutput: InferSelectResult<ModuleOutputWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateDocument(
      "ModuleOutput",
      "updateModuleOutput",
      "moduleOutput",
      args.select,
      args.where,
      args.data,
      "UpdateModuleOutputInput",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "mutation",
      operationName: "ModuleOutput",
      fieldName: "updateModuleOutput",
      document,
      variables,
    });
  }

  delete(
    args: DeleteArgs<{ id: string }>,
  ): QueryBuilder<{ deleteModuleOutput: { moduleOutput: { id: string } } }> {
    const { document, variables } = buildDeleteDocument(
      "ModuleOutput",
      "deleteModuleOutput",
      "moduleOutput",
      args.where,
      "DeleteModuleOutputInput",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "mutation",
      operationName: "ModuleOutput",
      fieldName: "deleteModuleOutput",
      document,
      variables,
    });
  }
}
