/**
 * ModuleField model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from "../client";
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildCreateDocument,
  buildUpdateDocument,
  buildDeleteDocument,
} from "../query-builder";
import {
  type ConnectionResult,
  type FindManyArgs,
  type FindFirstArgs,
  type CreateArgs,
  type UpdateArgs,
  type DeleteArgs,
  type InferSelectResult,
} from "../select-types";
import {
  type ModuleField,
  type ModuleFieldWithRelations,
  type ModuleFieldSelect,
  type ModuleFieldFilter,
  type ModuleFieldsOrderBy,
  type CreateModuleFieldInput,
  type UpdateModuleFieldInput,
  type ModuleFieldPatch,
} from "../input-types";

// ============================================================================
// Model Class
// ============================================================================
export class ModuleFieldModel {
  constructor(private client: OrmClient) {}

  findMany<const S extends ModuleFieldSelect>(
    args?: FindManyArgs<S, ModuleFieldFilter, ModuleFieldsOrderBy>,
  ): QueryBuilder<{
    moduleFields: ConnectionResult<
      InferSelectResult<ModuleFieldWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      "ModuleField",
      "moduleFields",
      args?.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      "ModuleFieldFilter",
      "ModuleFieldsOrderBy",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "query",
      operationName: "ModuleField",
      fieldName: "moduleFields",
      document,
      variables,
    });
  }

  findFirst<const S extends ModuleFieldSelect>(
    args?: FindFirstArgs<S, ModuleFieldFilter>,
  ): QueryBuilder<{
    moduleFields: { nodes: InferSelectResult<ModuleFieldWithRelations, S>[] };
  }> {
    const { document, variables } = buildFindFirstDocument(
      "ModuleField",
      "moduleFields",
      args?.select,
      { where: args?.where },
      "ModuleFieldFilter",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "query",
      operationName: "ModuleField",
      fieldName: "moduleFields",
      document,
      variables,
    });
  }

  create<const S extends ModuleFieldSelect>(
    args: CreateArgs<S, CreateModuleFieldInput["moduleField"]>,
  ): QueryBuilder<{
    createModuleField: {
      moduleField: InferSelectResult<ModuleFieldWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      "ModuleField",
      "createModuleField",
      "moduleField",
      args.select,
      args.data,
      "CreateModuleFieldInput",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "mutation",
      operationName: "ModuleField",
      fieldName: "createModuleField",
      document,
      variables,
    });
  }

  update<const S extends ModuleFieldSelect>(
    args: UpdateArgs<S, { id: string }, ModuleFieldPatch>,
  ): QueryBuilder<{
    updateModuleField: {
      moduleField: InferSelectResult<ModuleFieldWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateDocument(
      "ModuleField",
      "updateModuleField",
      "moduleField",
      args.select,
      args.where,
      args.data,
      "UpdateModuleFieldInput",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "mutation",
      operationName: "ModuleField",
      fieldName: "updateModuleField",
      document,
      variables,
    });
  }

  delete(
    args: DeleteArgs<{ id: string }>,
  ): QueryBuilder<{ deleteModuleField: { moduleField: { id: string } } }> {
    const { document, variables } = buildDeleteDocument(
      "ModuleField",
      "deleteModuleField",
      "moduleField",
      args.where,
      "DeleteModuleFieldInput",
    );
    return new QueryBuilder({
      client: this.client,
      operation: "mutation",
      operationName: "ModuleField",
      fieldName: "deleteModuleField",
      document,
      variables,
    });
  }
}
