/**
 * OrgMembershipDefault model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildCreateDocument,
  buildUpdateDocument,
  buildDeleteDocument,
} from '../query-builder';
import {
  type ConnectionResult,
  type FindManyArgs,
  type FindFirstArgs,
  type CreateArgs,
  type UpdateArgs,
  type DeleteArgs,
  type InferSelectResult,
} from '../select-types';
import {
  type OrgMembershipDefault,
  type OrgMembershipDefaultWithRelations,
  type OrgMembershipDefaultSelect,
  type OrgMembershipDefaultFilter,
  type OrgMembershipDefaultsOrderBy,
  type CreateOrgMembershipDefaultInput,
  type UpdateOrgMembershipDefaultInput,
  type OrgMembershipDefaultPatch,
} from '../input-types';

// ============================================================================
// Model Class
// ============================================================================
export class OrgMembershipDefaultModel {
  constructor(private client: OrmClient) {}

  findMany<const S extends OrgMembershipDefaultSelect>(
    args?: FindManyArgs<
      S,
      OrgMembershipDefaultFilter,
      OrgMembershipDefaultsOrderBy
    >
  ): QueryBuilder<{
    orgMembershipDefaults: ConnectionResult<
      InferSelectResult<OrgMembershipDefaultWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'OrgMembershipDefault',
      'orgMembershipDefaults',
      args?.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'OrgMembershipDefaultFilter',
      'OrgMembershipDefaultsOrderBy'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMembershipDefault',
      fieldName: 'orgMembershipDefaults',
      document,
      variables,
    });
  }

  findFirst<const S extends OrgMembershipDefaultSelect>(
    args?: FindFirstArgs<S, OrgMembershipDefaultFilter>
  ): QueryBuilder<{
    orgMembershipDefaults: {
      nodes: InferSelectResult<OrgMembershipDefaultWithRelations, S>[];
    };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'OrgMembershipDefault',
      'orgMembershipDefaults',
      args?.select,
      { where: args?.where },
      'OrgMembershipDefaultFilter'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'OrgMembershipDefault',
      fieldName: 'orgMembershipDefaults',
      document,
      variables,
    });
  }

  create<const S extends OrgMembershipDefaultSelect>(
    args: CreateArgs<S, CreateOrgMembershipDefaultInput['orgMembershipDefault']>
  ): QueryBuilder<{
    createOrgMembershipDefault: {
      orgMembershipDefault: InferSelectResult<
        OrgMembershipDefaultWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'OrgMembershipDefault',
      'createOrgMembershipDefault',
      'orgMembershipDefault',
      args.select,
      args.data,
      'CreateOrgMembershipDefaultInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMembershipDefault',
      fieldName: 'createOrgMembershipDefault',
      document,
      variables,
    });
  }

  update<const S extends OrgMembershipDefaultSelect>(
    args: UpdateArgs<S, { id: string }, OrgMembershipDefaultPatch>
  ): QueryBuilder<{
    updateOrgMembershipDefault: {
      orgMembershipDefault: InferSelectResult<
        OrgMembershipDefaultWithRelations,
        S
      >;
    };
  }> {
    const { document, variables } = buildUpdateDocument(
      'OrgMembershipDefault',
      'updateOrgMembershipDefault',
      'orgMembershipDefault',
      args.select,
      args.where,
      args.data,
      'UpdateOrgMembershipDefaultInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMembershipDefault',
      fieldName: 'updateOrgMembershipDefault',
      document,
      variables,
    });
  }

  delete(
    args: DeleteArgs<{ id: string }>
  ): QueryBuilder<{
    deleteOrgMembershipDefault: { orgMembershipDefault: { id: string } };
  }> {
    const { document, variables } = buildDeleteDocument(
      'OrgMembershipDefault',
      'deleteOrgMembershipDefault',
      'orgMembershipDefault',
      args.where,
      'DeleteOrgMembershipDefaultInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'OrgMembershipDefault',
      fieldName: 'deleteOrgMembershipDefault',
      document,
      variables,
    });
  }
}
