/**
 * Schema model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildCreateDocument,
  buildUpdateDocument,
  buildDeleteDocument,
} from '../query-builder';
import {
  type ConnectionResult,
  type FindManyArgs,
  type FindFirstArgs,
  type CreateArgs,
  type UpdateArgs,
  type DeleteArgs,
  type InferSelectResult,
} from '../select-types';
import {
  type Schema,
  type SchemaWithRelations,
  type SchemaSelect,
  type SchemaFilter,
  type SchemasOrderBy,
  type CreateSchemaInput,
  type UpdateSchemaInput,
  type SchemaPatch,
} from '../input-types';

// ============================================================================
// Model Class
// ============================================================================
export class SchemaModel {
  constructor(private client: OrmClient) {}

  findMany<const S extends SchemaSelect>(
    args?: FindManyArgs<S, SchemaFilter, SchemasOrderBy>
  ): QueryBuilder<{
    schemas: ConnectionResult<InferSelectResult<SchemaWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Schema',
      'schemas',
      args?.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'SchemaFilter',
      'SchemasOrderBy'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Schema',
      fieldName: 'schemas',
      document,
      variables,
    });
  }

  findFirst<const S extends SchemaSelect>(
    args?: FindFirstArgs<S, SchemaFilter>
  ): QueryBuilder<{
    schemas: { nodes: InferSelectResult<SchemaWithRelations, S>[] };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'Schema',
      'schemas',
      args?.select,
      { where: args?.where },
      'SchemaFilter'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Schema',
      fieldName: 'schemas',
      document,
      variables,
    });
  }

  create<const S extends SchemaSelect>(
    args: CreateArgs<S, CreateSchemaInput['schema']>
  ): QueryBuilder<{
    createSchema: { schema: InferSelectResult<SchemaWithRelations, S> };
  }> {
    const { document, variables } = buildCreateDocument(
      'Schema',
      'createSchema',
      'schema',
      args.select,
      args.data,
      'CreateSchemaInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Schema',
      fieldName: 'createSchema',
      document,
      variables,
    });
  }

  update<const S extends SchemaSelect>(
    args: UpdateArgs<S, { id: string }, SchemaPatch>
  ): QueryBuilder<{
    updateSchema: { schema: InferSelectResult<SchemaWithRelations, S> };
  }> {
    const { document, variables } = buildUpdateDocument(
      'Schema',
      'updateSchema',
      'schema',
      args.select,
      args.where,
      args.data,
      'UpdateSchemaInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Schema',
      fieldName: 'updateSchema',
      document,
      variables,
    });
  }

  delete(
    args: DeleteArgs<{ id: string }>
  ): QueryBuilder<{ deleteSchema: { schema: { id: string } } }> {
    const { document, variables } = buildDeleteDocument(
      'Schema',
      'deleteSchema',
      'schema',
      args.where,
      'DeleteSchemaInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Schema',
      fieldName: 'deleteSchema',
      document,
      variables,
    });
  }
}
