/**
 * Table model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildCreateDocument,
  buildUpdateDocument,
  buildDeleteDocument,
} from '../query-builder';
import {
  type ConnectionResult,
  type FindManyArgs,
  type FindFirstArgs,
  type CreateArgs,
  type UpdateArgs,
  type DeleteArgs,
  type InferSelectResult,
} from '../select-types';
import {
  type Table,
  type TableWithRelations,
  type TableSelect,
  type TableFilter,
  type TablesOrderBy,
  type CreateTableInput,
  type UpdateTableInput,
  type TablePatch,
} from '../input-types';

// ============================================================================
// Model Class
// ============================================================================
export class TableModel {
  constructor(private client: OrmClient) {}

  findMany<const S extends TableSelect>(
    args?: FindManyArgs<S, TableFilter, TablesOrderBy>
  ): QueryBuilder<{
    tables: ConnectionResult<InferSelectResult<TableWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Table',
      'tables',
      args?.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'TableFilter',
      'TablesOrderBy'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Table',
      fieldName: 'tables',
      document,
      variables,
    });
  }

  findFirst<const S extends TableSelect>(
    args?: FindFirstArgs<S, TableFilter>
  ): QueryBuilder<{
    tables: { nodes: InferSelectResult<TableWithRelations, S>[] };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'Table',
      'tables',
      args?.select,
      { where: args?.where },
      'TableFilter'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Table',
      fieldName: 'tables',
      document,
      variables,
    });
  }

  create<const S extends TableSelect>(
    args: CreateArgs<S, CreateTableInput['table']>
  ): QueryBuilder<{
    createTable: { table: InferSelectResult<TableWithRelations, S> };
  }> {
    const { document, variables } = buildCreateDocument(
      'Table',
      'createTable',
      'table',
      args.select,
      args.data,
      'CreateTableInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Table',
      fieldName: 'createTable',
      document,
      variables,
    });
  }

  update<const S extends TableSelect>(
    args: UpdateArgs<S, { id: string }, TablePatch>
  ): QueryBuilder<{
    updateTable: { table: InferSelectResult<TableWithRelations, S> };
  }> {
    const { document, variables } = buildUpdateDocument(
      'Table',
      'updateTable',
      'table',
      args.select,
      args.where,
      args.data,
      'UpdateTableInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Table',
      fieldName: 'updateTable',
      document,
      variables,
    });
  }

  delete(
    args: DeleteArgs<{ id: string }>
  ): QueryBuilder<{ deleteTable: { table: { id: string } } }> {
    const { document, variables } = buildDeleteDocument(
      'Table',
      'deleteTable',
      'table',
      args.where,
      'DeleteTableInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Table',
      fieldName: 'deleteTable',
      document,
      variables,
    });
  }
}
