/**
 * Framework-agnostic realtime subscription client.
 *
 * Manages a single graphql-ws WebSocket connection and multiplexes
 * subscriptions over it. Each subscribe() call sends a separate
 * GraphQL subscription operation; graphql-ws handles the protocol.
 */
import { createClient as createWsClient } from 'graphql-ws';
import type { Client as WsClient } from 'graphql-ws';

import type {
  ConnectionState,
  ConnectionStateListener,
  RealtimeClientConfig,
  SubscribeOptions,
  SubscriptionEvent,
  SubscriptionFieldMeta,
  SubscriptionOperation,
  Unsubscribe,
} from './types';

export class RealtimeClient {
  private wsClient: WsClient;
  private connectionState: ConnectionState = 'disconnected';
  private stateListeners: Set<ConnectionStateListener> = new Set();
  private activeSubscriptions = 0;

  constructor(private config: RealtimeClientConfig) {
    const retryWait = async (retryCount: number): Promise<void> => {
      if (typeof config.retryWait === 'function') {
        const result = config.retryWait(retryCount);
        const ms = typeof result === 'number' ? result : await result;
        await new Promise<void>((resolve) => setTimeout(resolve, ms));
      } else {
        const base = typeof config.retryWait === 'number' ? config.retryWait : 1000;
        await new Promise<void>((resolve) =>
          setTimeout(resolve, base * Math.pow(2, retryCount))
        );
      }
    };

    this.wsClient = createWsClient({
      url: config.url,
      lazy: config.lazy ?? true,
      retryAttempts: config.retryAttempts ?? 5,
      retryWait,
      connectionParams: async () => {
        const params: Record<string, unknown> = { ...config.connectionParams };
        if (config.getToken) {
          const token = await config.getToken();
          params['authorization'] = `Bearer ${token}`;
        }
        return params;
      },
      on: {
        connecting: () => {
          const newState =
            this.connectionState === 'disconnected' ? 'connecting' : 'reconnecting';
          this.setConnectionState(newState);
        },
        connected: () => {
          this.setConnectionState('connected');
          config.onConnected?.();
        },
        closed: (event) => {
          this.setConnectionState('disconnected');
          config.onDisconnected?.(event);
        },
      },
    });
  }

  /**
   * Subscribe to a GraphQL subscription field.
   *
   * This is the low-level method. Per-table subscription models
   * (generated by codegen) call this with the correct field metadata
   * and GraphQL document.
   */
  subscribe<T>(
    meta: SubscriptionFieldMeta,
    document: string,
    variables: Record<string, unknown>,
    options: SubscribeOptions<T>
  ): Unsubscribe {
    this.activeSubscriptions++;
    let disposed = false;

    const cleanup = this.wsClient.subscribe<Record<string, unknown>>(
      { query: document, variables },
      {
        next: (result) => {
          if (disposed) return;
          if (result.errors) {
            options.onError?.(
              new Error(result.errors.map((e) => e.message).join('; '))
            );
            return;
          }

          const payload = result.data?.[meta.fieldName] as
            | {
                event?: string;
                [key: string]: unknown;
              }
            | undefined;

          if (!payload) return;

          const event: SubscriptionEvent<T> = {
            operation: (payload.event as SubscriptionOperation) ?? 'UPDATE',
            data: (payload[meta.dataFieldName] as T) ?? null,
            previousValues: payload.previousValues as Partial<T> | undefined,
            timestamp:
              (payload.timestamp as string) ?? new Date().toISOString(),
          };
          options.onEvent(event);
        },
        error: (err) => {
          if (disposed) return;
          options.onError?.(
            err instanceof Error ? err : new Error(String(err))
          );
        },
        complete: () => {
          if (disposed) return;
          options.onComplete?.();
        },
      }
    );

    return () => {
      if (disposed) return;
      disposed = true;
      this.activeSubscriptions--;
      cleanup();
    };
  }

  /**
   * Create a per-table subscription model.
   *
   * Codegen calls this for each realtime-enabled table to produce
   * a typed `.subscribe()` method on the client instance.
   */
  createSubscriptionModel<T, TFilter extends Record<string, unknown> = Record<string, unknown>>(
    meta: SubscriptionFieldMeta,
    buildDocument: (filter?: TFilter) => { document: string; variables: Record<string, unknown> }
  ) {
    return {
      subscribe: (options: SubscribeOptions<T, TFilter>): Unsubscribe => {
        const { document, variables } = buildDocument(options.filter);
        return this.subscribe<T>(meta, document, variables, options);
      },
    };
  }

  /** Register a listener for connection state changes */
  onConnectionStateChange(listener: ConnectionStateListener): Unsubscribe {
    this.stateListeners.add(listener);
    return () => {
      this.stateListeners.delete(listener);
    };
  }

  /** Get current connection state */
  getConnectionState(): ConnectionState {
    return this.connectionState;
  }

  /** Number of active subscriptions */
  getActiveSubscriptionCount(): number {
    return this.activeSubscriptions;
  }

  /** Dispose the client and close the WebSocket connection */
  dispose(): void {
    this.wsClient.dispose();
    this.stateListeners.clear();
    this.activeSubscriptions = 0;
    this.setConnectionState('disconnected');
  }

  private setConnectionState(state: ConnectionState): void {
    if (this.connectionState === state) return;
    this.connectionState = state;
    for (const listener of this.stateListeners) {
      listener(state);
    }
  }
}
