/**
 * AppPermission model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildCreateDocument,
  buildUpdateDocument,
  buildDeleteDocument,
} from '../query-builder';
import {
  type ConnectionResult,
  type FindManyArgs,
  type FindFirstArgs,
  type CreateArgs,
  type UpdateArgs,
  type DeleteArgs,
  type InferSelectResult,
} from '../select-types';
import {
  type AppPermission,
  type AppPermissionWithRelations,
  type AppPermissionSelect,
  type AppPermissionFilter,
  type AppPermissionsOrderBy,
  type CreateAppPermissionInput,
  type UpdateAppPermissionInput,
  type AppPermissionPatch,
} from '../input-types';

// ============================================================================
// Model Class
// ============================================================================
export class AppPermissionModel {
  constructor(private client: OrmClient) {}

  findMany<const S extends AppPermissionSelect>(
    args?: FindManyArgs<S, AppPermissionFilter, AppPermissionsOrderBy>
  ): QueryBuilder<{
    appPermissions: ConnectionResult<
      InferSelectResult<AppPermissionWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppPermission',
      'appPermissions',
      args?.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppPermissionFilter',
      'AppPermissionsOrderBy'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppPermission',
      fieldName: 'appPermissions',
      document,
      variables,
    });
  }

  findFirst<const S extends AppPermissionSelect>(
    args?: FindFirstArgs<S, AppPermissionFilter>
  ): QueryBuilder<{
    appPermissions: {
      nodes: InferSelectResult<AppPermissionWithRelations, S>[];
    };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppPermission',
      'appPermissions',
      args?.select,
      { where: args?.where },
      'AppPermissionFilter'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppPermission',
      fieldName: 'appPermissions',
      document,
      variables,
    });
  }

  create<const S extends AppPermissionSelect>(
    args: CreateArgs<S, CreateAppPermissionInput['appPermission']>
  ): QueryBuilder<{
    createAppPermission: {
      appPermission: InferSelectResult<AppPermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppPermission',
      'createAppPermission',
      'appPermission',
      args.select,
      args.data,
      'CreateAppPermissionInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppPermission',
      fieldName: 'createAppPermission',
      document,
      variables,
    });
  }

  update<const S extends AppPermissionSelect>(
    args: UpdateArgs<S, { id: string }, AppPermissionPatch>
  ): QueryBuilder<{
    updateAppPermission: {
      appPermission: InferSelectResult<AppPermissionWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateDocument(
      'AppPermission',
      'updateAppPermission',
      'appPermission',
      args.select,
      args.where,
      args.data,
      'UpdateAppPermissionInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppPermission',
      fieldName: 'updateAppPermission',
      document,
      variables,
    });
  }

  delete(
    args: DeleteArgs<{ id: string }>
  ): QueryBuilder<{ deleteAppPermission: { appPermission: { id: string } } }> {
    const { document, variables } = buildDeleteDocument(
      'AppPermission',
      'deleteAppPermission',
      'appPermission',
      args.where,
      'DeleteAppPermissionInput'
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppPermission',
      fieldName: 'deleteAppPermission',
      document,
      variables,
    });
  }
}
