/**
 * CLI command for mutation constructBlueprint
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';
import { getClient } from '../executor';
import { unflattenDotNotation, buildSelectFromPaths } from '../utils';
import type { ConstructBlueprintVariables } from '../../orm/mutation';
import type { ConstructBlueprintPayloadSelect } from '../../orm/input-types';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log(
        'construct-blueprint - Executes a blueprint definition by delegating to provision_* procedures. Creates a blueprint_construction record to track the attempt. Five phases: (1) provision_table() for each table with nodes[], fields[], policies[], and grants (table-level indexes/fts/unique_constraints are deferred), (2) provision_relation() for each relation, (3) provision_index() for top-level + deferred indexes, (4) provision_full_text_search() for top-level + deferred FTS, (5) provision_unique_constraint() for top-level + deferred unique constraints. Table-level indexes/fts/unique_constraints are deferred to phases 3-5 so they can reference columns created by relations in phase 2. Tables are identified by table_name with optional per-table schema_name. Relations use $type for relation_type with source_table/target_table. Returns the construction record ID on success, NULL on failure.\n\nUsage: construct-blueprint [OPTIONS]\n'
      );
      process.exit(0);
    }
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'input',
        message:
          'The exclusive input argument for this mutation. An object type, make sure to see documentation for this object\u2019s fields.',
        required: true,
      },
    ]);
    const client = getClient();
    const parsedAnswers = unflattenDotNotation(answers);
    const selectFields = buildSelectFromPaths((argv.select as string) ?? 'clientMutationId');
    const result = await client.mutation
      .constructBlueprint(
        parsedAnswers as unknown as ConstructBlueprintVariables,
        {
          select: selectFields,
        } as unknown as {
          select: ConstructBlueprintPayloadSelect;
        }
      )
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: constructBlueprint');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
