/**
 * CLI command for query currentUserId
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';
import { getClient } from '../executor';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log('current-user-id - currentUserId\n\nUsage: current-user-id [OPTIONS]\n');
      process.exit(0);
    }
    const client = getClient();
    const result = await client.query.currentUserId().execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: currentUserId');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
