/**
 * CLI commands for MembershipType
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
const fieldSchema: FieldSchema = {
  id: 'int',
  name: 'string',
  description: 'string',
  prefix: 'string',
};
const usage =
  '\nmembership-type <command>\n\nCommands:\n  list                  List all membershipType records\n  get                   Get a membershipType by ID\n  create                Create a new membershipType\n  update                Update an existing membershipType\n  delete                Delete a membershipType\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(_argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const client = getClient();
    const result = await client.membershipType
      .findMany({
        select: {
          id: true,
          name: true,
          description: true,
          prefix: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'name',
        message: 'name',
        required: true,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: true,
      },
      {
        type: 'text',
        name: 'prefix',
        message: 'prefix',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema);
    const client = getClient();
    const result = await client.membershipType
      .create({
        data: {
          name: cleanedData.name,
          description: cleanedData.description,
          prefix: cleanedData.prefix,
        } as any,
        select: {
          id: true,
          name: true,
          description: true,
          prefix: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'name',
        message: 'name',
        required: false,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: false,
      },
      {
        type: 'text',
        name: 'prefix',
        message: 'prefix',
        required: false,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema);
    const client = getClient();
    const result = await client.membershipType
      .update({
        where: {
          id: Number(answers.id),
        },
        data: {
          name: cleanedData.name,
          description: cleanedData.description,
          prefix: cleanedData.prefix,
        } as any,
        select: {
          id: true,
          name: true,
          description: true,
          prefix: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.membershipType
      .delete({
        where: {
          id: Number(answers.id),
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
