// @ts-nocheck
/**
 * CLI commands for OrgMember
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, stripUndefined } from '../utils';
const fieldSchema = {
  id: 'uuid',
  isAdmin: 'boolean',
  actorId: 'uuid',
  entityId: 'uuid',
};
const usage =
  '\norg-member <command>\n\nCommands:\n  list                  List all orgMember records\n  get                   Get a orgMember by ID\n  create                Create a new orgMember\n  update                Update an existing orgMember\n  delete                Delete a orgMember\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(_argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const client = getClient();
    const result = await client.orgMember
      .findMany({
        select: {
          id: true,
          isAdmin: true,
          actorId: true,
          entityId: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.orgMember
      .findOne({
        id: answers.id,
        select: {
          id: true,
          isAdmin: true,
          actorId: true,
          entityId: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'isAdmin',
        message: 'isAdmin',
        required: false,
      },
      {
        type: 'text',
        name: 'actorId',
        message: 'actorId',
        required: true,
      },
      {
        type: 'text',
        name: 'entityId',
        message: 'entityId',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema);
    const client = getClient();
    const result = await client.orgMember
      .create({
        data: {
          isAdmin: cleanedData.isAdmin,
          actorId: cleanedData.actorId,
          entityId: cleanedData.entityId,
        },
        select: {
          id: true,
          isAdmin: true,
          actorId: true,
          entityId: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'isAdmin',
        message: 'isAdmin',
        required: false,
      },
      {
        type: 'text',
        name: 'actorId',
        message: 'actorId',
        required: false,
      },
      {
        type: 'text',
        name: 'entityId',
        message: 'entityId',
        required: false,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema);
    const client = getClient();
    const result = await client.orgMember
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          isAdmin: cleanedData.isAdmin,
          actorId: cleanedData.actorId,
          entityId: cleanedData.entityId,
        },
        select: {
          id: true,
          isAdmin: true,
          actorId: true,
          entityId: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.orgMember
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
