/**
 * CLI commands for PhoneNumbersModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
import type { CreatePhoneNumbersModuleInput, PhoneNumbersModulePatch } from '../../orm/input-types';
const fieldSchema: FieldSchema = {
  id: 'uuid',
  databaseId: 'uuid',
  schemaId: 'uuid',
  privateSchemaId: 'uuid',
  tableId: 'uuid',
  ownerTableId: 'uuid',
  tableName: 'string',
  tableNameTrgmSimilarity: 'float',
  searchScore: 'float',
};
const usage =
  '\nphone-numbers-module <command>\n\nCommands:\n  list                  List all phoneNumbersModule records\n  get                   Get a phoneNumbersModule by ID\n  create                Create a new phoneNumbersModule\n  update                Update an existing phoneNumbersModule\n  delete                Delete a phoneNumbersModule\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(_argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const client = getClient();
    const result = await client.phoneNumbersModule
      .findMany({
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          privateSchemaId: true,
          tableId: true,
          ownerTableId: true,
          tableName: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.phoneNumbersModule
      .findOne({
        id: answers.id as string,
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          privateSchemaId: true,
          tableId: true,
          ownerTableId: true,
          tableName: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: true,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'privateSchemaId',
        message: 'privateSchemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'tableId',
        message: 'tableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'ownerTableId',
        message: 'ownerTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'tableName',
        message: 'tableName',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(
      answers,
      fieldSchema
    ) as CreatePhoneNumbersModuleInput['phoneNumbersModule'];
    const client = getClient();
    const result = await client.phoneNumbersModule
      .create({
        data: {
          databaseId: cleanedData.databaseId,
          schemaId: cleanedData.schemaId,
          privateSchemaId: cleanedData.privateSchemaId,
          tableId: cleanedData.tableId,
          ownerTableId: cleanedData.ownerTableId,
          tableName: cleanedData.tableName,
        },
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          privateSchemaId: true,
          tableId: true,
          ownerTableId: true,
          tableName: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'privateSchemaId',
        message: 'privateSchemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'tableId',
        message: 'tableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'ownerTableId',
        message: 'ownerTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'tableName',
        message: 'tableName',
        required: false,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as PhoneNumbersModulePatch;
    const client = getClient();
    const result = await client.phoneNumbersModule
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          databaseId: cleanedData.databaseId,
          schemaId: cleanedData.schemaId,
          privateSchemaId: cleanedData.privateSchemaId,
          tableId: cleanedData.tableId,
          ownerTableId: cleanedData.ownerTableId,
          tableName: cleanedData.tableName,
        },
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          privateSchemaId: true,
          tableId: true,
          ownerTableId: true,
          tableName: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.phoneNumbersModule
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
