/**
 * CLI command for mutation provisionDatabaseWithUser
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';
import { getClient } from '../executor';
import { parseMutationInput, buildSelectFromPaths } from '../utils';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log(
        'provision-database-with-user - provisionDatabaseWithUser\n\nUsage: provision-database-with-user [OPTIONS]\n'
      );
      process.exit(0);
    }
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'input',
        message:
          'The exclusive input argument for this mutation. An object type, make sure to see documentation for this object\u2019s fields.',
        required: true,
      },
    ]);
    const client = getClient();
    const parsedAnswers = parseMutationInput(answers);
    const selectFields = buildSelectFromPaths((argv.select as string) ?? 'clientMutationId');
    const result = await client.mutation
      .provisionDatabaseWithUser(
        parsedAnswers as never,
        {
          select: selectFields,
        } as never
      )
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: provisionDatabaseWithUser');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
