/**
 * CLI commands for Table
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
import type {
  CreateTableInput,
  TablePatch,
  TableSelect,
  TableFilter,
  TableOrderBy,
} from '../../orm/input-types';
import type { FindManyArgs, FindFirstArgs } from '../../orm/select-types';
const fieldSchema: FieldSchema = {
  id: 'uuid',
  databaseId: 'uuid',
  schemaId: 'uuid',
  name: 'string',
  label: 'string',
  description: 'string',
  smartTags: 'json',
  category: 'string',
  module: 'string',
  scope: 'int',
  useRls: 'boolean',
  timestamps: 'boolean',
  peoplestamps: 'boolean',
  pluralName: 'string',
  singularName: 'string',
  tags: 'string',
  inheritsId: 'uuid',
  createdAt: 'string',
  updatedAt: 'string',
};
const usage =
  '\ntable <command>\n\nCommands:\n  list                  List table records\n  find-first            Find first matching table record\n  get                   Get a table by ID\n  create                Create a new table\n  update                Update an existing table\n  delete                Delete a table\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      id: true,
      databaseId: true,
      schemaId: true,
      name: true,
      label: true,
      description: true,
      smartTags: true,
      category: true,
      module: true,
      scope: true,
      useRls: true,
      timestamps: true,
      peoplestamps: true,
      pluralName: true,
      singularName: true,
      tags: true,
      inheritsId: true,
      createdAt: true,
      updatedAt: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<TableSelect, TableFilter, TableOrderBy> & {
        select: TableSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.table.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      id: true,
      databaseId: true,
      schemaId: true,
      name: true,
      label: true,
      description: true,
      smartTags: true,
      category: true,
      module: true,
      scope: true,
      useRls: true,
      timestamps: true,
      peoplestamps: true,
      pluralName: true,
      singularName: true,
      tags: true,
      inheritsId: true,
      createdAt: true,
      updatedAt: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<TableSelect, TableFilter> & {
        select: TableSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.table.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.table
      .findOne({
        id: answers.id as string,
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          name: true,
          label: true,
          description: true,
          smartTags: true,
          category: true,
          module: true,
          scope: true,
          useRls: true,
          timestamps: true,
          peoplestamps: true,
          pluralName: true,
          singularName: true,
          tags: true,
          inheritsId: true,
          createdAt: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: true,
      },
      {
        type: 'text',
        name: 'name',
        message: 'name',
        required: true,
      },
      {
        type: 'text',
        name: 'label',
        message: 'label',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'smartTags',
        message: 'smartTags',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'category',
        message: 'category',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'module',
        message: 'module',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'scope',
        message: 'scope',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'boolean',
        name: 'useRls',
        message: 'useRls',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'boolean',
        name: 'timestamps',
        message: 'timestamps',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'boolean',
        name: 'peoplestamps',
        message: 'peoplestamps',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'pluralName',
        message: 'pluralName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'singularName',
        message: 'singularName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'tags',
        message: 'tags',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'inheritsId',
        message: 'inheritsId',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as CreateTableInput['table'];
    const client = getClient();
    const result = await client.table
      .create({
        data: {
          databaseId: cleanedData.databaseId,
          schemaId: cleanedData.schemaId,
          name: cleanedData.name,
          label: cleanedData.label,
          description: cleanedData.description,
          smartTags: cleanedData.smartTags,
          category: cleanedData.category,
          module: cleanedData.module,
          scope: cleanedData.scope,
          useRls: cleanedData.useRls,
          timestamps: cleanedData.timestamps,
          peoplestamps: cleanedData.peoplestamps,
          pluralName: cleanedData.pluralName,
          singularName: cleanedData.singularName,
          tags: cleanedData.tags,
          inheritsId: cleanedData.inheritsId,
        },
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          name: true,
          label: true,
          description: true,
          smartTags: true,
          category: true,
          module: true,
          scope: true,
          useRls: true,
          timestamps: true,
          peoplestamps: true,
          pluralName: true,
          singularName: true,
          tags: true,
          inheritsId: true,
          createdAt: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: false,
      },
      {
        type: 'text',
        name: 'name',
        message: 'name',
        required: false,
      },
      {
        type: 'text',
        name: 'label',
        message: 'label',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'smartTags',
        message: 'smartTags',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'category',
        message: 'category',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'module',
        message: 'module',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'scope',
        message: 'scope',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'boolean',
        name: 'useRls',
        message: 'useRls',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'boolean',
        name: 'timestamps',
        message: 'timestamps',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'boolean',
        name: 'peoplestamps',
        message: 'peoplestamps',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'pluralName',
        message: 'pluralName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'singularName',
        message: 'singularName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'tags',
        message: 'tags',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'inheritsId',
        message: 'inheritsId',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as TablePatch;
    const client = getClient();
    const result = await client.table
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          databaseId: cleanedData.databaseId,
          schemaId: cleanedData.schemaId,
          name: cleanedData.name,
          label: cleanedData.label,
          description: cleanedData.description,
          smartTags: cleanedData.smartTags,
          category: cleanedData.category,
          module: cleanedData.module,
          scope: cleanedData.scope,
          useRls: cleanedData.useRls,
          timestamps: cleanedData.timestamps,
          peoplestamps: cleanedData.peoplestamps,
          pluralName: cleanedData.pluralName,
          singularName: cleanedData.singularName,
          tags: cleanedData.tags,
          inheritsId: cleanedData.inheritsId,
        },
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          name: true,
          label: true,
          description: true,
          smartTags: true,
          category: true,
          module: true,
          scope: true,
          useRls: true,
          timestamps: true,
          peoplestamps: true,
          pluralName: true,
          singularName: true,
          tags: true,
          inheritsId: true,
          createdAt: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.table
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
