/**
 * CLI commands for UserAuthModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
import type { CreateUserAuthModuleInput, UserAuthModulePatch } from '../../orm/input-types';
const fieldSchema: FieldSchema = {
  id: 'uuid',
  databaseId: 'uuid',
  schemaId: 'uuid',
  emailsTableId: 'uuid',
  usersTableId: 'uuid',
  secretsTableId: 'uuid',
  encryptedTableId: 'uuid',
  sessionsTableId: 'uuid',
  sessionCredentialsTableId: 'uuid',
  auditsTableId: 'uuid',
  auditsTableName: 'string',
  signInFunction: 'string',
  signUpFunction: 'string',
  signOutFunction: 'string',
  setPasswordFunction: 'string',
  resetPasswordFunction: 'string',
  forgotPasswordFunction: 'string',
  sendVerificationEmailFunction: 'string',
  verifyEmailFunction: 'string',
  verifyPasswordFunction: 'string',
  checkPasswordFunction: 'string',
  sendAccountDeletionEmailFunction: 'string',
  deleteAccountFunction: 'string',
  signInOneTimeTokenFunction: 'string',
  oneTimeTokenFunction: 'string',
  extendTokenExpires: 'string',
};
const usage =
  '\nuser-auth-module <command>\n\nCommands:\n  list                  List userAuthModule records\n  find-first            Find first matching userAuthModule record\n  get                   Get a userAuthModule by ID\n  create                Create a new userAuthModule\n  update                Update an existing userAuthModule\n  delete                Delete a userAuthModule\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      id: true,
      databaseId: true,
      schemaId: true,
      emailsTableId: true,
      usersTableId: true,
      secretsTableId: true,
      encryptedTableId: true,
      sessionsTableId: true,
      sessionCredentialsTableId: true,
      auditsTableId: true,
      auditsTableName: true,
      signInFunction: true,
      signUpFunction: true,
      signOutFunction: true,
      setPasswordFunction: true,
      resetPasswordFunction: true,
      forgotPasswordFunction: true,
      sendVerificationEmailFunction: true,
      verifyEmailFunction: true,
      verifyPasswordFunction: true,
      checkPasswordFunction: true,
      sendAccountDeletionEmailFunction: true,
      deleteAccountFunction: true,
      signInOneTimeTokenFunction: true,
      oneTimeTokenFunction: true,
      extendTokenExpires: true,
    };
    const findManyArgs = parseFindManyArgs(argv, defaultSelect);
    const client = getClient();
    const result = await client.userAuthModule.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      id: true,
      databaseId: true,
      schemaId: true,
      emailsTableId: true,
      usersTableId: true,
      secretsTableId: true,
      encryptedTableId: true,
      sessionsTableId: true,
      sessionCredentialsTableId: true,
      auditsTableId: true,
      auditsTableName: true,
      signInFunction: true,
      signUpFunction: true,
      signOutFunction: true,
      setPasswordFunction: true,
      resetPasswordFunction: true,
      forgotPasswordFunction: true,
      sendVerificationEmailFunction: true,
      verifyEmailFunction: true,
      verifyPasswordFunction: true,
      checkPasswordFunction: true,
      sendAccountDeletionEmailFunction: true,
      deleteAccountFunction: true,
      signInOneTimeTokenFunction: true,
      oneTimeTokenFunction: true,
      extendTokenExpires: true,
    };
    const findFirstArgs = parseFindFirstArgs(argv, defaultSelect);
    const client = getClient();
    const result = await client.userAuthModule.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.userAuthModule
      .findOne({
        id: answers.id as string,
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          emailsTableId: true,
          usersTableId: true,
          secretsTableId: true,
          encryptedTableId: true,
          sessionsTableId: true,
          sessionCredentialsTableId: true,
          auditsTableId: true,
          auditsTableName: true,
          signInFunction: true,
          signUpFunction: true,
          signOutFunction: true,
          setPasswordFunction: true,
          resetPasswordFunction: true,
          forgotPasswordFunction: true,
          sendVerificationEmailFunction: true,
          verifyEmailFunction: true,
          verifyPasswordFunction: true,
          checkPasswordFunction: true,
          sendAccountDeletionEmailFunction: true,
          deleteAccountFunction: true,
          signInOneTimeTokenFunction: true,
          oneTimeTokenFunction: true,
          extendTokenExpires: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: true,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'emailsTableId',
        message: 'emailsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'usersTableId',
        message: 'usersTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'secretsTableId',
        message: 'secretsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'encryptedTableId',
        message: 'encryptedTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sessionsTableId',
        message: 'sessionsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sessionCredentialsTableId',
        message: 'sessionCredentialsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'auditsTableId',
        message: 'auditsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'auditsTableName',
        message: 'auditsTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'signInFunction',
        message: 'signInFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'signUpFunction',
        message: 'signUpFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'signOutFunction',
        message: 'signOutFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'setPasswordFunction',
        message: 'setPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'resetPasswordFunction',
        message: 'resetPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'forgotPasswordFunction',
        message: 'forgotPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sendVerificationEmailFunction',
        message: 'sendVerificationEmailFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'verifyEmailFunction',
        message: 'verifyEmailFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'verifyPasswordFunction',
        message: 'verifyPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'checkPasswordFunction',
        message: 'checkPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sendAccountDeletionEmailFunction',
        message: 'sendAccountDeletionEmailFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'deleteAccountFunction',
        message: 'deleteAccountFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'signInOneTimeTokenFunction',
        message: 'signInOneTimeTokenFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'oneTimeTokenFunction',
        message: 'oneTimeTokenFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'extendTokenExpires',
        message: 'extendTokenExpires',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(
      answers,
      fieldSchema
    ) as CreateUserAuthModuleInput['userAuthModule'];
    const client = getClient();
    const result = await client.userAuthModule
      .create({
        data: {
          databaseId: cleanedData.databaseId,
          schemaId: cleanedData.schemaId,
          emailsTableId: cleanedData.emailsTableId,
          usersTableId: cleanedData.usersTableId,
          secretsTableId: cleanedData.secretsTableId,
          encryptedTableId: cleanedData.encryptedTableId,
          sessionsTableId: cleanedData.sessionsTableId,
          sessionCredentialsTableId: cleanedData.sessionCredentialsTableId,
          auditsTableId: cleanedData.auditsTableId,
          auditsTableName: cleanedData.auditsTableName,
          signInFunction: cleanedData.signInFunction,
          signUpFunction: cleanedData.signUpFunction,
          signOutFunction: cleanedData.signOutFunction,
          setPasswordFunction: cleanedData.setPasswordFunction,
          resetPasswordFunction: cleanedData.resetPasswordFunction,
          forgotPasswordFunction: cleanedData.forgotPasswordFunction,
          sendVerificationEmailFunction: cleanedData.sendVerificationEmailFunction,
          verifyEmailFunction: cleanedData.verifyEmailFunction,
          verifyPasswordFunction: cleanedData.verifyPasswordFunction,
          checkPasswordFunction: cleanedData.checkPasswordFunction,
          sendAccountDeletionEmailFunction: cleanedData.sendAccountDeletionEmailFunction,
          deleteAccountFunction: cleanedData.deleteAccountFunction,
          signInOneTimeTokenFunction: cleanedData.signInOneTimeTokenFunction,
          oneTimeTokenFunction: cleanedData.oneTimeTokenFunction,
          extendTokenExpires: cleanedData.extendTokenExpires,
        },
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          emailsTableId: true,
          usersTableId: true,
          secretsTableId: true,
          encryptedTableId: true,
          sessionsTableId: true,
          sessionCredentialsTableId: true,
          auditsTableId: true,
          auditsTableName: true,
          signInFunction: true,
          signUpFunction: true,
          signOutFunction: true,
          setPasswordFunction: true,
          resetPasswordFunction: true,
          forgotPasswordFunction: true,
          sendVerificationEmailFunction: true,
          verifyEmailFunction: true,
          verifyPasswordFunction: true,
          checkPasswordFunction: true,
          sendAccountDeletionEmailFunction: true,
          deleteAccountFunction: true,
          signInOneTimeTokenFunction: true,
          oneTimeTokenFunction: true,
          extendTokenExpires: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'emailsTableId',
        message: 'emailsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'usersTableId',
        message: 'usersTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'secretsTableId',
        message: 'secretsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'encryptedTableId',
        message: 'encryptedTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sessionsTableId',
        message: 'sessionsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sessionCredentialsTableId',
        message: 'sessionCredentialsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'auditsTableId',
        message: 'auditsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'auditsTableName',
        message: 'auditsTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'signInFunction',
        message: 'signInFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'signUpFunction',
        message: 'signUpFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'signOutFunction',
        message: 'signOutFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'setPasswordFunction',
        message: 'setPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'resetPasswordFunction',
        message: 'resetPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'forgotPasswordFunction',
        message: 'forgotPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sendVerificationEmailFunction',
        message: 'sendVerificationEmailFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'verifyEmailFunction',
        message: 'verifyEmailFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'verifyPasswordFunction',
        message: 'verifyPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'checkPasswordFunction',
        message: 'checkPasswordFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sendAccountDeletionEmailFunction',
        message: 'sendAccountDeletionEmailFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'deleteAccountFunction',
        message: 'deleteAccountFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'signInOneTimeTokenFunction',
        message: 'signInOneTimeTokenFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'oneTimeTokenFunction',
        message: 'oneTimeTokenFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'extendTokenExpires',
        message: 'extendTokenExpires',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as UserAuthModulePatch;
    const client = getClient();
    const result = await client.userAuthModule
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          databaseId: cleanedData.databaseId,
          schemaId: cleanedData.schemaId,
          emailsTableId: cleanedData.emailsTableId,
          usersTableId: cleanedData.usersTableId,
          secretsTableId: cleanedData.secretsTableId,
          encryptedTableId: cleanedData.encryptedTableId,
          sessionsTableId: cleanedData.sessionsTableId,
          sessionCredentialsTableId: cleanedData.sessionCredentialsTableId,
          auditsTableId: cleanedData.auditsTableId,
          auditsTableName: cleanedData.auditsTableName,
          signInFunction: cleanedData.signInFunction,
          signUpFunction: cleanedData.signUpFunction,
          signOutFunction: cleanedData.signOutFunction,
          setPasswordFunction: cleanedData.setPasswordFunction,
          resetPasswordFunction: cleanedData.resetPasswordFunction,
          forgotPasswordFunction: cleanedData.forgotPasswordFunction,
          sendVerificationEmailFunction: cleanedData.sendVerificationEmailFunction,
          verifyEmailFunction: cleanedData.verifyEmailFunction,
          verifyPasswordFunction: cleanedData.verifyPasswordFunction,
          checkPasswordFunction: cleanedData.checkPasswordFunction,
          sendAccountDeletionEmailFunction: cleanedData.sendAccountDeletionEmailFunction,
          deleteAccountFunction: cleanedData.deleteAccountFunction,
          signInOneTimeTokenFunction: cleanedData.signInOneTimeTokenFunction,
          oneTimeTokenFunction: cleanedData.oneTimeTokenFunction,
          extendTokenExpires: cleanedData.extendTokenExpires,
        },
        select: {
          id: true,
          databaseId: true,
          schemaId: true,
          emailsTableId: true,
          usersTableId: true,
          secretsTableId: true,
          encryptedTableId: true,
          sessionsTableId: true,
          sessionCredentialsTableId: true,
          auditsTableId: true,
          auditsTableName: true,
          signInFunction: true,
          signUpFunction: true,
          signOutFunction: true,
          setPasswordFunction: true,
          resetPasswordFunction: true,
          forgotPasswordFunction: true,
          sendVerificationEmailFunction: true,
          verifyEmailFunction: true,
          verifyPasswordFunction: true,
          checkPasswordFunction: true,
          sendAccountDeletionEmailFunction: true,
          deleteAccountFunction: true,
          signInOneTimeTokenFunction: true,
          oneTimeTokenFunction: true,
          extendTokenExpires: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.userAuthModule
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
