/**
 * CLI command map and entry point
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import contextCmd from './commands/context';
import authCmd from './commands/auth';
import appLimitCapCmd from './commands/app-limit-cap';
import appLimitCapsDefaultCmd from './commands/app-limit-caps-default';
import appLimitCmd from './commands/app-limit';
import appLimitCreditCodeCmd from './commands/app-limit-credit-code';
import appLimitCreditCodeItemCmd from './commands/app-limit-credit-code-item';
import appLimitCreditCmd from './commands/app-limit-credit';
import appLimitCreditRedemptionCmd from './commands/app-limit-credit-redemption';
import appLimitDefaultCmd from './commands/app-limit-default';
import appLimitEventCmd from './commands/app-limit-event';
import appLimitWarningCmd from './commands/app-limit-warning';
import orgLimitAggregateCmd from './commands/org-limit-aggregate';
import orgLimitCapCmd from './commands/org-limit-cap';
import orgLimitCapsDefaultCmd from './commands/org-limit-caps-default';
import orgLimitCmd from './commands/org-limit';
import orgLimitCreditCmd from './commands/org-limit-credit';
import orgLimitDefaultCmd from './commands/org-limit-default';
import orgLimitEventCmd from './commands/org-limit-event';
import orgLimitWarningCmd from './commands/org-limit-warning';
import provisionBucketCmd from './commands/provision-bucket';
import seedAppLimitCapsDefaultsCmd from './commands/seed-app-limit-caps-defaults';
import seedAppLimitDefaultsCmd from './commands/seed-app-limit-defaults';
import seedOrgLimitCapsDefaultsCmd from './commands/seed-org-limit-caps-defaults';
import seedOrgLimitDefaultsCmd from './commands/seed-org-limit-defaults';
const createCommandMap: () => Record<
  string,
  (
    argv: Partial<Record<string, unknown>>,
    prompter: Inquirerer,
    options: CLIOptions
  ) => Promise<void>
> = () => ({
  context: contextCmd,
  auth: authCmd,
  'app-limit-cap': appLimitCapCmd,
  'app-limit-caps-default': appLimitCapsDefaultCmd,
  'app-limit': appLimitCmd,
  'app-limit-credit-code': appLimitCreditCodeCmd,
  'app-limit-credit-code-item': appLimitCreditCodeItemCmd,
  'app-limit-credit': appLimitCreditCmd,
  'app-limit-credit-redemption': appLimitCreditRedemptionCmd,
  'app-limit-default': appLimitDefaultCmd,
  'app-limit-event': appLimitEventCmd,
  'app-limit-warning': appLimitWarningCmd,
  'org-limit-aggregate': orgLimitAggregateCmd,
  'org-limit-cap': orgLimitCapCmd,
  'org-limit-caps-default': orgLimitCapsDefaultCmd,
  'org-limit': orgLimitCmd,
  'org-limit-credit': orgLimitCreditCmd,
  'org-limit-default': orgLimitDefaultCmd,
  'org-limit-event': orgLimitEventCmd,
  'org-limit-warning': orgLimitWarningCmd,
  'provision-bucket': provisionBucketCmd,
  'seed-app-limit-caps-defaults': seedAppLimitCapsDefaultsCmd,
  'seed-app-limit-defaults': seedAppLimitDefaultsCmd,
  'seed-org-limit-caps-defaults': seedOrgLimitCapsDefaultsCmd,
  'seed-org-limit-defaults': seedOrgLimitDefaultsCmd,
});
const usage =
  '\ncsdk <command>\n\nCommands:\n  context               Manage API contexts\n  auth                  Manage authentication\n  app-limit-cap        appLimitCap CRUD operations\n  app-limit-caps-default appLimitCapsDefault CRUD operations\n  app-limit            appLimit CRUD operations\n  app-limit-credit-code appLimitCreditCode CRUD operations\n  app-limit-credit-code-item appLimitCreditCodeItem CRUD operations\n  app-limit-credit     appLimitCredit CRUD operations\n  app-limit-credit-redemption appLimitCreditRedemption CRUD operations\n  app-limit-default    appLimitDefault CRUD operations\n  app-limit-event      appLimitEvent CRUD operations\n  app-limit-warning    appLimitWarning CRUD operations\n  org-limit-aggregate  orgLimitAggregate CRUD operations\n  org-limit-cap        orgLimitCap CRUD operations\n  org-limit-caps-default orgLimitCapsDefault CRUD operations\n  org-limit            orgLimit CRUD operations\n  org-limit-credit     orgLimitCredit CRUD operations\n  org-limit-default    orgLimitDefault CRUD operations\n  org-limit-event      orgLimitEvent CRUD operations\n  org-limit-warning    orgLimitWarning CRUD operations\n  provision-bucket     Provision an S3 bucket for a logical bucket in the database.\nReads the bucket config via RLS, then creates and configures\nthe S3 bucket with the appropriate privacy policies, CORS rules,\nand lifecycle settings.\n  seed-app-limit-caps-defaults seedAppLimitCapsDefaults\n  seed-app-limit-defaults seedAppLimitDefaults\n  seed-org-limit-caps-defaults seedOrgLimitCapsDefaults\n  seed-org-limit-defaults seedOrgLimitDefaults\n\n  --help, -h            Show this help message\n  --version, -v         Show version\n';
export const commands = async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  let { first: command, newArgv } = extractFirst(argv);
  const commandMap = createCommandMap();
  if (!command) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'command',
        message: 'What do you want to do?',
        options: Object.keys(commandMap),
      },
    ]);
    command = answer.command as string;
  }
  const commandFn = commandMap[command];
  if (!commandFn) {
    console.log(usage);
    console.error(`Unknown command: ${command}`);
    process.exit(1);
  }
  await commandFn(newArgv, prompter, options);
  prompter.close();
  return argv;
};
