/**
 * Single item query hook for InternalSecret
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { internalSecretKeys } from '../query-keys';
import type { InternalSecretSelect, InternalSecretWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { InternalSecretSelect, InternalSecretWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const internalSecretQueryKey = internalSecretKeys.detail;
/**
 * Query hook for fetching a single InternalSecret
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useInternalSecretQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useInternalSecretQuery<
  S extends InternalSecretSelect,
  TData = {
    internalSecret: InferSelectResult<InternalSecretWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, InternalSecretSelect>;
  } & Omit<
    UseQueryOptions<
      {
        internalSecret: InferSelectResult<InternalSecretWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useInternalSecretQuery(
  params: {
    id: string;
    selection: SelectionConfig<InternalSecretSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<InternalSecretSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: internalSecretKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .internalSecret.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch a single InternalSecret without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchInternalSecretQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchInternalSecretQuery<S extends InternalSecretSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, InternalSecretSelect>;
}): Promise<{
  internalSecret: InferSelectResult<InternalSecretWithRelations, S> | null;
}>;
export async function fetchInternalSecretQuery(params: {
  id: string;
  selection: SelectionConfig<InternalSecretSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<InternalSecretSelect>(params.selection);
  return getClient()
    .internalSecret.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Prefetch a single InternalSecret for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchInternalSecretQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchInternalSecretQuery<S extends InternalSecretSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, InternalSecretSelect>;
  }
): Promise<void>;
export async function prefetchInternalSecretQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<InternalSecretSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<InternalSecretSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: internalSecretKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .internalSecret.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
