/**
 * Files a reviewer has read, pinned to the blob they read
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { proposalFileViewKeys } from '../query-keys';
import type { ProposalFileViewSelect, ProposalFileViewWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { ProposalFileViewSelect, ProposalFileViewWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const proposalFileViewQueryKey = proposalFileViewKeys.detail;
/**
 * Files a reviewer has read, pinned to the blob they read
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useProposalFileViewQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useProposalFileViewQuery<
  S extends ProposalFileViewSelect,
  TData = {
    proposalFileView: InferSelectResult<ProposalFileViewWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, ProposalFileViewSelect>;
  } & Omit<
    UseQueryOptions<
      {
        proposalFileView: InferSelectResult<ProposalFileViewWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useProposalFileViewQuery(
  params: {
    id: string;
    selection: SelectionConfig<ProposalFileViewSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<ProposalFileViewSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: proposalFileViewKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .proposalFileView.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Files a reviewer has read, pinned to the blob they read
 *
 * @example
 * ```ts
 * const data = await fetchProposalFileViewQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchProposalFileViewQuery<S extends ProposalFileViewSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, ProposalFileViewSelect>;
}): Promise<{
  proposalFileView: InferSelectResult<ProposalFileViewWithRelations, S> | null;
}>;
export async function fetchProposalFileViewQuery(params: {
  id: string;
  selection: SelectionConfig<ProposalFileViewSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<ProposalFileViewSelect>(params.selection);
  return getClient()
    .proposalFileView.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Files a reviewer has read, pinned to the blob they read
 *
 * @example
 * ```ts
 * await prefetchProposalFileViewQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchProposalFileViewQuery<S extends ProposalFileViewSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, ProposalFileViewSelect>;
  }
): Promise<void>;
export async function prefetchProposalFileViewQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<ProposalFileViewSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<ProposalFileViewSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: proposalFileViewKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .proposalFileView.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
