/**
 * Installed resource bundle ("release") — groups a set of resources; params are merkle-versioned in the scope's shared infra store for rollback
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { resourceInstallationKeys } from '../query-keys';
import type {
  ResourceInstallationSelect,
  ResourceInstallationWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  ResourceInstallationSelect,
  ResourceInstallationWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const resourceInstallationQueryKey = resourceInstallationKeys.detail;
/**
 * Installed resource bundle ("release") — groups a set of resources; params are merkle-versioned in the scope's shared infra store for rollback
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useResourceInstallationQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useResourceInstallationQuery<
  S extends ResourceInstallationSelect,
  TData = {
    resourceInstallation: InferSelectResult<ResourceInstallationWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, ResourceInstallationSelect>;
  } & Omit<
    UseQueryOptions<
      {
        resourceInstallation: InferSelectResult<ResourceInstallationWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useResourceInstallationQuery(
  params: {
    id: string;
    selection: SelectionConfig<ResourceInstallationSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<ResourceInstallationSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: resourceInstallationKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .resourceInstallation.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Installed resource bundle ("release") — groups a set of resources; params are merkle-versioned in the scope's shared infra store for rollback
 *
 * @example
 * ```ts
 * const data = await fetchResourceInstallationQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchResourceInstallationQuery<S extends ResourceInstallationSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, ResourceInstallationSelect>;
}): Promise<{
  resourceInstallation: InferSelectResult<ResourceInstallationWithRelations, S> | null;
}>;
export async function fetchResourceInstallationQuery(params: {
  id: string;
  selection: SelectionConfig<ResourceInstallationSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<ResourceInstallationSelect>(params.selection);
  return getClient()
    .resourceInstallation.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Installed resource bundle ("release") — groups a set of resources; params are merkle-versioned in the scope's shared infra store for rollback
 *
 * @example
 * ```ts
 * await prefetchResourceInstallationQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchResourceInstallationQuery<S extends ResourceInstallationSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, ResourceInstallationSelect>;
  }
): Promise<void>;
export async function prefetchResourceInstallationQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<ResourceInstallationSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<ResourceInstallationSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: resourceInstallationKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .resourceInstallation.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
