/**
 * Webhook route authority: (host, path) -> function task_identifier invoked through the webhook channel, with provider, signing-secret reference, and replay window
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { webhookEndpointKeys } from '../query-keys';
import type {
  WebhookEndpointSelect,
  WebhookEndpointWithRelations,
  WebhookEndpointFilter,
  WebhookEndpointOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  WebhookEndpointSelect,
  WebhookEndpointWithRelations,
  WebhookEndpointFilter,
  WebhookEndpointOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const webhookEndpointsQueryKey = webhookEndpointKeys.list;
/**
 * Webhook route authority: (host, path) -> function task_identifier invoked through the webhook channel, with provider, signing-secret reference, and replay window
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useWebhookEndpointsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useWebhookEndpointsQuery<
  S extends WebhookEndpointSelect,
  TData = {
    webhookEndpoints: ConnectionResult<InferSelectResult<WebhookEndpointWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, WebhookEndpointFilter, WebhookEndpointOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, WebhookEndpointSelect>;
  } & Omit<
    UseQueryOptions<
      {
        webhookEndpoints: ConnectionResult<InferSelectResult<WebhookEndpointWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useWebhookEndpointsQuery(
  params: {
    selection: ListSelectionConfig<
      WebhookEndpointSelect,
      WebhookEndpointFilter,
      WebhookEndpointOrderBy
    >;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    WebhookEndpointSelect,
    WebhookEndpointFilter,
    WebhookEndpointOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: webhookEndpointKeys.list(args),
    queryFn: () => getClient().webhookEndpoint.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Webhook route authority: (host, path) -> function task_identifier invoked through the webhook channel, with provider, signing-secret reference, and replay window
 *
 * @example
 * ```ts
 * const data = await fetchWebhookEndpointsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchWebhookEndpointsQuery<S extends WebhookEndpointSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, WebhookEndpointFilter, WebhookEndpointOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, WebhookEndpointSelect>;
}): Promise<{
  webhookEndpoints: ConnectionResult<InferSelectResult<WebhookEndpointWithRelations, S>>;
}>;
export async function fetchWebhookEndpointsQuery(params: {
  selection: ListSelectionConfig<
    WebhookEndpointSelect,
    WebhookEndpointFilter,
    WebhookEndpointOrderBy
  >;
}) {
  const args = buildListSelectionArgs<
    WebhookEndpointSelect,
    WebhookEndpointFilter,
    WebhookEndpointOrderBy
  >(params.selection);
  return getClient().webhookEndpoint.findMany(args).unwrap();
}
/**
 * Webhook route authority: (host, path) -> function task_identifier invoked through the webhook channel, with provider, signing-secret reference, and replay window
 *
 * @example
 * ```ts
 * await prefetchWebhookEndpointsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchWebhookEndpointsQuery<S extends WebhookEndpointSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, WebhookEndpointFilter, WebhookEndpointOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, WebhookEndpointSelect>;
  }
): Promise<void>;
export async function prefetchWebhookEndpointsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<
      WebhookEndpointSelect,
      WebhookEndpointFilter,
      WebhookEndpointOrderBy
    >;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    WebhookEndpointSelect,
    WebhookEndpointFilter,
    WebhookEndpointOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: webhookEndpointKeys.list(args),
    queryFn: () => getClient().webhookEndpoint.findMany(args).unwrap(),
  });
}
