/**
 * CLI commands for Field
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
import type {
  CreateFieldInput,
  FieldPatch,
  FieldSelect,
  FieldFilter,
  FieldOrderBy,
} from '../../orm/input-types';
import type { FindManyArgs, FindFirstArgs } from '../../orm/select-types';
const fieldSchema: FieldSchema = {
  apiRequired: 'boolean',
  category: 'string',
  chk: 'json',
  chkExpr: 'json',
  createdAt: 'string',
  databaseId: 'uuid',
  defaultValue: 'json',
  description: 'string',
  fieldOrder: 'int',
  generationExpression: 'json',
  generationType: 'string',
  id: 'uuid',
  identityGeneration: 'string',
  identityOptions: 'json',
  isRequired: 'boolean',
  label: 'string',
  max: 'float',
  min: 'float',
  name: 'string',
  regexp: 'string',
  smartTags: 'json',
  tableId: 'uuid',
  tags: 'string',
  type: 'json',
  updatedAt: 'string',
};
const usage =
  '\nfield <command>\n\nCommands:\n  list                  List field records\n  find-first            Find first matching field record\n  get                   Get a field by ID\n  create                Create a new field\n  update                Update an existing field\n  delete                Delete a field\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      apiRequired: true,
      category: true,
      chk: true,
      chkExpr: true,
      createdAt: true,
      databaseId: true,
      defaultValue: true,
      description: true,
      fieldOrder: true,
      generationExpression: true,
      generationType: true,
      id: true,
      identityGeneration: true,
      identityOptions: true,
      isRequired: true,
      label: true,
      max: true,
      min: true,
      name: true,
      regexp: true,
      smartTags: true,
      tableId: true,
      tags: true,
      type: true,
      updatedAt: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<FieldSelect, FieldFilter, FieldOrderBy> & {
        select: FieldSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.field.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      apiRequired: true,
      category: true,
      chk: true,
      chkExpr: true,
      createdAt: true,
      databaseId: true,
      defaultValue: true,
      description: true,
      fieldOrder: true,
      generationExpression: true,
      generationType: true,
      id: true,
      identityGeneration: true,
      identityOptions: true,
      isRequired: true,
      label: true,
      max: true,
      min: true,
      name: true,
      regexp: true,
      smartTags: true,
      tableId: true,
      tags: true,
      type: true,
      updatedAt: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<FieldSelect, FieldFilter, FieldOrderBy> & {
        select: FieldSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.field.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.field
      .findOne({
        id: answers.id as string,
        select: {
          apiRequired: true,
          category: true,
          chk: true,
          chkExpr: true,
          createdAt: true,
          databaseId: true,
          defaultValue: true,
          description: true,
          fieldOrder: true,
          generationExpression: true,
          generationType: true,
          id: true,
          identityGeneration: true,
          identityOptions: true,
          isRequired: true,
          label: true,
          max: true,
          min: true,
          name: true,
          regexp: true,
          smartTags: true,
          tableId: true,
          tags: true,
          type: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'boolean',
        name: 'apiRequired',
        message: 'apiRequired',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'category',
        message: 'category',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'chk',
        message: 'chk',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'chkExpr',
        message: 'chkExpr',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'defaultValue',
        message: 'defaultValue',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'fieldOrder',
        message: 'fieldOrder',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'generationExpression',
        message: 'generationExpression',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'generationType',
        message: 'generationType',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'identityGeneration',
        message: 'identityGeneration',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'identityOptions',
        message: 'identityOptions',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'boolean',
        name: 'isRequired',
        message: 'isRequired',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'label',
        message: 'label',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'max',
        message: 'max',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'min',
        message: 'min',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'name',
        message: 'name',
        required: true,
      },
      {
        type: 'text',
        name: 'regexp',
        message: 'regexp',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'smartTags',
        message: 'smartTags',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'tableId',
        message: 'tableId',
        required: true,
      },
      {
        type: 'text',
        name: 'tags',
        message: 'tags',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'type',
        message: 'type',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as CreateFieldInput['field'];
    const client = getClient();
    const result = await client.field
      .create({
        data: {
          apiRequired: cleanedData.apiRequired,
          category: cleanedData.category,
          chk: cleanedData.chk,
          chkExpr: cleanedData.chkExpr,
          databaseId: cleanedData.databaseId,
          defaultValue: cleanedData.defaultValue,
          description: cleanedData.description,
          fieldOrder: cleanedData.fieldOrder,
          generationExpression: cleanedData.generationExpression,
          generationType: cleanedData.generationType,
          identityGeneration: cleanedData.identityGeneration,
          identityOptions: cleanedData.identityOptions,
          isRequired: cleanedData.isRequired,
          label: cleanedData.label,
          max: cleanedData.max,
          min: cleanedData.min,
          name: cleanedData.name,
          regexp: cleanedData.regexp,
          smartTags: cleanedData.smartTags,
          tableId: cleanedData.tableId,
          tags: cleanedData.tags,
          type: cleanedData.type,
        },
        select: {
          apiRequired: true,
          category: true,
          chk: true,
          chkExpr: true,
          createdAt: true,
          databaseId: true,
          defaultValue: true,
          description: true,
          fieldOrder: true,
          generationExpression: true,
          generationType: true,
          id: true,
          identityGeneration: true,
          identityOptions: true,
          isRequired: true,
          label: true,
          max: true,
          min: true,
          name: true,
          regexp: true,
          smartTags: true,
          tableId: true,
          tags: true,
          type: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'boolean',
        name: 'apiRequired',
        message: 'apiRequired',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'category',
        message: 'category',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'chk',
        message: 'chk',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'chkExpr',
        message: 'chkExpr',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'defaultValue',
        message: 'defaultValue',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'fieldOrder',
        message: 'fieldOrder',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'generationExpression',
        message: 'generationExpression',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'generationType',
        message: 'generationType',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'identityGeneration',
        message: 'identityGeneration',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'identityOptions',
        message: 'identityOptions',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'boolean',
        name: 'isRequired',
        message: 'isRequired',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'label',
        message: 'label',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'max',
        message: 'max',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'min',
        message: 'min',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'name',
        message: 'name',
        required: false,
      },
      {
        type: 'text',
        name: 'regexp',
        message: 'regexp',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'smartTags',
        message: 'smartTags',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'tableId',
        message: 'tableId',
        required: false,
      },
      {
        type: 'text',
        name: 'tags',
        message: 'tags',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'type',
        message: 'type',
        required: false,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as FieldPatch;
    const client = getClient();
    const result = await client.field
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          apiRequired: cleanedData.apiRequired,
          category: cleanedData.category,
          chk: cleanedData.chk,
          chkExpr: cleanedData.chkExpr,
          databaseId: cleanedData.databaseId,
          defaultValue: cleanedData.defaultValue,
          description: cleanedData.description,
          fieldOrder: cleanedData.fieldOrder,
          generationExpression: cleanedData.generationExpression,
          generationType: cleanedData.generationType,
          identityGeneration: cleanedData.identityGeneration,
          identityOptions: cleanedData.identityOptions,
          isRequired: cleanedData.isRequired,
          label: cleanedData.label,
          max: cleanedData.max,
          min: cleanedData.min,
          name: cleanedData.name,
          regexp: cleanedData.regexp,
          smartTags: cleanedData.smartTags,
          tableId: cleanedData.tableId,
          tags: cleanedData.tags,
          type: cleanedData.type,
        },
        select: {
          apiRequired: true,
          category: true,
          chk: true,
          chkExpr: true,
          createdAt: true,
          databaseId: true,
          defaultValue: true,
          description: true,
          fieldOrder: true,
          generationExpression: true,
          generationType: true,
          id: true,
          identityGeneration: true,
          identityOptions: true,
          isRequired: true,
          label: true,
          max: true,
          min: true,
          name: true,
          regexp: true,
          smartTags: true,
          tableId: true,
          tags: true,
          type: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.field
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
