/**
 * CLI commands for PlatformSiteMetadatum
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
import type {
  CreatePlatformSiteMetadatumInput,
  PlatformSiteMetadatumPatch,
  PlatformSiteMetadatumSelect,
  PlatformSiteMetadatumFilter,
  PlatformSiteMetadatumOrderBy,
} from '../../orm/input-types';
import type { FindManyArgs, FindFirstArgs } from '../../orm/select-types';
const fieldSchema: FieldSchema = {
  appleTouchIcon: 'string',
  canonicalUrl: 'string',
  commitId: 'uuid',
  createdAt: 'string',
  description: 'string',
  favicon: 'string',
  id: 'uuid',
  logo: 'string',
  ogImage: 'string',
  robots: 'string',
  robotsSeededFrom: 'json',
  siteId: 'uuid',
  storeId: 'uuid',
  title: 'string',
  updatedAt: 'string',
};
const usage =
  '\nplatform-site-metadatum <command>\n\nCommands:\n  list                  List platformSiteMetadatum records\n  find-first            Find first matching platformSiteMetadatum record\n  get                   Get a platformSiteMetadatum by ID\n  create                Create a new platformSiteMetadatum\n  update                Update an existing platformSiteMetadatum\n  delete                Delete a platformSiteMetadatum\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      appleTouchIcon: true,
      canonicalUrl: true,
      commitId: true,
      createdAt: true,
      description: true,
      favicon: true,
      id: true,
      logo: true,
      ogImage: true,
      robots: true,
      robotsSeededFrom: true,
      siteId: true,
      storeId: true,
      title: true,
      updatedAt: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<
        PlatformSiteMetadatumSelect,
        PlatformSiteMetadatumFilter,
        PlatformSiteMetadatumOrderBy
      > & {
        select: PlatformSiteMetadatumSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.platformSiteMetadatum.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      appleTouchIcon: true,
      canonicalUrl: true,
      commitId: true,
      createdAt: true,
      description: true,
      favicon: true,
      id: true,
      logo: true,
      ogImage: true,
      robots: true,
      robotsSeededFrom: true,
      siteId: true,
      storeId: true,
      title: true,
      updatedAt: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<
        PlatformSiteMetadatumSelect,
        PlatformSiteMetadatumFilter,
        PlatformSiteMetadatumOrderBy
      > & {
        select: PlatformSiteMetadatumSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.platformSiteMetadatum.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.platformSiteMetadatum
      .findOne({
        id: answers.id as string,
        select: {
          appleTouchIcon: true,
          canonicalUrl: true,
          commitId: true,
          createdAt: true,
          description: true,
          favicon: true,
          id: true,
          logo: true,
          ogImage: true,
          robots: true,
          robotsSeededFrom: true,
          siteId: true,
          storeId: true,
          title: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'appleTouchIcon',
        message: 'appleTouchIcon',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'canonicalUrl',
        message: 'canonicalUrl',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'commitId',
        message: 'commitId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'favicon',
        message: 'favicon',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'logo',
        message: 'logo',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'ogImage',
        message: 'ogImage',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'robots',
        message: 'robots',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'robotsSeededFrom',
        message: 'robotsSeededFrom',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'siteId',
        message: 'siteId',
        required: true,
      },
      {
        type: 'text',
        name: 'storeId',
        message: 'storeId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'title',
        message: 'title',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(
      answers,
      fieldSchema
    ) as CreatePlatformSiteMetadatumInput['platformSiteMetadatum'];
    const client = getClient();
    const result = await client.platformSiteMetadatum
      .create({
        data: {
          appleTouchIcon: cleanedData.appleTouchIcon,
          canonicalUrl: cleanedData.canonicalUrl,
          commitId: cleanedData.commitId,
          description: cleanedData.description,
          favicon: cleanedData.favicon,
          logo: cleanedData.logo,
          ogImage: cleanedData.ogImage,
          robots: cleanedData.robots,
          robotsSeededFrom: cleanedData.robotsSeededFrom,
          siteId: cleanedData.siteId,
          storeId: cleanedData.storeId,
          title: cleanedData.title,
        },
        select: {
          appleTouchIcon: true,
          canonicalUrl: true,
          commitId: true,
          createdAt: true,
          description: true,
          favicon: true,
          id: true,
          logo: true,
          ogImage: true,
          robots: true,
          robotsSeededFrom: true,
          siteId: true,
          storeId: true,
          title: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'appleTouchIcon',
        message: 'appleTouchIcon',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'canonicalUrl',
        message: 'canonicalUrl',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'commitId',
        message: 'commitId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'description',
        message: 'description',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'favicon',
        message: 'favicon',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'logo',
        message: 'logo',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'ogImage',
        message: 'ogImage',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'robots',
        message: 'robots',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'robotsSeededFrom',
        message: 'robotsSeededFrom',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'siteId',
        message: 'siteId',
        required: false,
      },
      {
        type: 'text',
        name: 'storeId',
        message: 'storeId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'title',
        message: 'title',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as PlatformSiteMetadatumPatch;
    const client = getClient();
    const result = await client.platformSiteMetadatum
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          appleTouchIcon: cleanedData.appleTouchIcon,
          canonicalUrl: cleanedData.canonicalUrl,
          commitId: cleanedData.commitId,
          description: cleanedData.description,
          favicon: cleanedData.favicon,
          logo: cleanedData.logo,
          ogImage: cleanedData.ogImage,
          robots: cleanedData.robots,
          robotsSeededFrom: cleanedData.robotsSeededFrom,
          siteId: cleanedData.siteId,
          storeId: cleanedData.storeId,
          title: cleanedData.title,
        },
        select: {
          appleTouchIcon: true,
          canonicalUrl: true,
          commitId: true,
          createdAt: true,
          description: true,
          favicon: true,
          id: true,
          logo: true,
          ogImage: true,
          robots: true,
          robotsSeededFrom: true,
          siteId: true,
          storeId: true,
          title: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.platformSiteMetadatum
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
