/**
 * CLI command for query platformVerifySitePreviewToken
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';
import { getClient } from '../executor';
import type { PlatformVerifySitePreviewTokenVariables } from '../../orm/query';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log(
        'platform-verify-site-preview-token - platformVerifySitePreviewToken\n\nUsage: platform-verify-site-preview-token [OPTIONS]\n'
      );
      process.exit(0);
    }
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'siteId',
        message: 'siteId',
      },
      {
        type: 'text',
        name: 'token',
        message: 'token',
      },
    ]);
    const client = getClient();
    const result = await client.query
      .platformVerifySitePreviewToken(answers as unknown as PlatformVerifySitePreviewTokenVariables)
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: platformVerifySitePreviewToken');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
