/**
 * Cache invalidation helpers
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

// ============================================================================
// Type-safe cache invalidation utilities
//
// Features:
// - Simple invalidation helpers per entity
// - Cascade invalidation for parent-child relationships
// - Remove helpers for delete operations
// ============================================================================

import type { QueryClient } from '@tanstack/react-query';
import {
  agentKeys,
  agentMessageKeys,
  agentPersonaKeys,
  agentPlanKeys,
  agentPromptKeys,
  agentResourceChunkKeys,
  agentResourceKeys,
  agentTaskKeys,
  agentThreadKeys,
  platformAgentKeys,
  platformAgentEventKeys,
  platformAgentMessageKeys,
  platformAgentPersonaKeys,
  platformAgentPlanKeys,
  platformAgentPromptKeys,
  platformAgentResourceChunkKeys,
  platformAgentResourceKeys,
  platformAgentRunKeys,
  platformAgentRunWorkspaceKeys,
  platformAgentTaskKeys,
  platformAgentThreadKeys,
} from './query-keys';
/**
// ============================================================================
// Invalidation Helpers
// ============================================================================

 * Type-safe query invalidation helpers
 * 
 * @example
 * ```ts
 * // Invalidate all user queries
 * invalidate.user.all(queryClient);
 * 
 * // Invalidate user lists
 * invalidate.user.lists(queryClient);
 * 
 * // Invalidate specific user
 * invalidate.user.detail(queryClient, userId);
 * ```
 */
export const invalidate = {
  /** Invalidate agent queries */ agent: {
    /** Invalidate all agent queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentKeys.all,
      }),
    /** Invalidate agent list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentKeys.lists(),
      }),
    /** Invalidate a specific agent */ detail: (queryClient: QueryClient, id: string | number) =>
      queryClient.invalidateQueries({
        queryKey: agentKeys.detail(id),
      }),
  },
  /** Invalidate agentMessage queries */ agentMessage: {
    /** Invalidate all agentMessage queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentMessageKeys.all,
      }),
    /** Invalidate agentMessage list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentMessageKeys.lists(),
      }),
    /** Invalidate a specific agentMessage */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: agentMessageKeys.detail(id),
      }),
  },
  /** Invalidate agentPersona queries */ agentPersona: {
    /** Invalidate all agentPersona queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentPersonaKeys.all,
      }),
    /** Invalidate agentPersona list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentPersonaKeys.lists(),
      }),
    /** Invalidate a specific agentPersona */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: agentPersonaKeys.detail(id),
      }),
  },
  /** Invalidate agentPlan queries */ agentPlan: {
    /** Invalidate all agentPlan queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentPlanKeys.all,
      }),
    /** Invalidate agentPlan list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentPlanKeys.lists(),
      }),
    /** Invalidate a specific agentPlan */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: agentPlanKeys.detail(id),
      }),
  },
  /** Invalidate agentPrompt queries */ agentPrompt: {
    /** Invalidate all agentPrompt queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentPromptKeys.all,
      }),
    /** Invalidate agentPrompt list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentPromptKeys.lists(),
      }),
    /** Invalidate a specific agentPrompt */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: agentPromptKeys.detail(id),
      }),
  },
  /** Invalidate agentResourceChunk queries */ agentResourceChunk: {
    /** Invalidate all agentResourceChunk queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentResourceChunkKeys.all,
      }),
    /** Invalidate agentResourceChunk list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentResourceChunkKeys.lists(),
      }),
    /** Invalidate a specific agentResourceChunk */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: agentResourceChunkKeys.detail(id),
      }),
  },
  /** Invalidate agentResource queries */ agentResource: {
    /** Invalidate all agentResource queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentResourceKeys.all,
      }),
    /** Invalidate agentResource list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentResourceKeys.lists(),
      }),
    /** Invalidate a specific agentResource */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: agentResourceKeys.detail(id),
      }),
  },
  /** Invalidate agentTask queries */ agentTask: {
    /** Invalidate all agentTask queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentTaskKeys.all,
      }),
    /** Invalidate agentTask list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentTaskKeys.lists(),
      }),
    /** Invalidate a specific agentTask */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: agentTaskKeys.detail(id),
      }),
  },
  /** Invalidate agentThread queries */ agentThread: {
    /** Invalidate all agentThread queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentThreadKeys.all,
      }),
    /** Invalidate agentThread list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: agentThreadKeys.lists(),
      }),
    /** Invalidate a specific agentThread */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: agentThreadKeys.detail(id),
      }),
  },
  /** Invalidate platformAgent queries */ platformAgent: {
    /** Invalidate all platformAgent queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentKeys.all,
      }),
    /** Invalidate platformAgent list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentKeys.lists(),
      }),
    /** Invalidate a specific platformAgent */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentEvent queries */ platformAgentEvent: {
    /** Invalidate all platformAgentEvent queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentEventKeys.all,
      }),
    /** Invalidate platformAgentEvent list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentEventKeys.lists(),
      }),
    /** Invalidate a specific platformAgentEvent */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentEventKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentMessage queries */ platformAgentMessage: {
    /** Invalidate all platformAgentMessage queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentMessageKeys.all,
      }),
    /** Invalidate platformAgentMessage list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentMessageKeys.lists(),
      }),
    /** Invalidate a specific platformAgentMessage */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentMessageKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentPersona queries */ platformAgentPersona: {
    /** Invalidate all platformAgentPersona queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentPersonaKeys.all,
      }),
    /** Invalidate platformAgentPersona list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentPersonaKeys.lists(),
      }),
    /** Invalidate a specific platformAgentPersona */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentPersonaKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentPlan queries */ platformAgentPlan: {
    /** Invalidate all platformAgentPlan queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentPlanKeys.all,
      }),
    /** Invalidate platformAgentPlan list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentPlanKeys.lists(),
      }),
    /** Invalidate a specific platformAgentPlan */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentPlanKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentPrompt queries */ platformAgentPrompt: {
    /** Invalidate all platformAgentPrompt queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentPromptKeys.all,
      }),
    /** Invalidate platformAgentPrompt list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentPromptKeys.lists(),
      }),
    /** Invalidate a specific platformAgentPrompt */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentPromptKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentResourceChunk queries */ platformAgentResourceChunk: {
    /** Invalidate all platformAgentResourceChunk queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentResourceChunkKeys.all,
      }),
    /** Invalidate platformAgentResourceChunk list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentResourceChunkKeys.lists(),
      }),
    /** Invalidate a specific platformAgentResourceChunk */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentResourceChunkKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentResource queries */ platformAgentResource: {
    /** Invalidate all platformAgentResource queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentResourceKeys.all,
      }),
    /** Invalidate platformAgentResource list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentResourceKeys.lists(),
      }),
    /** Invalidate a specific platformAgentResource */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentResourceKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentRun queries */ platformAgentRun: {
    /** Invalidate all platformAgentRun queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentRunKeys.all,
      }),
    /** Invalidate platformAgentRun list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentRunKeys.lists(),
      }),
    /** Invalidate a specific platformAgentRun */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentRunKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentRunWorkspace queries */ platformAgentRunWorkspace: {
    /** Invalidate all platformAgentRunWorkspace queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentRunWorkspaceKeys.all,
      }),
    /** Invalidate platformAgentRunWorkspace list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentRunWorkspaceKeys.lists(),
      }),
    /** Invalidate a specific platformAgentRunWorkspace */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentRunWorkspaceKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentTask queries */ platformAgentTask: {
    /** Invalidate all platformAgentTask queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentTaskKeys.all,
      }),
    /** Invalidate platformAgentTask list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentTaskKeys.lists(),
      }),
    /** Invalidate a specific platformAgentTask */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentTaskKeys.detail(id),
      }),
  },
  /** Invalidate platformAgentThread queries */ platformAgentThread: {
    /** Invalidate all platformAgentThread queries */ all: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentThreadKeys.all,
      }),
    /** Invalidate platformAgentThread list queries */ lists: (queryClient: QueryClient) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentThreadKeys.lists(),
      }),
    /** Invalidate a specific platformAgentThread */ detail: (
      queryClient: QueryClient,
      id: string | number
    ) =>
      queryClient.invalidateQueries({
        queryKey: platformAgentThreadKeys.detail(id),
      }),
  },
} as const;
/**

// ============================================================================
// Remove Helpers (for delete operations)
// ============================================================================

 * Remove queries from cache (for delete operations)
 * 
 * Use these when an entity is deleted to remove it from cache
 * instead of just invalidating (which would trigger a refetch).
 */
export const remove = {
  /** Remove agent from cache */ agent: (queryClient: QueryClient, id: string | number) => {
    queryClient.removeQueries({
      queryKey: agentKeys.detail(id),
    });
  },
  /** Remove agentMessage from cache */ agentMessage: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: agentMessageKeys.detail(id),
    });
  },
  /** Remove agentPersona from cache */ agentPersona: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: agentPersonaKeys.detail(id),
    });
  },
  /** Remove agentPlan from cache */ agentPlan: (queryClient: QueryClient, id: string | number) => {
    queryClient.removeQueries({
      queryKey: agentPlanKeys.detail(id),
    });
  },
  /** Remove agentPrompt from cache */ agentPrompt: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: agentPromptKeys.detail(id),
    });
  },
  /** Remove agentResourceChunk from cache */ agentResourceChunk: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: agentResourceChunkKeys.detail(id),
    });
  },
  /** Remove agentResource from cache */ agentResource: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: agentResourceKeys.detail(id),
    });
  },
  /** Remove agentTask from cache */ agentTask: (queryClient: QueryClient, id: string | number) => {
    queryClient.removeQueries({
      queryKey: agentTaskKeys.detail(id),
    });
  },
  /** Remove agentThread from cache */ agentThread: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: agentThreadKeys.detail(id),
    });
  },
  /** Remove platformAgent from cache */ platformAgent: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentKeys.detail(id),
    });
  },
  /** Remove platformAgentEvent from cache */ platformAgentEvent: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentEventKeys.detail(id),
    });
  },
  /** Remove platformAgentMessage from cache */ platformAgentMessage: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentMessageKeys.detail(id),
    });
  },
  /** Remove platformAgentPersona from cache */ platformAgentPersona: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentPersonaKeys.detail(id),
    });
  },
  /** Remove platformAgentPlan from cache */ platformAgentPlan: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentPlanKeys.detail(id),
    });
  },
  /** Remove platformAgentPrompt from cache */ platformAgentPrompt: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentPromptKeys.detail(id),
    });
  },
  /** Remove platformAgentResourceChunk from cache */ platformAgentResourceChunk: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentResourceChunkKeys.detail(id),
    });
  },
  /** Remove platformAgentResource from cache */ platformAgentResource: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentResourceKeys.detail(id),
    });
  },
  /** Remove platformAgentRun from cache */ platformAgentRun: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentRunKeys.detail(id),
    });
  },
  /** Remove platformAgentRunWorkspace from cache */ platformAgentRunWorkspace: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentRunWorkspaceKeys.detail(id),
    });
  },
  /** Remove platformAgentTask from cache */ platformAgentTask: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentTaskKeys.detail(id),
    });
  },
  /** Remove platformAgentThread from cache */ platformAgentThread: (
    queryClient: QueryClient,
    id: string | number
  ) => {
    queryClient.removeQueries({
      queryKey: platformAgentThreadKeys.detail(id),
    });
  },
} as const;
