/**
 * PlatformSecret model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PlatformSecret,
  PlatformSecretWithRelations,
  PlatformSecretSelect,
  PlatformSecretFilter,
  PlatformSecretOrderBy,
  CreatePlatformSecretInput,
  UpdatePlatformSecretInput,
  PlatformSecretPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PlatformSecretModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlatformSecretSelect>(
    args: FindManyArgs<S, PlatformSecretFilter, PlatformSecretOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformSecretSelect>
  ): QueryBuilder<{
    platformSecrets: ConnectionResult<InferSelectResult<PlatformSecretWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformSecret',
      'platformSecrets',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlatformSecretFilter',
      'PlatformSecretOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformSecret',
      fieldName: 'platformSecrets',
      document,
      variables,
    });
  }
  findFirst<S extends PlatformSecretSelect>(
    args: FindFirstArgs<S, PlatformSecretFilter, PlatformSecretOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformSecretSelect>
  ): QueryBuilder<{
    platformSecret: InferSelectResult<PlatformSecretWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlatformSecret',
      'platformSecrets',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlatformSecretFilter',
      'PlatformSecretOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformSecret',
      fieldName: 'platformSecret',
      document,
      variables,
      transform: (data: {
        platformSecrets?: {
          nodes?: InferSelectResult<PlatformSecretWithRelations, S>[];
        };
      }) => ({
        platformSecret: data.platformSecrets?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlatformSecretSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlatformSecretSelect>
  ): QueryBuilder<{
    platformSecret: InferSelectResult<PlatformSecretWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformSecret',
      'platformSecrets',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlatformSecretFilter',
      'PlatformSecretOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformSecret',
      fieldName: 'platformSecret',
      document,
      variables,
      transform: (data: {
        platformSecrets?: {
          nodes?: InferSelectResult<PlatformSecretWithRelations, S>[];
        };
      }) => ({
        platformSecret: data.platformSecrets?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlatformSecretSelect>(
    args: CreateArgs<S, CreatePlatformSecretInput['platformSecret']> & {
      select: S;
    } & StrictSelect<S, PlatformSecretSelect>
  ): QueryBuilder<{
    createPlatformSecret: {
      platformSecret: InferSelectResult<PlatformSecretWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlatformSecret',
      'createPlatformSecret',
      'platformSecret',
      args.select,
      args.data,
      'CreatePlatformSecretInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformSecret',
      fieldName: 'createPlatformSecret',
      document,
      variables,
    });
  }
}
