/**
 * GraphQL SDK
 * @generated by @constructive-io/graphql-codegen
 *
 * Tables: OrgGetManagersRecord, OrgGetSubordinatesRecord, AppPermission, OrgPermission, AppLimitCreditRedemption, AppLimitCreditCodeItem, AppLimitCredit, OrgMember, AppPermissionDefault, AppAdminGrant, AppOwnerGrant, OrgPermissionDefault, AppMembershipDefault, OrgAdminGrant, OrgMembershipDefault, OrgOwnerGrant, AppLimitCapsDefault, OrgLimitCapsDefault, AppLimitCap, OrgLimitCap, OrgChartEdge, AppLimitDefault, OrgLimitDefault, OrgLimitCredit, AppLimitCreditCode, AppLimitWarning, OrgChartEdgeGrant, AppClaimedInvite, OrgLimitWarning, MembershipType, AppGrant, OrgClaimedInvite, OrgGrant, OrgMembershipSetting, AppLimitEvent, OrgLimitEvent, AppMembership, OrgMembership, OrgMemberProfile, AppInvite, AppLimit, OrgLimitAggregate, OrgLimit, OrgInvite
 *
 * Usage:
 *
 * 1. Configure the client:
 * ```ts
 * import { configure } from './generated';
 *
 * configure({
 *   endpoint: 'https://api.example.com/graphql',
 *   headers: { Authorization: 'Bearer <token>' },
 * });
 * ```
 *
 * 2. Use the hooks:
 * ```tsx
 * import { useCarsQuery, useCreateCarMutation } from './generated';
 *
 * function MyComponent() {
 *   const { data, isLoading } = useCarsQuery({
 *     selection: { fields: { id: true }, first: 10 },
 *   });
 *   const { mutate } = useCreateCarMutation({
 *     selection: { fields: { id: true } },
 *   });
 *   // ...
 * }
 * ```
 */
export * from './client';
export * from './query-keys';
export * from './mutation-keys';
export * from './invalidation';
export * from './queries';
export * from './mutations';
