/**
 * Barrel file generators for ORM client (Babel AST-based)
 *
 * Generates index.ts files that re-export all models and operations.
 */
import type { CleanTable } from '../../../types/schema';
import * as t from '@babel/types';
import { generateCode } from '../babel-ast';
import { getTableNames, lcFirst, getGeneratedFileHeader } from '../utils';

export interface GeneratedBarrelFile {
  fileName: string;
  content: string;
}

/**
 * Generate the models/index.ts barrel file
 */
export function generateModelsBarrel(tables: CleanTable[]): GeneratedBarrelFile {
  const statements: t.Statement[] = [];

  // Export all model classes (Select types are now in input-types.ts)
  for (const table of tables) {
    const { typeName } = getTableNames(table);
    const modelName = `${typeName}Model`;
    // Use same naming logic as model-generator to avoid "index.ts" clash with barrel file
    const baseFileName = lcFirst(typeName);
    const moduleFileName = baseFileName === 'index' ? `${baseFileName}Model` : baseFileName;

    // Create: export { ModelName } from './moduleName';
    const exportDecl = t.exportNamedDeclaration(
      null,
      [t.exportSpecifier(t.identifier(modelName), t.identifier(modelName))],
      t.stringLiteral(`./${moduleFileName}`)
    );
    statements.push(exportDecl);
  }

  const header = getGeneratedFileHeader('Models barrel export');
  const code = generateCode(statements);

  return {
    fileName: 'models/index.ts',
    content: header + '\n' + code,
  };
}

/**
 * Generate the types.ts file that re-exports all types
 */
export function generateTypesBarrel(_useSharedTypes: boolean): GeneratedBarrelFile {
  // Always re-export from input-types since that's where all types are generated
  const content = `/**
 * Types re-export
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

// Re-export all types from input-types
export * from './input-types';
`;

  return {
    fileName: 'types.ts',
    content,
  };
}
