/**
 * InfraGetAllRecord model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  InfraGetAllRecord,
  InfraGetAllRecordWithRelations,
  InfraGetAllRecordSelect,
  InfraGetAllRecordFilter,
  InfraGetAllRecordsOrderBy,
  CreateInfraGetAllRecordInput,
  UpdateInfraGetAllRecordInput,
  InfraGetAllRecordPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class InfraGetAllRecordModel {
  constructor(private client: OrmClient) {}
  findMany<S extends InfraGetAllRecordSelect>(
    args: FindManyArgs<S, InfraGetAllRecordFilter, InfraGetAllRecordsOrderBy> & {
      select: S;
    } & StrictSelect<S, InfraGetAllRecordSelect>
  ): QueryBuilder<{
    infraGetAll: ConnectionResult<InferSelectResult<InfraGetAllRecordWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'InfraGetAllRecord',
      'infraGetAll',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'InfraGetAllRecordFilter',
      'InfraGetAllRecordsOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'InfraGetAllRecord',
      fieldName: 'infraGetAll',
      document,
      variables,
    });
  }
  findFirst<S extends InfraGetAllRecordSelect>(
    args: FindFirstArgs<S, InfraGetAllRecordFilter, InfraGetAllRecordsOrderBy> & {
      select: S;
    } & StrictSelect<S, InfraGetAllRecordSelect>
  ): QueryBuilder<{
    infraGetAllRecord: InferSelectResult<InfraGetAllRecordWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'InfraGetAllRecord',
      'infraGetAll',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'InfraGetAllRecordFilter',
      'InfraGetAllRecordsOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'InfraGetAllRecord',
      fieldName: 'infraGetAllRecord',
      document,
      variables,
      transform: (data: {
        infraGetAll?: {
          nodes?: InferSelectResult<InfraGetAllRecordWithRelations, S>[];
        };
      }) => ({
        infraGetAllRecord: data.infraGetAll?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends InfraGetAllRecordSelect>(
    args: CreateArgs<S, CreateInfraGetAllRecordInput['infraGetAllRecord']> & {
      select: S;
    } & StrictSelect<S, InfraGetAllRecordSelect>
  ): QueryBuilder<{
    createInfraGetAllRecord: {
      infraGetAllRecord: InferSelectResult<InfraGetAllRecordWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'InfraGetAllRecord',
      'createInfraGetAllRecord',
      'infraGetAllRecord',
      args.select,
      args.data,
      'CreateInfraGetAllRecordInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'InfraGetAllRecord',
      fieldName: 'createInfraGetAllRecord',
      document,
      variables,
    });
  }
}
