/**
 * DatabaseSetting model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  DatabaseSetting,
  DatabaseSettingWithRelations,
  DatabaseSettingSelect,
  DatabaseSettingFilter,
  DatabaseSettingOrderBy,
  CreateDatabaseSettingInput,
  UpdateDatabaseSettingInput,
  DatabaseSettingPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class DatabaseSettingModel {
  constructor(private client: OrmClient) {}
  findMany<S extends DatabaseSettingSelect>(
    args: FindManyArgs<S, DatabaseSettingFilter, DatabaseSettingOrderBy> & {
      select: S;
    } & StrictSelect<S, DatabaseSettingSelect>
  ): QueryBuilder<{
    databaseSettings: ConnectionResult<InferSelectResult<DatabaseSettingWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'DatabaseSetting',
      'databaseSettings',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'DatabaseSettingFilter',
      'DatabaseSettingOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'DatabaseSetting',
      fieldName: 'databaseSettings',
      document,
      variables,
    });
  }
  findFirst<S extends DatabaseSettingSelect>(
    args: FindFirstArgs<S, DatabaseSettingFilter> & {
      select: S;
    } & StrictSelect<S, DatabaseSettingSelect>
  ): QueryBuilder<{
    databaseSettings: {
      nodes: InferSelectResult<DatabaseSettingWithRelations, S>[];
    };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'DatabaseSetting',
      'databaseSettings',
      args.select,
      {
        where: args?.where,
      },
      'DatabaseSettingFilter',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'DatabaseSetting',
      fieldName: 'databaseSettings',
      document,
      variables,
    });
  }
  findOne<S extends DatabaseSettingSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, DatabaseSettingSelect>
  ): QueryBuilder<{
    databaseSetting: InferSelectResult<DatabaseSettingWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'DatabaseSetting',
      'databaseSettings',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'DatabaseSettingFilter',
      'DatabaseSettingOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'DatabaseSetting',
      fieldName: 'databaseSetting',
      document,
      variables,
      transform: (data: {
        databaseSettings?: {
          nodes?: InferSelectResult<DatabaseSettingWithRelations, S>[];
        };
      }) => ({
        databaseSetting: data.databaseSettings?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends DatabaseSettingSelect>(
    args: CreateArgs<S, CreateDatabaseSettingInput['databaseSetting']> & {
      select: S;
    } & StrictSelect<S, DatabaseSettingSelect>
  ): QueryBuilder<{
    createDatabaseSetting: {
      databaseSetting: InferSelectResult<DatabaseSettingWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'DatabaseSetting',
      'createDatabaseSetting',
      'databaseSetting',
      args.select,
      args.data,
      'CreateDatabaseSettingInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'DatabaseSetting',
      fieldName: 'createDatabaseSetting',
      document,
      variables,
    });
  }
  update<S extends DatabaseSettingSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      DatabaseSettingPatch
    > & {
      select: S;
    } & StrictSelect<S, DatabaseSettingSelect>
  ): QueryBuilder<{
    updateDatabaseSetting: {
      databaseSetting: InferSelectResult<DatabaseSettingWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'DatabaseSetting',
      'updateDatabaseSetting',
      'databaseSetting',
      args.select,
      args.where.id,
      args.data,
      'UpdateDatabaseSettingInput',
      'id',
      'databaseSettingPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'DatabaseSetting',
      fieldName: 'updateDatabaseSetting',
      document,
      variables,
    });
  }
  delete<S extends DatabaseSettingSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, DatabaseSettingSelect>
  ): QueryBuilder<{
    deleteDatabaseSetting: {
      databaseSetting: InferSelectResult<DatabaseSettingWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'DatabaseSetting',
      'deleteDatabaseSetting',
      'databaseSetting',
      {
        id: args.where.id,
      },
      'DeleteDatabaseSettingInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'DatabaseSetting',
      fieldName: 'deleteDatabaseSetting',
      document,
      variables,
    });
  }
}
