/**
 * EmbeddingChunk model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  EmbeddingChunk,
  EmbeddingChunkWithRelations,
  EmbeddingChunkSelect,
  EmbeddingChunkFilter,
  EmbeddingChunkOrderBy,
  CreateEmbeddingChunkInput,
  UpdateEmbeddingChunkInput,
  EmbeddingChunkPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class EmbeddingChunkModel {
  constructor(private client: OrmClient) {}
  findMany<S extends EmbeddingChunkSelect>(
    args: FindManyArgs<S, EmbeddingChunkFilter, never, EmbeddingChunkOrderBy> & {
      select: S;
    } & StrictSelect<S, EmbeddingChunkSelect>
  ): QueryBuilder<{
    embeddingChunks: ConnectionResult<InferSelectResult<EmbeddingChunkWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'EmbeddingChunk',
      'embeddingChunks',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'EmbeddingChunkFilter',
      'EmbeddingChunkOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'EmbeddingChunk',
      fieldName: 'embeddingChunks',
      document,
      variables,
    });
  }
  findFirst<S extends EmbeddingChunkSelect>(
    args: FindFirstArgs<S, EmbeddingChunkFilter> & {
      select: S;
    } & StrictSelect<S, EmbeddingChunkSelect>
  ): QueryBuilder<{
    embeddingChunks: {
      nodes: InferSelectResult<EmbeddingChunkWithRelations, S>[];
    };
  }> {
    const { document, variables } = buildFindFirstDocument(
      'EmbeddingChunk',
      'embeddingChunks',
      args.select,
      {
        where: args?.where,
      },
      'EmbeddingChunkFilter',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'EmbeddingChunk',
      fieldName: 'embeddingChunks',
      document,
      variables,
    });
  }
  findOne<S extends EmbeddingChunkSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, EmbeddingChunkSelect>
  ): QueryBuilder<{
    embeddingChunk: InferSelectResult<EmbeddingChunkWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'EmbeddingChunk',
      'embeddingChunks',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'EmbeddingChunkFilter',
      'EmbeddingChunkOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'EmbeddingChunk',
      fieldName: 'embeddingChunk',
      document,
      variables,
      transform: (data: {
        embeddingChunks?: {
          nodes?: InferSelectResult<EmbeddingChunkWithRelations, S>[];
        };
      }) => ({
        embeddingChunk: data.embeddingChunks?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends EmbeddingChunkSelect>(
    args: CreateArgs<S, CreateEmbeddingChunkInput['embeddingChunk']> & {
      select: S;
    } & StrictSelect<S, EmbeddingChunkSelect>
  ): QueryBuilder<{
    createEmbeddingChunk: {
      embeddingChunk: InferSelectResult<EmbeddingChunkWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'EmbeddingChunk',
      'createEmbeddingChunk',
      'embeddingChunk',
      args.select,
      args.data,
      'CreateEmbeddingChunkInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'EmbeddingChunk',
      fieldName: 'createEmbeddingChunk',
      document,
      variables,
    });
  }
  update<S extends EmbeddingChunkSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      EmbeddingChunkPatch
    > & {
      select: S;
    } & StrictSelect<S, EmbeddingChunkSelect>
  ): QueryBuilder<{
    updateEmbeddingChunk: {
      embeddingChunk: InferSelectResult<EmbeddingChunkWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'EmbeddingChunk',
      'updateEmbeddingChunk',
      'embeddingChunk',
      args.select,
      args.where.id,
      args.data,
      'UpdateEmbeddingChunkInput',
      'id',
      'embeddingChunkPatch',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'EmbeddingChunk',
      fieldName: 'updateEmbeddingChunk',
      document,
      variables,
    });
  }
  delete<S extends EmbeddingChunkSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, EmbeddingChunkSelect>
  ): QueryBuilder<{
    deleteEmbeddingChunk: {
      embeddingChunk: InferSelectResult<EmbeddingChunkWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'EmbeddingChunk',
      'deleteEmbeddingChunk',
      'embeddingChunk',
      args.where.id,
      'DeleteEmbeddingChunkInput',
      'id',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'EmbeddingChunk',
      fieldName: 'deleteEmbeddingChunk',
      document,
      variables,
    });
  }
}
