/**
 * PlanLimit model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PlanLimit,
  PlanLimitWithRelations,
  PlanLimitSelect,
  PlanLimitFilter,
  PlanLimitOrderBy,
  CreatePlanLimitInput,
  UpdatePlanLimitInput,
  PlanLimitPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PlanLimitModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlanLimitSelect>(
    args: FindManyArgs<S, PlanLimitFilter, PlanLimitOrderBy> & {
      select: S;
    } & StrictSelect<S, PlanLimitSelect>
  ): QueryBuilder<{
    planLimits: ConnectionResult<InferSelectResult<PlanLimitWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlanLimit',
      'planLimits',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlanLimitFilter',
      'PlanLimitOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlanLimit',
      fieldName: 'planLimits',
      document,
      variables,
    });
  }
  findFirst<S extends PlanLimitSelect>(
    args: FindFirstArgs<S, PlanLimitFilter, PlanLimitOrderBy> & {
      select: S;
    } & StrictSelect<S, PlanLimitSelect>
  ): QueryBuilder<{
    planLimit: InferSelectResult<PlanLimitWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlanLimit',
      'planLimits',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlanLimitFilter',
      'PlanLimitOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlanLimit',
      fieldName: 'planLimit',
      document,
      variables,
      transform: (data: {
        planLimits?: {
          nodes?: InferSelectResult<PlanLimitWithRelations, S>[];
        };
      }) => ({
        planLimit: data.planLimits?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlanLimitSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlanLimitSelect>
  ): QueryBuilder<{
    planLimit: InferSelectResult<PlanLimitWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlanLimit',
      'planLimits',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlanLimitFilter',
      'PlanLimitOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlanLimit',
      fieldName: 'planLimit',
      document,
      variables,
      transform: (data: {
        planLimits?: {
          nodes?: InferSelectResult<PlanLimitWithRelations, S>[];
        };
      }) => ({
        planLimit: data.planLimits?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlanLimitSelect>(
    args: CreateArgs<S, CreatePlanLimitInput['planLimit']> & {
      select: S;
    } & StrictSelect<S, PlanLimitSelect>
  ): QueryBuilder<{
    createPlanLimit: {
      planLimit: InferSelectResult<PlanLimitWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlanLimit',
      'createPlanLimit',
      'planLimit',
      args.select,
      args.data,
      'CreatePlanLimitInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlanLimit',
      fieldName: 'createPlanLimit',
      document,
      variables,
    });
  }
  update<S extends PlanLimitSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      PlanLimitPatch
    > & {
      select: S;
    } & StrictSelect<S, PlanLimitSelect>
  ): QueryBuilder<{
    updatePlanLimit: {
      planLimit: InferSelectResult<PlanLimitWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'PlanLimit',
      'updatePlanLimit',
      'planLimit',
      args.select,
      args.where.id,
      args.data,
      'UpdatePlanLimitInput',
      'id',
      'planLimitPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlanLimit',
      fieldName: 'updatePlanLimit',
      document,
      variables,
    });
  }
  delete<S extends PlanLimitSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, PlanLimitSelect>
  ): QueryBuilder<{
    deletePlanLimit: {
      planLimit: InferSelectResult<PlanLimitWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'PlanLimit',
      'deletePlanLimit',
      'planLimit',
      {
        id: args.where.id,
      },
      'DeletePlanLimitInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlanLimit',
      fieldName: 'deletePlanLimit',
      document,
      variables,
    });
  }
}
