import path from 'node:path';

import { makeSchema } from 'graphile-build';
import { makePgService, MinimalPreset } from 'graphile-settings';
import {
  lexicographicSortSchema,
  parse,
  printSchema,
  type ExecutionResult
} from 'graphql';
import type { Pool } from 'pg';
import { getConnections, PgTestClient } from 'pgsql-test';

const SCHEMA = 'scoped_equivalence';

// graphile-schema consumes these through graphile-settings in production; the
// test resolves that package's exact dependency instances without adding
// test-only runtime dependencies to graphile-schema.
const graphileSettingsDirectory = path.dirname(require.resolve('graphile-settings'));
const { execute } = require(require.resolve('grafast', {
  paths: [graphileSettingsDirectory]
}));
const { withPgClientFromPgService } = require(require.resolve('graphile-build-pg', {
  paths: [graphileSettingsDirectory]
}));

let pg: PgTestClient;
let pool: Pool;
let teardown: () => Promise<void>;

beforeAll(async () => {
  const connections = await getConnections({}, []);
  ({ pg, teardown } = connections);
  pool = connections.manager.getPool(pg.config);

  await pg.query(`
    CREATE SCHEMA ${SCHEMA};
    CREATE TYPE ${SCHEMA}.item_state AS ENUM ('draft', 'published');

    CREATE TABLE ${SCHEMA}.organizations (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name text NOT NULL UNIQUE
    );

    CREATE TABLE ${SCHEMA}.items (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      organization_id bigint NOT NULL REFERENCES ${SCHEMA}.organizations(id),
      state ${SCHEMA}.item_state NOT NULL DEFAULT 'draft',
      title text NOT NULL
    );

    CREATE FUNCTION ${SCHEMA}.item_title(item ${SCHEMA}.items)
    RETURNS text
    LANGUAGE sql
    IMMUTABLE
    AS 'SELECT item.title';

    CREATE FUNCTION ${SCHEMA}.tenant_token()
    RETURNS text
    LANGUAGE sql
    STABLE
    AS 'SELECT ''scoped-equivalence-token''::text';

    COMMENT ON TABLE ${SCHEMA}.items IS 'Scoped-introspection equivalence canary';
  `);
});

beforeEach(async () => {
  await pg.beforeEach();
});

afterEach(async () => {
  await pg.afterEach();
});

afterAll(async () => {
  await teardown();
});

async function build(
  mode: 'stock' | 'scoped-required',
  schemas = [SCHEMA],
  scopedCatalogTypes?: 'all' | 'dependency-closure'
) {
  const pgService = makePgService({
    pool,
    schemas,
    introspectionMode: mode,
    ...(scopedCatalogTypes === undefined
      ? {}
      : { introspectionScopedCatalogTypes: scopedCatalogTypes })
  });
  const built = await makeSchema({
    extends: [MinimalPreset],
    pgServices: [pgService]
  });
  return { ...built, pgService };
}

describe('scoped introspection schema equivalence', () => {
  it('builds byte-equivalent SDL and executes the same token in every arm', async () => {
    const stockBuild = await build('stock');
    const scopedAllBuild = await build('scoped-required');
    const scopedClosureBuild = await build(
      'scoped-required',
      [SCHEMA],
      'dependency-closure'
    );
    const stock = printSchema(lexicographicSortSchema(stockBuild.schema));
    const scopedAll = printSchema(lexicographicSortSchema(scopedAllBuild.schema));
    const scopedClosure = printSchema(lexicographicSortSchema(
      scopedClosureBuild.schema
    ));

    expect(scopedAll).toBe(stock);
    expect(scopedClosure).toBe(stock);
    expect(scopedClosure).toContain('type Item');
    expect(scopedClosure).toContain('enum ItemState');

    for (const built of [stockBuild, scopedAllBuild, scopedClosureBuild]) {
      const withPgClientKey = built.pgService.withPgClientKey ?? 'withPgClient';
      const result = await execute({
        schema: built.schema,
        document: parse('{ tenantToken }'),
        contextValue: {
          pgSettings: {},
          [withPgClientKey]: withPgClientFromPgService.bind(
            null,
            built.pgService
          )
        },
        resolvedPreset: built.resolvedPreset
      }) as ExecutionResult<{ tenantToken?: unknown }>;
      if (Symbol.asyncIterator in result) {
        throw new Error('tenant token canary unexpectedly returned a stream');
      }
      expect(result.errors).toBeUndefined();
      expect(result.data).toEqual({ tenantToken: 'scoped-equivalence-token' });
    }
  });

  it.each([undefined, 'dependency-closure'] as const)(
    'fails closed when a required schema is absent (catalog types: %s)',
    async (scopedCatalogTypes) => {
      await expect(build(
        'scoped-required',
        ['missing_required_schema'],
        scopedCatalogTypes
      ))
      .rejects.toThrow(
        'did not find required schema(s): missing_required_schema'
      );
    }
  );
});
