/**
 * CLI command for query orgIsManagerOf
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer } from 'inquirerer';
import { getClient } from '../executor';
import type { OrgIsManagerOfVariables } from '../../orm/query';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  try {
    if (argv.help || argv.h) {
      console.log('org-is-manager-of - orgIsManagerOf\n\nUsage: org-is-manager-of [OPTIONS]\n');
      process.exit(0);
    }
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'managerId',
        message: 'managerId',
      },
      {
        type: 'text',
        name: 'maxDepth',
        message: 'maxDepth (number)',
      },
      {
        type: 'text',
        name: 'targetEntityId',
        message: 'targetEntityId',
      },
      {
        type: 'text',
        name: 'userId',
        message: 'userId',
      },
    ]);
    const client = getClient();
    const result = await client.query
      .orgIsManagerOf(answers as unknown as OrgIsManagerOfVariables)
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed: orgIsManagerOf');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
};
