/**
 * Catalog of known event types with per-type configuration for aggregation, retention, and level participation
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appEventTypeKeys } from '../query-keys';
import type { AppEventTypeSelect, AppEventTypeWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { AppEventTypeSelect, AppEventTypeWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appEventTypeQueryKey = appEventTypeKeys.detail;
/**
 * Catalog of known event types with per-type configuration for aggregation, retention, and level participation
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppEventTypeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppEventTypeQuery<
  S extends AppEventTypeSelect,
  TData = {
    appEventType: InferSelectResult<AppEventTypeWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppEventTypeSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appEventType: InferSelectResult<AppEventTypeWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppEventTypeQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppEventTypeSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppEventTypeSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appEventTypeKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appEventType.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Catalog of known event types with per-type configuration for aggregation, retention, and level participation
 *
 * @example
 * ```ts
 * const data = await fetchAppEventTypeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppEventTypeQuery<S extends AppEventTypeSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppEventTypeSelect>;
}): Promise<{
  appEventType: InferSelectResult<AppEventTypeWithRelations, S> | null;
}>;
export async function fetchAppEventTypeQuery(params: {
  id: string;
  selection: SelectionConfig<AppEventTypeSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<AppEventTypeSelect>(params.selection);
  return getClient()
    .appEventType.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Catalog of known event types with per-type configuration for aggregation, retention, and level participation
 *
 * @example
 * ```ts
 * await prefetchAppEventTypeQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppEventTypeQuery<S extends AppEventTypeSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppEventTypeSelect>;
  }
): Promise<void>;
export async function prefetchAppEventTypeQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppEventTypeSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppEventTypeSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appEventTypeKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appEventType.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
