/**
 * Custom query operations
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OperationTypeNode } from 'graphql';
import { OrmClient } from '../client';
import { QueryBuilder, buildCustomDocument } from '../query-builder';
import type { InferSelectResult, DeepExact } from '../select-types';
import type { Api, ApiSelect } from '../input-types';

export interface ApiByDatabaseIdAndNameVariables {
  databaseId: string;
  name: string;
}

export function createQueryOperations(client: OrmClient) {
  return {
    apiByDatabaseIdAndName: <const S extends ApiSelect>(
      args: ApiByDatabaseIdAndNameVariables,
      options?: {
        select?: DeepExact<S, ApiSelect>;
      },
    ) =>
      new QueryBuilder<{
        apiByDatabaseIdAndName: InferSelectResult<Api, S>;
      }>({
        client,
        operation: 'query',
        operationName: 'ApiByDatabaseIdAndName',
        fieldName: 'apiByDatabaseIdAndName',
        ...buildCustomDocument(
          OperationTypeNode.QUERY,
          'ApiByDatabaseIdAndName',
          'apiByDatabaseIdAndName',
          options?.select,
          args,
          [
            {
              name: 'databaseId',
              type: 'UUID!',
            },
            {
              name: 'name',
              type: 'String!',
            },
          ],
        ),
      }),
  };
}
