/**
 * SiteWebConfig model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  SiteWebConfig,
  SiteWebConfigWithRelations,
  SiteWebConfigSelect,
  SiteWebConfigFilter,
  SiteWebConfigOrderBy,
  CreateSiteWebConfigInput,
  UpdateSiteWebConfigInput,
  SiteWebConfigPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class SiteWebConfigModel {
  constructor(private client: OrmClient) {}
  findMany<S extends SiteWebConfigSelect>(
    args: FindManyArgs<S, SiteWebConfigFilter, SiteWebConfigOrderBy> & {
      select: S;
    } & StrictSelect<S, SiteWebConfigSelect>
  ): QueryBuilder<{
    siteWebConfigs: ConnectionResult<InferSelectResult<SiteWebConfigWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'SiteWebConfig',
      'siteWebConfigs',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'SiteWebConfigFilter',
      'SiteWebConfigOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'SiteWebConfig',
      fieldName: 'siteWebConfigs',
      document,
      variables,
    });
  }
  findFirst<S extends SiteWebConfigSelect>(
    args: FindFirstArgs<S, SiteWebConfigFilter, SiteWebConfigOrderBy> & {
      select: S;
    } & StrictSelect<S, SiteWebConfigSelect>
  ): QueryBuilder<{
    siteWebConfig: InferSelectResult<SiteWebConfigWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'SiteWebConfig',
      'siteWebConfigs',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'SiteWebConfigFilter',
      'SiteWebConfigOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'SiteWebConfig',
      fieldName: 'siteWebConfig',
      document,
      variables,
      transform: (data: {
        siteWebConfigs?: {
          nodes?: InferSelectResult<SiteWebConfigWithRelations, S>[];
        };
      }) => ({
        siteWebConfig: data.siteWebConfigs?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends SiteWebConfigSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, SiteWebConfigSelect>
  ): QueryBuilder<{
    siteWebConfig: InferSelectResult<SiteWebConfigWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'SiteWebConfig',
      'siteWebConfigs',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'SiteWebConfigFilter',
      'SiteWebConfigOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'SiteWebConfig',
      fieldName: 'siteWebConfig',
      document,
      variables,
      transform: (data: {
        siteWebConfigs?: {
          nodes?: InferSelectResult<SiteWebConfigWithRelations, S>[];
        };
      }) => ({
        siteWebConfig: data.siteWebConfigs?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends SiteWebConfigSelect>(
    args: CreateArgs<S, CreateSiteWebConfigInput['siteWebConfig']> & {
      select: S;
    } & StrictSelect<S, SiteWebConfigSelect>
  ): QueryBuilder<{
    createSiteWebConfig: {
      siteWebConfig: InferSelectResult<SiteWebConfigWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'SiteWebConfig',
      'createSiteWebConfig',
      'siteWebConfig',
      args.select,
      args.data,
      'CreateSiteWebConfigInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'SiteWebConfig',
      fieldName: 'createSiteWebConfig',
      document,
      variables,
    });
  }
  update<S extends SiteWebConfigSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      SiteWebConfigPatch
    > & {
      select: S;
    } & StrictSelect<S, SiteWebConfigSelect>
  ): QueryBuilder<{
    updateSiteWebConfig: {
      siteWebConfig: InferSelectResult<SiteWebConfigWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'SiteWebConfig',
      'updateSiteWebConfig',
      'siteWebConfig',
      args.select,
      args.where.id,
      args.data,
      'UpdateSiteWebConfigInput',
      'id',
      'siteWebConfigPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'SiteWebConfig',
      fieldName: 'updateSiteWebConfig',
      document,
      variables,
    });
  }
  delete<S extends SiteWebConfigSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, SiteWebConfigSelect>
  ): QueryBuilder<{
    deleteSiteWebConfig: {
      siteWebConfig: InferSelectResult<SiteWebConfigWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'SiteWebConfig',
      'deleteSiteWebConfig',
      'siteWebConfig',
      {
        id: args.where.id,
      },
      'DeleteSiteWebConfigInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'SiteWebConfig',
      fieldName: 'deleteSiteWebConfig',
      document,
      variables,
    });
  }
}
