/**
 * A tenant's configured account at an email provider: provider slug, endpoint coordinates, and the NAME of the secret holding its credentials (never the credential itself)
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { platformEmailProviderAccountKeys } from '../query-keys';
import type {
  PlatformEmailProviderAccountSelect,
  PlatformEmailProviderAccountWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  PlatformEmailProviderAccountSelect,
  PlatformEmailProviderAccountWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const platformEmailProviderAccountQueryKey = platformEmailProviderAccountKeys.detail;
/**
 * A tenant's configured account at an email provider: provider slug, endpoint coordinates, and the NAME of the secret holding its credentials (never the credential itself)
 *
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformEmailProviderAccountQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function usePlatformEmailProviderAccountQuery<
  S extends PlatformEmailProviderAccountSelect,
  TData = {
    platformEmailProviderAccount: InferSelectResult<
      PlatformEmailProviderAccountWithRelations,
      S
    > | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformEmailProviderAccountSelect>;
  } & Omit<
    UseQueryOptions<
      {
        platformEmailProviderAccount: InferSelectResult<
          PlatformEmailProviderAccountWithRelations,
          S
        > | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function usePlatformEmailProviderAccountQuery(
  params: {
    id: string;
    selection: SelectionConfig<PlatformEmailProviderAccountSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<PlatformEmailProviderAccountSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformEmailProviderAccountKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformEmailProviderAccount.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * A tenant's configured account at an email provider: provider slug, endpoint coordinates, and the NAME of the secret holding its credentials (never the credential itself)
 *
 * @example
 * ```ts
 * const data = await fetchPlatformEmailProviderAccountQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchPlatformEmailProviderAccountQuery<
  S extends PlatformEmailProviderAccountSelect,
>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformEmailProviderAccountSelect>;
}): Promise<{
  platformEmailProviderAccount: InferSelectResult<
    PlatformEmailProviderAccountWithRelations,
    S
  > | null;
}>;
export async function fetchPlatformEmailProviderAccountQuery(params: {
  id: string;
  selection: SelectionConfig<PlatformEmailProviderAccountSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<PlatformEmailProviderAccountSelect>(params.selection);
  return getClient()
    .platformEmailProviderAccount.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * A tenant's configured account at an email provider: provider slug, endpoint coordinates, and the NAME of the secret holding its credentials (never the credential itself)
 *
 * @example
 * ```ts
 * await prefetchPlatformEmailProviderAccountQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchPlatformEmailProviderAccountQuery<
  S extends PlatformEmailProviderAccountSelect,
>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, PlatformEmailProviderAccountSelect>;
  }
): Promise<void>;
export async function prefetchPlatformEmailProviderAccountQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<PlatformEmailProviderAccountSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<PlatformEmailProviderAccountSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformEmailProviderAccountKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .platformEmailProviderAccount.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
