/**
 * Theme (colors, fonts, design tokens) for a site surface
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from "@tanstack/react-query";
import type { UseQueryOptions, UseQueryResult, QueryClient } from "@tanstack/react-query";
import { getClient } from "../client";
import { buildSelectionArgs } from "../selection";
import type { SelectionConfig } from "../selection";
import { platformSiteThemeKeys } from "../query-keys";
import type { PlatformSiteThemeSelect, PlatformSiteThemeWithRelations } from "../../orm/input-types";
import type { InferSelectResult, HookStrictSelect } from "../../orm/select-types";
export type { PlatformSiteThemeSelect, PlatformSiteThemeWithRelations } from "../../orm/input-types";
/** Query key factory - re-exported from query-keys.ts */
export const platformSiteThemeQueryKey = platformSiteThemeKeys.detail;
/**
 * Theme (colors, fonts, design tokens) for a site surface
 * 
 * @example
 * ```tsx
 * const { data, isLoading } = usePlatformSiteThemeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function usePlatformSiteThemeQuery<S extends PlatformSiteThemeSelect, TData = {
  platformSiteTheme: InferSelectResult<PlatformSiteThemeWithRelations, S> | null;
}>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformSiteThemeSelect>;
} & Omit<UseQueryOptions<{
  platformSiteTheme: InferSelectResult<PlatformSiteThemeWithRelations, S> | null;
}, Error, TData>, "queryKey" | "queryFn">): UseQueryResult<TData>;
export function usePlatformSiteThemeQuery(params: {
  id: string;
  selection: SelectionConfig<PlatformSiteThemeSelect>;
} & Omit<UseQueryOptions<any, Error, any, any>, "queryKey" | "queryFn">) {
  const args = buildSelectionArgs<PlatformSiteThemeSelect>(params.selection);
  const {
    selection: _selection,
    ...queryOptions
  } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: platformSiteThemeKeys.detail(params.id),
    queryFn: () => getClient().platformSiteTheme.findOne({
      id: params.id,
      select: args.select
    }).unwrap(),
    ...queryOptions
  });
}
/**
 * Theme (colors, fonts, design tokens) for a site surface
 * 
 * @example
 * ```ts
 * const data = await fetchPlatformSiteThemeQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchPlatformSiteThemeQuery<S extends PlatformSiteThemeSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformSiteThemeSelect>;
}): Promise<{
  platformSiteTheme: InferSelectResult<PlatformSiteThemeWithRelations, S> | null;
}>;
export async function fetchPlatformSiteThemeQuery(params: {
  id: string;
  selection: SelectionConfig<PlatformSiteThemeSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<PlatformSiteThemeSelect>(params.selection);
  return getClient().platformSiteTheme.findOne({
    id: params.id,
    select: args.select
  }).unwrap();
}
/**
 * Theme (colors, fonts, design tokens) for a site surface
 * 
 * @example
 * ```ts
 * await prefetchPlatformSiteThemeQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchPlatformSiteThemeQuery<S extends PlatformSiteThemeSelect>(queryClient: QueryClient, params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, PlatformSiteThemeSelect>;
}): Promise<void>;
export async function prefetchPlatformSiteThemeQuery(queryClient: QueryClient, params: {
  id: string;
  selection: SelectionConfig<PlatformSiteThemeSelect>;
}): Promise<void> {
  const args = buildSelectionArgs<PlatformSiteThemeSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: platformSiteThemeKeys.detail(params.id),
    queryFn: () => getClient().platformSiteTheme.findOne({
      id: params.id,
      select: args.select
    }).unwrap()
  });
}
