/**
 * Barrel file generators for ORM client
 *
 * Generates index.ts files that re-export all models and operations.
 */
import type { CleanTable } from '../../../types/schema';
import {
  createProject,
  createSourceFile,
  getFormattedOutput,
  createFileHeader,
} from '../ts-ast';
import { getTableNames, lcFirst } from '../utils';

export interface GeneratedBarrelFile {
  fileName: string;
  content: string;
}

/**
 * Generate the models/index.ts barrel file
 */
export function generateModelsBarrel(tables: CleanTable[]): GeneratedBarrelFile {
  const project = createProject();
  const sourceFile = createSourceFile(project, 'index.ts');

  // Add file header
  sourceFile.insertText(
    0,
    createFileHeader('Models barrel export') + '\n\n'
  );

  // Export all model classes (Select types are now in input-types.ts)
  for (const table of tables) {
    const { typeName } = getTableNames(table);
    const modelName = `${typeName}Model`;
    const fileName = lcFirst(typeName);

    sourceFile.addExportDeclaration({
      moduleSpecifier: `./${fileName}`,
      namedExports: [modelName],
    });
  }

  return {
    fileName: 'models/index.ts',
    content: getFormattedOutput(sourceFile),
  };
}

/**
 * Generate the types.ts file that re-exports all types
 */
export function generateTypesBarrel(_useSharedTypes: boolean): GeneratedBarrelFile {
  // Always re-export from input-types since that's where all types are generated
  const content = `/**
 * Types re-export
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

// Re-export all types from input-types
export * from './input-types';
`;

  return {
    fileName: 'types.ts',
    content,
  };
}
