/**
 * Append-only transcript of an agent run: one agent session entry per row, stored verbatim
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { agentEventKeys } from '../query-keys';
import type {
  AgentEventSelect,
  AgentEventWithRelations,
  AgentEventFilter,
  AgentEventOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  AgentEventSelect,
  AgentEventWithRelations,
  AgentEventFilter,
  AgentEventOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const agentEventsQueryKey = agentEventKeys.list;
/**
 * Append-only transcript of an agent run: one agent session entry per row, stored verbatim
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAgentEventsQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useAgentEventsQuery<
  S extends AgentEventSelect,
  TData = {
    agentEvents: ConnectionResult<InferSelectResult<AgentEventWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AgentEventFilter, AgentEventOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AgentEventSelect>;
  } & Omit<
    UseQueryOptions<
      {
        agentEvents: ConnectionResult<InferSelectResult<AgentEventWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAgentEventsQuery(
  params: {
    selection: ListSelectionConfig<AgentEventSelect, AgentEventFilter, AgentEventOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<AgentEventSelect, AgentEventFilter, AgentEventOrderBy>(
    params.selection
  );
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: agentEventKeys.list(args),
    queryFn: () => getClient().agentEvent.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Append-only transcript of an agent run: one agent session entry per row, stored verbatim
 *
 * @example
 * ```ts
 * const data = await fetchAgentEventsQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchAgentEventsQuery<S extends AgentEventSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, AgentEventFilter, AgentEventOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, AgentEventSelect>;
}): Promise<{
  agentEvents: ConnectionResult<InferSelectResult<AgentEventWithRelations, S>>;
}>;
export async function fetchAgentEventsQuery(params: {
  selection: ListSelectionConfig<AgentEventSelect, AgentEventFilter, AgentEventOrderBy>;
}) {
  const args = buildListSelectionArgs<AgentEventSelect, AgentEventFilter, AgentEventOrderBy>(
    params.selection
  );
  return getClient().agentEvent.findMany(args).unwrap();
}
/**
 * Append-only transcript of an agent run: one agent session entry per row, stored verbatim
 *
 * @example
 * ```ts
 * await prefetchAgentEventsQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchAgentEventsQuery<S extends AgentEventSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, AgentEventFilter, AgentEventOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, AgentEventSelect>;
  }
): Promise<void>;
export async function prefetchAgentEventsQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<AgentEventSelect, AgentEventFilter, AgentEventOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<AgentEventSelect, AgentEventFilter, AgentEventOrderBy>(
    params.selection
  );
  await queryClient.prefetchQuery({
    queryKey: agentEventKeys.list(args),
    queryFn: () => getClient().agentEvent.findMany(args).unwrap(),
  });
}
