/**
 * CLI commands for FunctionDeployment
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
import type {
  CreateFunctionDeploymentInput,
  FunctionDeploymentPatch,
  FunctionDeploymentSelect,
  FunctionDeploymentFilter,
  FunctionDeploymentOrderBy,
} from '../../orm/input-types';
import type { FindManyArgs, FindFirstArgs } from '../../orm/select-types';
const fieldSchema: FieldSchema = {
  annotations: 'json',
  concurrency: 'int',
  createdAt: 'string',
  databaseId: 'uuid',
  errorCount: 'int',
  handlerName: 'string',
  id: 'uuid',
  image: 'string',
  imageVersion: 'string',
  labels: 'json',
  lastError: 'string',
  lastErrorAt: 'string',
  namespaceId: 'uuid',
  resources: 'json',
  revision: 'int',
  scaleMax: 'int',
  scaleMin: 'int',
  serviceName: 'string',
  serviceUrl: 'string',
  status: 'string',
  timeoutSeconds: 'int',
  updatedAt: 'string',
};
const usage =
  '\nfunction-deployment <command>\n\nCommands:\n  list                  List functionDeployment records\n  find-first            Find first matching functionDeployment record\n  get                   Get a functionDeployment by ID\n  create                Create a new functionDeployment\n  update                Update an existing functionDeployment\n  delete                Delete a functionDeployment\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      annotations: true,
      concurrency: true,
      createdAt: true,
      databaseId: true,
      errorCount: true,
      handlerName: true,
      id: true,
      image: true,
      imageVersion: true,
      labels: true,
      lastError: true,
      lastErrorAt: true,
      namespaceId: true,
      resources: true,
      revision: true,
      scaleMax: true,
      scaleMin: true,
      serviceName: true,
      serviceUrl: true,
      status: true,
      timeoutSeconds: true,
      updatedAt: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<
        FunctionDeploymentSelect,
        FunctionDeploymentFilter,
        FunctionDeploymentOrderBy
      > & {
        select: FunctionDeploymentSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.functionDeployment.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      annotations: true,
      concurrency: true,
      createdAt: true,
      databaseId: true,
      errorCount: true,
      handlerName: true,
      id: true,
      image: true,
      imageVersion: true,
      labels: true,
      lastError: true,
      lastErrorAt: true,
      namespaceId: true,
      resources: true,
      revision: true,
      scaleMax: true,
      scaleMin: true,
      serviceName: true,
      serviceUrl: true,
      status: true,
      timeoutSeconds: true,
      updatedAt: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<
        FunctionDeploymentSelect,
        FunctionDeploymentFilter,
        FunctionDeploymentOrderBy
      > & {
        select: FunctionDeploymentSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.functionDeployment.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.functionDeployment
      .findOne({
        id: answers.id as string,
        select: {
          annotations: true,
          concurrency: true,
          createdAt: true,
          databaseId: true,
          errorCount: true,
          handlerName: true,
          id: true,
          image: true,
          imageVersion: true,
          labels: true,
          lastError: true,
          lastErrorAt: true,
          namespaceId: true,
          resources: true,
          revision: true,
          scaleMax: true,
          scaleMin: true,
          serviceName: true,
          serviceUrl: true,
          status: true,
          timeoutSeconds: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'json',
        name: 'annotations',
        message: 'annotations',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'concurrency',
        message: 'concurrency',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: true,
      },
      {
        type: 'text',
        name: 'errorCount',
        message: 'errorCount',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'handlerName',
        message: 'handlerName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'image',
        message: 'image',
        required: true,
      },
      {
        type: 'text',
        name: 'imageVersion',
        message: 'imageVersion',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'labels',
        message: 'labels',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'lastError',
        message: 'lastError',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'lastErrorAt',
        message: 'lastErrorAt',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'namespaceId',
        message: 'namespaceId',
        required: true,
      },
      {
        type: 'json',
        name: 'resources',
        message: 'resources',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'revision',
        message: 'revision',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'scaleMax',
        message: 'scaleMax',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'scaleMin',
        message: 'scaleMin',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'serviceName',
        message: 'serviceName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'serviceUrl',
        message: 'serviceUrl',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'status',
        message: 'status',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'timeoutSeconds',
        message: 'timeoutSeconds',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(
      answers,
      fieldSchema
    ) as CreateFunctionDeploymentInput['functionDeployment'];
    const client = getClient();
    const result = await client.functionDeployment
      .create({
        data: {
          annotations: cleanedData.annotations,
          concurrency: cleanedData.concurrency,
          databaseId: cleanedData.databaseId,
          errorCount: cleanedData.errorCount,
          handlerName: cleanedData.handlerName,
          image: cleanedData.image,
          imageVersion: cleanedData.imageVersion,
          labels: cleanedData.labels,
          lastError: cleanedData.lastError,
          lastErrorAt: cleanedData.lastErrorAt,
          namespaceId: cleanedData.namespaceId,
          resources: cleanedData.resources,
          revision: cleanedData.revision,
          scaleMax: cleanedData.scaleMax,
          scaleMin: cleanedData.scaleMin,
          serviceName: cleanedData.serviceName,
          serviceUrl: cleanedData.serviceUrl,
          status: cleanedData.status,
          timeoutSeconds: cleanedData.timeoutSeconds,
        },
        select: {
          annotations: true,
          concurrency: true,
          createdAt: true,
          databaseId: true,
          errorCount: true,
          handlerName: true,
          id: true,
          image: true,
          imageVersion: true,
          labels: true,
          lastError: true,
          lastErrorAt: true,
          namespaceId: true,
          resources: true,
          revision: true,
          scaleMax: true,
          scaleMin: true,
          serviceName: true,
          serviceUrl: true,
          status: true,
          timeoutSeconds: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'json',
        name: 'annotations',
        message: 'annotations',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'concurrency',
        message: 'concurrency',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
      },
      {
        type: 'text',
        name: 'errorCount',
        message: 'errorCount',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'handlerName',
        message: 'handlerName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'image',
        message: 'image',
        required: false,
      },
      {
        type: 'text',
        name: 'imageVersion',
        message: 'imageVersion',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'labels',
        message: 'labels',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'lastError',
        message: 'lastError',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'lastErrorAt',
        message: 'lastErrorAt',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'namespaceId',
        message: 'namespaceId',
        required: false,
      },
      {
        type: 'json',
        name: 'resources',
        message: 'resources',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'revision',
        message: 'revision',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'scaleMax',
        message: 'scaleMax',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'scaleMin',
        message: 'scaleMin',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'serviceName',
        message: 'serviceName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'serviceUrl',
        message: 'serviceUrl',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'status',
        message: 'status',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'timeoutSeconds',
        message: 'timeoutSeconds',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as FunctionDeploymentPatch;
    const client = getClient();
    const result = await client.functionDeployment
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          annotations: cleanedData.annotations,
          concurrency: cleanedData.concurrency,
          databaseId: cleanedData.databaseId,
          errorCount: cleanedData.errorCount,
          handlerName: cleanedData.handlerName,
          image: cleanedData.image,
          imageVersion: cleanedData.imageVersion,
          labels: cleanedData.labels,
          lastError: cleanedData.lastError,
          lastErrorAt: cleanedData.lastErrorAt,
          namespaceId: cleanedData.namespaceId,
          resources: cleanedData.resources,
          revision: cleanedData.revision,
          scaleMax: cleanedData.scaleMax,
          scaleMin: cleanedData.scaleMin,
          serviceName: cleanedData.serviceName,
          serviceUrl: cleanedData.serviceUrl,
          status: cleanedData.status,
          timeoutSeconds: cleanedData.timeoutSeconds,
        },
        select: {
          annotations: true,
          concurrency: true,
          createdAt: true,
          databaseId: true,
          errorCount: true,
          handlerName: true,
          id: true,
          image: true,
          imageVersion: true,
          labels: true,
          lastError: true,
          lastErrorAt: true,
          namespaceId: true,
          resources: true,
          revision: true,
          scaleMax: true,
          scaleMin: true,
          serviceName: true,
          serviceUrl: true,
          status: true,
          timeoutSeconds: true,
          updatedAt: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.functionDeployment
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
