/**
 * AppLevelGrant model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  AppLevelGrant,
  AppLevelGrantWithRelations,
  AppLevelGrantSelect,
  AppLevelGrantFilter,
  AppLevelGrantOrderBy,
  CreateAppLevelGrantInput,
  UpdateAppLevelGrantInput,
  AppLevelGrantPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class AppLevelGrantModel {
  constructor(private client: OrmClient) {}
  findMany<S extends AppLevelGrantSelect>(
    args: FindManyArgs<S, AppLevelGrantFilter, AppLevelGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLevelGrantSelect>
  ): QueryBuilder<{
    appLevelGrants: ConnectionResult<InferSelectResult<AppLevelGrantWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLevelGrant',
      'appLevelGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'AppLevelGrantFilter',
      'AppLevelGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLevelGrant',
      fieldName: 'appLevelGrants',
      document,
      variables,
    });
  }
  findFirst<S extends AppLevelGrantSelect>(
    args: FindFirstArgs<S, AppLevelGrantFilter, AppLevelGrantOrderBy> & {
      select: S;
    } & StrictSelect<S, AppLevelGrantSelect>
  ): QueryBuilder<{
    appLevelGrant: InferSelectResult<AppLevelGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'AppLevelGrant',
      'appLevelGrants',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'AppLevelGrantFilter',
      'AppLevelGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLevelGrant',
      fieldName: 'appLevelGrant',
      document,
      variables,
      transform: (data: {
        appLevelGrants?: {
          nodes?: InferSelectResult<AppLevelGrantWithRelations, S>[];
        };
      }) => ({
        appLevelGrant: data.appLevelGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends AppLevelGrantSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, AppLevelGrantSelect>
  ): QueryBuilder<{
    appLevelGrant: InferSelectResult<AppLevelGrantWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'AppLevelGrant',
      'appLevelGrants',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'AppLevelGrantFilter',
      'AppLevelGrantOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'AppLevelGrant',
      fieldName: 'appLevelGrant',
      document,
      variables,
      transform: (data: {
        appLevelGrants?: {
          nodes?: InferSelectResult<AppLevelGrantWithRelations, S>[];
        };
      }) => ({
        appLevelGrant: data.appLevelGrants?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends AppLevelGrantSelect>(
    args: CreateArgs<S, CreateAppLevelGrantInput['appLevelGrant']> & {
      select: S;
    } & StrictSelect<S, AppLevelGrantSelect>
  ): QueryBuilder<{
    createAppLevelGrant: {
      appLevelGrant: InferSelectResult<AppLevelGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'AppLevelGrant',
      'createAppLevelGrant',
      'appLevelGrant',
      args.select,
      args.data,
      'CreateAppLevelGrantInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLevelGrant',
      fieldName: 'createAppLevelGrant',
      document,
      variables,
    });
  }
  update<S extends AppLevelGrantSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      AppLevelGrantPatch
    > & {
      select: S;
    } & StrictSelect<S, AppLevelGrantSelect>
  ): QueryBuilder<{
    updateAppLevelGrant: {
      appLevelGrant: InferSelectResult<AppLevelGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'AppLevelGrant',
      'updateAppLevelGrant',
      'appLevelGrant',
      args.select,
      args.where.id,
      args.data,
      'UpdateAppLevelGrantInput',
      'id',
      'appLevelGrantPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLevelGrant',
      fieldName: 'updateAppLevelGrant',
      document,
      variables,
    });
  }
  delete<S extends AppLevelGrantSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, AppLevelGrantSelect>
  ): QueryBuilder<{
    deleteAppLevelGrant: {
      appLevelGrant: InferSelectResult<AppLevelGrantWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'AppLevelGrant',
      'deleteAppLevelGrant',
      'appLevelGrant',
      {
        id: args.where.id,
      },
      'DeleteAppLevelGrantInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'AppLevelGrant',
      fieldName: 'deleteAppLevelGrant',
      document,
      variables,
    });
  }
}
