/**
 * Meter model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  Meter,
  MeterWithRelations,
  MeterSelect,
  MeterFilter,
  MeterOrderBy,
  CreateMeterInput,
  UpdateMeterInput,
  MeterPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class MeterModel {
  constructor(private client: OrmClient) {}
  findMany<S extends MeterSelect>(
    args: FindManyArgs<S, MeterFilter, MeterOrderBy> & {
      select: S;
    } & StrictSelect<S, MeterSelect>
  ): QueryBuilder<{
    meters: ConnectionResult<InferSelectResult<MeterWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Meter',
      'meters',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'MeterFilter',
      'MeterOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Meter',
      fieldName: 'meters',
      document,
      variables,
    });
  }
  findFirst<S extends MeterSelect>(
    args: FindFirstArgs<S, MeterFilter, MeterOrderBy> & {
      select: S;
    } & StrictSelect<S, MeterSelect>
  ): QueryBuilder<{
    meter: InferSelectResult<MeterWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'Meter',
      'meters',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'MeterFilter',
      'MeterOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Meter',
      fieldName: 'meter',
      document,
      variables,
      transform: (data: {
        meters?: {
          nodes?: InferSelectResult<MeterWithRelations, S>[];
        };
      }) => ({
        meter: data.meters?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends MeterSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, MeterSelect>
  ): QueryBuilder<{
    meter: InferSelectResult<MeterWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'Meter',
      'meters',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'MeterFilter',
      'MeterOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'Meter',
      fieldName: 'meter',
      document,
      variables,
      transform: (data: {
        meters?: {
          nodes?: InferSelectResult<MeterWithRelations, S>[];
        };
      }) => ({
        meter: data.meters?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends MeterSelect>(
    args: CreateArgs<S, CreateMeterInput['meter']> & {
      select: S;
    } & StrictSelect<S, MeterSelect>
  ): QueryBuilder<{
    createMeter: {
      meter: InferSelectResult<MeterWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'Meter',
      'createMeter',
      'meter',
      args.select,
      args.data,
      'CreateMeterInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Meter',
      fieldName: 'createMeter',
      document,
      variables,
    });
  }
  update<S extends MeterSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      MeterPatch
    > & {
      select: S;
    } & StrictSelect<S, MeterSelect>
  ): QueryBuilder<{
    updateMeter: {
      meter: InferSelectResult<MeterWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'Meter',
      'updateMeter',
      'meter',
      args.select,
      args.where.id,
      args.data,
      'UpdateMeterInput',
      'id',
      'meterPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Meter',
      fieldName: 'updateMeter',
      document,
      variables,
    });
  }
  delete<S extends MeterSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, MeterSelect>
  ): QueryBuilder<{
    deleteMeter: {
      meter: InferSelectResult<MeterWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'Meter',
      'deleteMeter',
      'meter',
      {
        id: args.where.id,
      },
      'DeleteMeterInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'Meter',
      fieldName: 'deleteMeter',
      document,
      variables,
    });
  }
}
