/**
 * FileRefField model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  FileRefField,
  FileRefFieldWithRelations,
  FileRefFieldSelect,
  FileRefFieldFilter,
  FileRefFieldOrderBy,
  CreateFileRefFieldInput,
  UpdateFileRefFieldInput,
  FileRefFieldPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class FileRefFieldModel {
  constructor(private client: OrmClient) {}
  findMany<S extends FileRefFieldSelect>(
    args: FindManyArgs<S, FileRefFieldFilter, FileRefFieldOrderBy> & {
      select: S;
    } & StrictSelect<S, FileRefFieldSelect>
  ): QueryBuilder<{
    fileRefFields: ConnectionResult<InferSelectResult<FileRefFieldWithRelations, S>>;
  }> {
    const { document, variables } = buildFindManyDocument(
      'FileRefField',
      'fileRefFields',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'FileRefFieldFilter',
      'FileRefFieldOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'FileRefField',
      fieldName: 'fileRefFields',
      document,
      variables,
    });
  }
  findFirst<S extends FileRefFieldSelect>(
    args: FindFirstArgs<S, FileRefFieldFilter, FileRefFieldOrderBy> & {
      select: S;
    } & StrictSelect<S, FileRefFieldSelect>
  ): QueryBuilder<{
    fileRefField: InferSelectResult<FileRefFieldWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'FileRefField',
      'fileRefFields',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'FileRefFieldFilter',
      'FileRefFieldOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'FileRefField',
      fieldName: 'fileRefField',
      document,
      variables,
      transform: (data: {
        fileRefFields?: {
          nodes?: InferSelectResult<FileRefFieldWithRelations, S>[];
        };
      }) => ({
        fileRefField: data.fileRefFields?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends FileRefFieldSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, FileRefFieldSelect>
  ): QueryBuilder<{
    fileRefField: InferSelectResult<FileRefFieldWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'FileRefField',
      'fileRefFields',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'FileRefFieldFilter',
      'FileRefFieldOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'FileRefField',
      fieldName: 'fileRefField',
      document,
      variables,
      transform: (data: {
        fileRefFields?: {
          nodes?: InferSelectResult<FileRefFieldWithRelations, S>[];
        };
      }) => ({
        fileRefField: data.fileRefFields?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends FileRefFieldSelect>(
    args: CreateArgs<S, CreateFileRefFieldInput['fileRefField']> & {
      select: S;
    } & StrictSelect<S, FileRefFieldSelect>
  ): QueryBuilder<{
    createFileRefField: {
      fileRefField: InferSelectResult<FileRefFieldWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'FileRefField',
      'createFileRefField',
      'fileRefField',
      args.select,
      args.data,
      'CreateFileRefFieldInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'FileRefField',
      fieldName: 'createFileRefField',
      document,
      variables,
    });
  }
  update<S extends FileRefFieldSelect>(
    args: UpdateArgs<
      S,
      {
        id: string;
      },
      FileRefFieldPatch
    > & {
      select: S;
    } & StrictSelect<S, FileRefFieldSelect>
  ): QueryBuilder<{
    updateFileRefField: {
      fileRefField: InferSelectResult<FileRefFieldWithRelations, S>;
    };
  }> {
    const { document, variables } = buildUpdateByPkDocument(
      'FileRefField',
      'updateFileRefField',
      'fileRefField',
      args.select,
      args.where.id,
      args.data,
      'UpdateFileRefFieldInput',
      'id',
      'fileRefFieldPatch',
      connectionFieldsMap,
      undefined
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'FileRefField',
      fieldName: 'updateFileRefField',
      document,
      variables,
    });
  }
  delete<S extends FileRefFieldSelect>(
    args: DeleteArgs<
      {
        id: string;
      },
      S
    > & {
      select: S;
    } & StrictSelect<S, FileRefFieldSelect>
  ): QueryBuilder<{
    deleteFileRefField: {
      fileRefField: InferSelectResult<FileRefFieldWithRelations, S>;
    };
  }> {
    const { document, variables } = buildDeleteByPkDocument(
      'FileRefField',
      'deleteFileRefField',
      'fileRefField',
      {
        id: args.where.id,
      },
      'DeleteFileRefFieldInput',
      args.select,
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'FileRefField',
      fieldName: 'deleteFileRefField',
      document,
      variables,
    });
  }
}
