/**
 * Provisions the platform-managed Kubernetes admission catalogs: a kinds table and a spec-rules table, Merkle-versioned through the referenced merkle_store_module, whose rows the generated admission gate on resources/resource_definitions reads. Writes are platform-admin and human-only; every scope reads the one catalog.
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { k8sAdmissionModuleKeys } from '../query-keys';
import type {
  K8sAdmissionModuleSelect,
  K8sAdmissionModuleWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  K8sAdmissionModuleSelect,
  K8sAdmissionModuleWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const k8sAdmissionModuleQueryKey = k8sAdmissionModuleKeys.detail;
/**
 * Provisions the platform-managed Kubernetes admission catalogs: a kinds table and a spec-rules table, Merkle-versioned through the referenced merkle_store_module, whose rows the generated admission gate on resources/resource_definitions reads. Writes are platform-admin and human-only; every scope reads the one catalog.
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useK8sAdmissionModuleQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useK8sAdmissionModuleQuery<
  S extends K8sAdmissionModuleSelect,
  TData = {
    k8sAdmissionModule: InferSelectResult<K8sAdmissionModuleWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, K8sAdmissionModuleSelect>;
  } & Omit<
    UseQueryOptions<
      {
        k8sAdmissionModule: InferSelectResult<K8sAdmissionModuleWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useK8sAdmissionModuleQuery(
  params: {
    id: string;
    selection: SelectionConfig<K8sAdmissionModuleSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<K8sAdmissionModuleSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: k8sAdmissionModuleKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .k8sAdmissionModule.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Provisions the platform-managed Kubernetes admission catalogs: a kinds table and a spec-rules table, Merkle-versioned through the referenced merkle_store_module, whose rows the generated admission gate on resources/resource_definitions reads. Writes are platform-admin and human-only; every scope reads the one catalog.
 *
 * @example
 * ```ts
 * const data = await fetchK8sAdmissionModuleQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchK8sAdmissionModuleQuery<S extends K8sAdmissionModuleSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, K8sAdmissionModuleSelect>;
}): Promise<{
  k8sAdmissionModule: InferSelectResult<K8sAdmissionModuleWithRelations, S> | null;
}>;
export async function fetchK8sAdmissionModuleQuery(params: {
  id: string;
  selection: SelectionConfig<K8sAdmissionModuleSelect>;
}): Promise<any> {
  const args = buildSelectionArgs<K8sAdmissionModuleSelect>(params.selection);
  return getClient()
    .k8sAdmissionModule.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Provisions the platform-managed Kubernetes admission catalogs: a kinds table and a spec-rules table, Merkle-versioned through the referenced merkle_store_module, whose rows the generated admission gate on resources/resource_definitions reads. Writes are platform-admin and human-only; every scope reads the one catalog.
 *
 * @example
 * ```ts
 * await prefetchK8sAdmissionModuleQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchK8sAdmissionModuleQuery<S extends K8sAdmissionModuleSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, K8sAdmissionModuleSelect>;
  }
): Promise<void>;
export async function prefetchK8sAdmissionModuleQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<K8sAdmissionModuleSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<K8sAdmissionModuleSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: k8sAdmissionModuleKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .k8sAdmissionModule.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
