/**
 * CLI commands for ImageModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
import type {
  CreateImageModuleInput,
  ImageModulePatch,
  ImageModuleSelect,
  ImageModuleFilter,
  ImageModuleOrderBy,
} from '../../orm/input-types';
import type { FindManyArgs, FindFirstArgs } from '../../orm/select-types';
const fieldSchema: FieldSchema = {
  apiName: 'string',
  databaseId: 'uuid',
  defaultCapabilities: 'string',
  entityField: 'string',
  entityTableId: 'uuid',
  id: 'uuid',
  imageGrantsTableId: 'uuid',
  imageGrantsTableName: 'string',
  imagesTableId: 'uuid',
  imagesTableName: 'string',
  policies: 'json',
  prefix: 'string',
  privateApiName: 'string',
  privateSchemaId: 'uuid',
  privateSchemaName: 'string',
  provisions: 'json',
  publicSchemaName: 'string',
  registriesTableId: 'uuid',
  registriesTableName: 'string',
  registryGrantsTableId: 'uuid',
  registryGrantsTableName: 'string',
  schemaId: 'uuid',
  scope: 'string',
};
const usage =
  '\nimage-module <command>\n\nCommands:\n  list                  List imageModule records\n  find-first            Find first matching imageModule record\n  get                   Get a imageModule by ID\n  create                Create a new imageModule\n  update                Update an existing imageModule\n  delete                Delete a imageModule\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      apiName: true,
      databaseId: true,
      defaultCapabilities: true,
      entityField: true,
      entityTableId: true,
      id: true,
      imageGrantsTableId: true,
      imageGrantsTableName: true,
      imagesTableId: true,
      imagesTableName: true,
      policies: true,
      prefix: true,
      privateApiName: true,
      privateSchemaId: true,
      privateSchemaName: true,
      provisions: true,
      publicSchemaName: true,
      registriesTableId: true,
      registriesTableName: true,
      registryGrantsTableId: true,
      registryGrantsTableName: true,
      schemaId: true,
      scope: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<ImageModuleSelect, ImageModuleFilter, ImageModuleOrderBy> & {
        select: ImageModuleSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.imageModule.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      apiName: true,
      databaseId: true,
      defaultCapabilities: true,
      entityField: true,
      entityTableId: true,
      id: true,
      imageGrantsTableId: true,
      imageGrantsTableName: true,
      imagesTableId: true,
      imagesTableName: true,
      policies: true,
      prefix: true,
      privateApiName: true,
      privateSchemaId: true,
      privateSchemaName: true,
      provisions: true,
      publicSchemaName: true,
      registriesTableId: true,
      registriesTableName: true,
      registryGrantsTableId: true,
      registryGrantsTableName: true,
      schemaId: true,
      scope: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<ImageModuleSelect, ImageModuleFilter, ImageModuleOrderBy> & {
        select: ImageModuleSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.imageModule.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.imageModule
      .findOne({
        id: answers.id as string,
        select: {
          apiName: true,
          databaseId: true,
          defaultCapabilities: true,
          entityField: true,
          entityTableId: true,
          id: true,
          imageGrantsTableId: true,
          imageGrantsTableName: true,
          imagesTableId: true,
          imagesTableName: true,
          policies: true,
          prefix: true,
          privateApiName: true,
          privateSchemaId: true,
          privateSchemaName: true,
          provisions: true,
          publicSchemaName: true,
          registriesTableId: true,
          registriesTableName: true,
          registryGrantsTableId: true,
          registryGrantsTableName: true,
          schemaId: true,
          scope: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'apiName',
        message: 'apiName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: true,
      },
      {
        type: 'text',
        name: 'defaultCapabilities',
        message: 'defaultCapabilities',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'entityField',
        message: 'entityField',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'entityTableId',
        message: 'entityTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'imageGrantsTableId',
        message: 'imageGrantsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'imageGrantsTableName',
        message: 'imageGrantsTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'imagesTableId',
        message: 'imagesTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'imagesTableName',
        message: 'imagesTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'policies',
        message: 'policies',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'prefix',
        message: 'prefix',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'privateApiName',
        message: 'privateApiName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'privateSchemaId',
        message: 'privateSchemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'privateSchemaName',
        message: 'privateSchemaName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'provisions',
        message: 'provisions',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'publicSchemaName',
        message: 'publicSchemaName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'registriesTableId',
        message: 'registriesTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'registriesTableName',
        message: 'registriesTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'registryGrantsTableId',
        message: 'registryGrantsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'registryGrantsTableName',
        message: 'registryGrantsTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'scope',
        message: 'scope',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(
      answers,
      fieldSchema
    ) as CreateImageModuleInput['imageModule'];
    const client = getClient();
    const result = await client.imageModule
      .create({
        data: {
          apiName: cleanedData.apiName,
          databaseId: cleanedData.databaseId,
          defaultCapabilities: cleanedData.defaultCapabilities,
          entityField: cleanedData.entityField,
          entityTableId: cleanedData.entityTableId,
          imageGrantsTableId: cleanedData.imageGrantsTableId,
          imageGrantsTableName: cleanedData.imageGrantsTableName,
          imagesTableId: cleanedData.imagesTableId,
          imagesTableName: cleanedData.imagesTableName,
          policies: cleanedData.policies,
          prefix: cleanedData.prefix,
          privateApiName: cleanedData.privateApiName,
          privateSchemaId: cleanedData.privateSchemaId,
          privateSchemaName: cleanedData.privateSchemaName,
          provisions: cleanedData.provisions,
          publicSchemaName: cleanedData.publicSchemaName,
          registriesTableId: cleanedData.registriesTableId,
          registriesTableName: cleanedData.registriesTableName,
          registryGrantsTableId: cleanedData.registryGrantsTableId,
          registryGrantsTableName: cleanedData.registryGrantsTableName,
          schemaId: cleanedData.schemaId,
          scope: cleanedData.scope,
        },
        select: {
          apiName: true,
          databaseId: true,
          defaultCapabilities: true,
          entityField: true,
          entityTableId: true,
          id: true,
          imageGrantsTableId: true,
          imageGrantsTableName: true,
          imagesTableId: true,
          imagesTableName: true,
          policies: true,
          prefix: true,
          privateApiName: true,
          privateSchemaId: true,
          privateSchemaName: true,
          provisions: true,
          publicSchemaName: true,
          registriesTableId: true,
          registriesTableName: true,
          registryGrantsTableId: true,
          registryGrantsTableName: true,
          schemaId: true,
          scope: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'apiName',
        message: 'apiName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
      },
      {
        type: 'text',
        name: 'defaultCapabilities',
        message: 'defaultCapabilities',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'entityField',
        message: 'entityField',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'entityTableId',
        message: 'entityTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'imageGrantsTableId',
        message: 'imageGrantsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'imageGrantsTableName',
        message: 'imageGrantsTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'imagesTableId',
        message: 'imagesTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'imagesTableName',
        message: 'imagesTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'policies',
        message: 'policies',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'prefix',
        message: 'prefix',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'privateApiName',
        message: 'privateApiName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'privateSchemaId',
        message: 'privateSchemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'privateSchemaName',
        message: 'privateSchemaName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'json',
        name: 'provisions',
        message: 'provisions',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'publicSchemaName',
        message: 'publicSchemaName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'registriesTableId',
        message: 'registriesTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'registriesTableName',
        message: 'registriesTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'registryGrantsTableId',
        message: 'registryGrantsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'registryGrantsTableName',
        message: 'registryGrantsTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'scope',
        message: 'scope',
        required: false,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as ImageModulePatch;
    const client = getClient();
    const result = await client.imageModule
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          apiName: cleanedData.apiName,
          databaseId: cleanedData.databaseId,
          defaultCapabilities: cleanedData.defaultCapabilities,
          entityField: cleanedData.entityField,
          entityTableId: cleanedData.entityTableId,
          imageGrantsTableId: cleanedData.imageGrantsTableId,
          imageGrantsTableName: cleanedData.imageGrantsTableName,
          imagesTableId: cleanedData.imagesTableId,
          imagesTableName: cleanedData.imagesTableName,
          policies: cleanedData.policies,
          prefix: cleanedData.prefix,
          privateApiName: cleanedData.privateApiName,
          privateSchemaId: cleanedData.privateSchemaId,
          privateSchemaName: cleanedData.privateSchemaName,
          provisions: cleanedData.provisions,
          publicSchemaName: cleanedData.publicSchemaName,
          registriesTableId: cleanedData.registriesTableId,
          registriesTableName: cleanedData.registriesTableName,
          registryGrantsTableId: cleanedData.registryGrantsTableId,
          registryGrantsTableName: cleanedData.registryGrantsTableName,
          schemaId: cleanedData.schemaId,
          scope: cleanedData.scope,
        },
        select: {
          apiName: true,
          databaseId: true,
          defaultCapabilities: true,
          entityField: true,
          entityTableId: true,
          id: true,
          imageGrantsTableId: true,
          imageGrantsTableName: true,
          imagesTableId: true,
          imagesTableName: true,
          policies: true,
          prefix: true,
          privateApiName: true,
          privateSchemaId: true,
          privateSchemaName: true,
          provisions: true,
          publicSchemaName: true,
          registriesTableId: true,
          registriesTableName: true,
          registryGrantsTableId: true,
          registryGrantsTableName: true,
          schemaId: true,
          scope: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.imageModule
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
