/**
 * CLI commands for PrincipalAuthModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { CLIOptions, Inquirerer, extractFirst } from 'inquirerer';
import { getClient } from '../executor';
import { coerceAnswers, parseFindFirstArgs, parseFindManyArgs, stripUndefined } from '../utils';
import type { FieldSchema } from '../utils';
import type {
  CreatePrincipalAuthModuleInput,
  PrincipalAuthModulePatch,
  PrincipalAuthModuleSelect,
  PrincipalAuthModuleFilter,
  PrincipalAuthModuleOrderBy,
} from '../../orm/input-types';
import type { FindManyArgs, FindFirstArgs } from '../../orm/select-types';
const fieldSchema: FieldSchema = {
  apiName: 'string',
  auditsTableId: 'uuid',
  createOrgApiKeyFunction: 'string',
  createOrgPrincipalFunction: 'string',
  createPrincipalFunction: 'string',
  databaseId: 'uuid',
  deleteOrgPrincipalFunction: 'string',
  deletePrincipalFunction: 'string',
  id: 'uuid',
  principalEntitiesTableId: 'uuid',
  principalScopeOverridesTableId: 'uuid',
  principalsTableId: 'uuid',
  principalsTableName: 'string',
  revokeOrgApiKeyFunction: 'string',
  schemaId: 'uuid',
  sessionCredentialsTableId: 'uuid',
  sessionsTableId: 'uuid',
  usersTableId: 'uuid',
};
const usage =
  '\nprincipal-auth-module <command>\n\nCommands:\n  list                  List principalAuthModule records\n  find-first            Find first matching principalAuthModule record\n  get                   Get a principalAuthModule by ID\n  create                Create a new principalAuthModule\n  update                Update an existing principalAuthModule\n  delete                Delete a principalAuthModule\n\nList Options:\n  --limit <n>           Max number of records to return (forward pagination)\n  --last <n>            Number of records from the end (backward pagination)\n  --after <cursor>      Cursor for forward pagination\n  --before <cursor>     Cursor for backward pagination\n  --offset <n>          Number of records to skip\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.name.equalTo foo)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\nFind-First Options:\n  --select <fields>     Comma-separated list of fields to return\n  --where.<field>.<op>  Filter (dot-notation, e.g. --where.status.equalTo active)\n  --condition.<f>.<op>  Condition filter (dot-notation)\n  --orderBy <values>    Comma-separated ordering values (e.g. NAME_ASC,CREATED_AT_DESC)\n\n  --help, -h            Show this help message\n';
export default async (
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer,
  _options: CLIOptions
) => {
  if (argv.help || argv.h) {
    console.log(usage);
    process.exit(0);
  }
  const { first: subcommand, newArgv } = extractFirst(argv);
  if (!subcommand) {
    const answer = await prompter.prompt(argv, [
      {
        type: 'autocomplete',
        name: 'subcommand',
        message: 'What do you want to do?',
        options: ['list', 'find-first', 'get', 'create', 'update', 'delete'],
      },
    ]);
    return handleTableSubcommand(answer.subcommand as string, newArgv, prompter);
  }
  return handleTableSubcommand(subcommand, newArgv, prompter);
};
async function handleTableSubcommand(
  subcommand: string,
  argv: Partial<Record<string, unknown>>,
  prompter: Inquirerer
) {
  switch (subcommand) {
    case 'list':
      return handleList(argv, prompter);
    case 'find-first':
      return handleFindFirst(argv, prompter);
    case 'get':
      return handleGet(argv, prompter);
    case 'create':
      return handleCreate(argv, prompter);
    case 'update':
      return handleUpdate(argv, prompter);
    case 'delete':
      return handleDelete(argv, prompter);
    default:
      console.log(usage);
      process.exit(1);
  }
}
async function handleList(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      apiName: true,
      auditsTableId: true,
      createOrgApiKeyFunction: true,
      createOrgPrincipalFunction: true,
      createPrincipalFunction: true,
      databaseId: true,
      deleteOrgPrincipalFunction: true,
      deletePrincipalFunction: true,
      id: true,
      principalEntitiesTableId: true,
      principalScopeOverridesTableId: true,
      principalsTableId: true,
      principalsTableName: true,
      revokeOrgApiKeyFunction: true,
      schemaId: true,
      sessionCredentialsTableId: true,
      sessionsTableId: true,
      usersTableId: true,
    };
    const findManyArgs = parseFindManyArgs<
      FindManyArgs<
        PrincipalAuthModuleSelect,
        PrincipalAuthModuleFilter,
        PrincipalAuthModuleOrderBy
      > & {
        select: PrincipalAuthModuleSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.principalAuthModule.findMany(findManyArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to list records.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleFindFirst(argv: Partial<Record<string, unknown>>, _prompter: Inquirerer) {
  try {
    const defaultSelect = {
      apiName: true,
      auditsTableId: true,
      createOrgApiKeyFunction: true,
      createOrgPrincipalFunction: true,
      createPrincipalFunction: true,
      databaseId: true,
      deleteOrgPrincipalFunction: true,
      deletePrincipalFunction: true,
      id: true,
      principalEntitiesTableId: true,
      principalScopeOverridesTableId: true,
      principalsTableId: true,
      principalsTableName: true,
      revokeOrgApiKeyFunction: true,
      schemaId: true,
      sessionCredentialsTableId: true,
      sessionsTableId: true,
      usersTableId: true,
    };
    const findFirstArgs = parseFindFirstArgs<
      FindFirstArgs<
        PrincipalAuthModuleSelect,
        PrincipalAuthModuleFilter,
        PrincipalAuthModuleOrderBy
      > & {
        select: PrincipalAuthModuleSelect;
      }
    >(argv, defaultSelect);
    const client = getClient();
    const result = await client.principalAuthModule.findFirst(findFirstArgs).execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to find record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleGet(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const answers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const client = getClient();
    const result = await client.principalAuthModule
      .findOne({
        id: answers.id as string,
        select: {
          apiName: true,
          auditsTableId: true,
          createOrgApiKeyFunction: true,
          createOrgPrincipalFunction: true,
          createPrincipalFunction: true,
          databaseId: true,
          deleteOrgPrincipalFunction: true,
          deletePrincipalFunction: true,
          id: true,
          principalEntitiesTableId: true,
          principalScopeOverridesTableId: true,
          principalsTableId: true,
          principalsTableName: true,
          revokeOrgApiKeyFunction: true,
          schemaId: true,
          sessionCredentialsTableId: true,
          sessionsTableId: true,
          usersTableId: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Record not found.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleCreate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'apiName',
        message: 'apiName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'auditsTableId',
        message: 'auditsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'createOrgApiKeyFunction',
        message: 'createOrgApiKeyFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'createOrgPrincipalFunction',
        message: 'createOrgPrincipalFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'createPrincipalFunction',
        message: 'createPrincipalFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: true,
      },
      {
        type: 'text',
        name: 'deleteOrgPrincipalFunction',
        message: 'deleteOrgPrincipalFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'deletePrincipalFunction',
        message: 'deletePrincipalFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'principalEntitiesTableId',
        message: 'principalEntitiesTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'principalScopeOverridesTableId',
        message: 'principalScopeOverridesTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'principalsTableId',
        message: 'principalsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'principalsTableName',
        message: 'principalsTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'revokeOrgApiKeyFunction',
        message: 'revokeOrgApiKeyFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sessionCredentialsTableId',
        message: 'sessionCredentialsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sessionsTableId',
        message: 'sessionsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'usersTableId',
        message: 'usersTableId',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(
      answers,
      fieldSchema
    ) as CreatePrincipalAuthModuleInput['principalAuthModule'];
    const client = getClient();
    const result = await client.principalAuthModule
      .create({
        data: {
          apiName: cleanedData.apiName,
          auditsTableId: cleanedData.auditsTableId,
          createOrgApiKeyFunction: cleanedData.createOrgApiKeyFunction,
          createOrgPrincipalFunction: cleanedData.createOrgPrincipalFunction,
          createPrincipalFunction: cleanedData.createPrincipalFunction,
          databaseId: cleanedData.databaseId,
          deleteOrgPrincipalFunction: cleanedData.deleteOrgPrincipalFunction,
          deletePrincipalFunction: cleanedData.deletePrincipalFunction,
          principalEntitiesTableId: cleanedData.principalEntitiesTableId,
          principalScopeOverridesTableId: cleanedData.principalScopeOverridesTableId,
          principalsTableId: cleanedData.principalsTableId,
          principalsTableName: cleanedData.principalsTableName,
          revokeOrgApiKeyFunction: cleanedData.revokeOrgApiKeyFunction,
          schemaId: cleanedData.schemaId,
          sessionCredentialsTableId: cleanedData.sessionCredentialsTableId,
          sessionsTableId: cleanedData.sessionsTableId,
          usersTableId: cleanedData.usersTableId,
        },
        select: {
          apiName: true,
          auditsTableId: true,
          createOrgApiKeyFunction: true,
          createOrgPrincipalFunction: true,
          createPrincipalFunction: true,
          databaseId: true,
          deleteOrgPrincipalFunction: true,
          deletePrincipalFunction: true,
          id: true,
          principalEntitiesTableId: true,
          principalScopeOverridesTableId: true,
          principalsTableId: true,
          principalsTableName: true,
          revokeOrgApiKeyFunction: true,
          schemaId: true,
          sessionCredentialsTableId: true,
          sessionsTableId: true,
          usersTableId: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to create record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleUpdate(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
      {
        type: 'text',
        name: 'apiName',
        message: 'apiName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'auditsTableId',
        message: 'auditsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'createOrgApiKeyFunction',
        message: 'createOrgApiKeyFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'createOrgPrincipalFunction',
        message: 'createOrgPrincipalFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'createPrincipalFunction',
        message: 'createPrincipalFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'databaseId',
        message: 'databaseId',
        required: false,
      },
      {
        type: 'text',
        name: 'deleteOrgPrincipalFunction',
        message: 'deleteOrgPrincipalFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'deletePrincipalFunction',
        message: 'deletePrincipalFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'principalEntitiesTableId',
        message: 'principalEntitiesTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'principalScopeOverridesTableId',
        message: 'principalScopeOverridesTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'principalsTableId',
        message: 'principalsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'principalsTableName',
        message: 'principalsTableName',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'revokeOrgApiKeyFunction',
        message: 'revokeOrgApiKeyFunction',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'schemaId',
        message: 'schemaId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sessionCredentialsTableId',
        message: 'sessionCredentialsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'sessionsTableId',
        message: 'sessionsTableId',
        required: false,
        skipPrompt: true,
      },
      {
        type: 'text',
        name: 'usersTableId',
        message: 'usersTableId',
        required: false,
        skipPrompt: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const cleanedData = stripUndefined(answers, fieldSchema) as PrincipalAuthModulePatch;
    const client = getClient();
    const result = await client.principalAuthModule
      .update({
        where: {
          id: answers.id as string,
        },
        data: {
          apiName: cleanedData.apiName,
          auditsTableId: cleanedData.auditsTableId,
          createOrgApiKeyFunction: cleanedData.createOrgApiKeyFunction,
          createOrgPrincipalFunction: cleanedData.createOrgPrincipalFunction,
          createPrincipalFunction: cleanedData.createPrincipalFunction,
          databaseId: cleanedData.databaseId,
          deleteOrgPrincipalFunction: cleanedData.deleteOrgPrincipalFunction,
          deletePrincipalFunction: cleanedData.deletePrincipalFunction,
          principalEntitiesTableId: cleanedData.principalEntitiesTableId,
          principalScopeOverridesTableId: cleanedData.principalScopeOverridesTableId,
          principalsTableId: cleanedData.principalsTableId,
          principalsTableName: cleanedData.principalsTableName,
          revokeOrgApiKeyFunction: cleanedData.revokeOrgApiKeyFunction,
          schemaId: cleanedData.schemaId,
          sessionCredentialsTableId: cleanedData.sessionCredentialsTableId,
          sessionsTableId: cleanedData.sessionsTableId,
          usersTableId: cleanedData.usersTableId,
        },
        select: {
          apiName: true,
          auditsTableId: true,
          createOrgApiKeyFunction: true,
          createOrgPrincipalFunction: true,
          createPrincipalFunction: true,
          databaseId: true,
          deleteOrgPrincipalFunction: true,
          deletePrincipalFunction: true,
          id: true,
          principalEntitiesTableId: true,
          principalScopeOverridesTableId: true,
          principalsTableId: true,
          principalsTableName: true,
          revokeOrgApiKeyFunction: true,
          schemaId: true,
          sessionCredentialsTableId: true,
          sessionsTableId: true,
          usersTableId: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to update record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
async function handleDelete(argv: Partial<Record<string, unknown>>, prompter: Inquirerer) {
  try {
    const rawAnswers = await prompter.prompt(argv, [
      {
        type: 'text',
        name: 'id',
        message: 'id',
        required: true,
      },
    ]);
    const answers = coerceAnswers(rawAnswers, fieldSchema);
    const client = getClient();
    const result = await client.principalAuthModule
      .delete({
        where: {
          id: answers.id as string,
        },
        select: {
          id: true,
        },
      })
      .execute();
    console.log(JSON.stringify(result, null, 2));
  } catch (error) {
    console.error('Failed to delete record.');
    if (error instanceof Error) {
      console.error(error.message);
    }
    process.exit(1);
  }
}
