/**
 * Single item query hook for AppLevel
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { appLevelKeys } from '../query-keys';
import type { AppLevelSelect, AppLevelWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { AppLevelSelect, AppLevelWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const appLevelQueryKey = appLevelKeys.detail;
/**
 * Query hook for fetching a single AppLevel
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useAppLevelQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useAppLevelQuery<
  S extends AppLevelSelect,
  TData = {
    appLevel: InferSelectResult<AppLevelWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLevelSelect>;
  } & Omit<
    UseQueryOptions<
      {
        appLevel: InferSelectResult<AppLevelWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useAppLevelQuery(
  params: {
    id: string;
    selection: SelectionConfig<AppLevelSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<AppLevelSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: appLevelKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLevel.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch a single AppLevel without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchAppLevelQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchAppLevelQuery<S extends AppLevelSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, AppLevelSelect>;
}): Promise<{
  appLevel: InferSelectResult<AppLevelWithRelations, S> | null;
}>;
export async function fetchAppLevelQuery(params: {
  id: string;
  selection: SelectionConfig<AppLevelSelect>;
}) {
  const args = buildSelectionArgs<AppLevelSelect>(params.selection);
  return getClient()
    .appLevel.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Prefetch a single AppLevel for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchAppLevelQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchAppLevelQuery<S extends AppLevelSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, AppLevelSelect>;
  }
): Promise<void>;
export async function prefetchAppLevelQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<AppLevelSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<AppLevelSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: appLevelKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .appLevel.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
