/**
 * PlatformResourcesHealth model for ORM client
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */
import { OrmClient } from '../client';
import {
  QueryBuilder,
  buildFindManyDocument,
  buildFindFirstDocument,
  buildFindOneDocument,
  buildCreateDocument,
  buildUpdateByPkDocument,
  buildDeleteByPkDocument,
} from '../query-builder';
import type {
  ConnectionResult,
  FindManyArgs,
  FindFirstArgs,
  CreateArgs,
  UpdateArgs,
  DeleteArgs,
  InferSelectResult,
  StrictSelect,
} from '../select-types';
import type {
  PlatformResourcesHealth,
  PlatformResourcesHealthWithRelations,
  PlatformResourcesHealthSelect,
  PlatformResourcesHealthFilter,
  PlatformResourcesHealthOrderBy,
  CreatePlatformResourcesHealthInput,
  UpdatePlatformResourcesHealthInput,
  PlatformResourcesHealthPatch,
} from '../input-types';
import { connectionFieldsMap } from '../input-types';
export class PlatformResourcesHealthModel {
  constructor(private client: OrmClient) {}
  findMany<S extends PlatformResourcesHealthSelect>(
    args: FindManyArgs<S, PlatformResourcesHealthFilter, PlatformResourcesHealthOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformResourcesHealthSelect>
  ): QueryBuilder<{
    platformResourcesHealths: ConnectionResult<
      InferSelectResult<PlatformResourcesHealthWithRelations, S>
    >;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformResourcesHealth',
      'platformResourcesHealths',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
        first: args?.first,
        last: args?.last,
        after: args?.after,
        before: args?.before,
        offset: args?.offset,
      },
      'PlatformResourcesHealthFilter',
      'PlatformResourcesHealthOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformResourcesHealth',
      fieldName: 'platformResourcesHealths',
      document,
      variables,
    });
  }
  findFirst<S extends PlatformResourcesHealthSelect>(
    args: FindFirstArgs<S, PlatformResourcesHealthFilter, PlatformResourcesHealthOrderBy> & {
      select: S;
    } & StrictSelect<S, PlatformResourcesHealthSelect>
  ): QueryBuilder<{
    platformResourcesHealth: InferSelectResult<PlatformResourcesHealthWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindFirstDocument(
      'PlatformResourcesHealth',
      'platformResourcesHealths',
      args.select,
      {
        where: args?.where,
        orderBy: args?.orderBy as string[] | undefined,
      },
      'PlatformResourcesHealthFilter',
      'PlatformResourcesHealthOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformResourcesHealth',
      fieldName: 'platformResourcesHealth',
      document,
      variables,
      transform: (data: {
        platformResourcesHealths?: {
          nodes?: InferSelectResult<PlatformResourcesHealthWithRelations, S>[];
        };
      }) => ({
        platformResourcesHealth: data.platformResourcesHealths?.nodes?.[0] ?? null,
      }),
    });
  }
  findOne<S extends PlatformResourcesHealthSelect>(
    args: {
      id: string;
      select: S;
    } & StrictSelect<S, PlatformResourcesHealthSelect>
  ): QueryBuilder<{
    platformResourcesHealth: InferSelectResult<PlatformResourcesHealthWithRelations, S> | null;
  }> {
    const { document, variables } = buildFindManyDocument(
      'PlatformResourcesHealth',
      'platformResourcesHealths',
      args.select,
      {
        where: {
          id: {
            equalTo: args.id,
          },
        },
        first: 1,
      },
      'PlatformResourcesHealthFilter',
      'PlatformResourcesHealthOrderBy',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'query',
      operationName: 'PlatformResourcesHealth',
      fieldName: 'platformResourcesHealth',
      document,
      variables,
      transform: (data: {
        platformResourcesHealths?: {
          nodes?: InferSelectResult<PlatformResourcesHealthWithRelations, S>[];
        };
      }) => ({
        platformResourcesHealth: data.platformResourcesHealths?.nodes?.[0] ?? null,
      }),
    });
  }
  create<S extends PlatformResourcesHealthSelect>(
    args: CreateArgs<S, CreatePlatformResourcesHealthInput['platformResourcesHealth']> & {
      select: S;
    } & StrictSelect<S, PlatformResourcesHealthSelect>
  ): QueryBuilder<{
    createPlatformResourcesHealth: {
      platformResourcesHealth: InferSelectResult<PlatformResourcesHealthWithRelations, S>;
    };
  }> {
    const { document, variables } = buildCreateDocument(
      'PlatformResourcesHealth',
      'createPlatformResourcesHealth',
      'platformResourcesHealth',
      args.select,
      args.data,
      'CreatePlatformResourcesHealthInput',
      connectionFieldsMap
    );
    return new QueryBuilder({
      client: this.client,
      operation: 'mutation',
      operationName: 'PlatformResourcesHealth',
      fieldName: 'createPlatformResourcesHealth',
      document,
      variables,
    });
  }
}
