/**
 * List query hook for SiteMetadatum
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildListSelectionArgs } from '../selection';
import type { ListSelectionConfig } from '../selection';
import { siteMetadatumKeys } from '../query-keys';
import type {
  SiteMetadatumSelect,
  SiteMetadatumWithRelations,
  SiteMetadatumFilter,
  SiteMetadatumOrderBy,
} from '../../orm/input-types';
import type {
  FindManyArgs,
  InferSelectResult,
  ConnectionResult,
  HookStrictSelect,
} from '../../orm/select-types';
export type {
  SiteMetadatumSelect,
  SiteMetadatumWithRelations,
  SiteMetadatumFilter,
  SiteMetadatumOrderBy,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const siteMetadataQueryKey = siteMetadatumKeys.list;
/**
 * Query hook for fetching SiteMetadatum list
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useSiteMetadataQuery({
 *   selection: {
 *     fields: { id: true, name: true },
 *     where: { name: { equalTo: "example" } },
 *     orderBy: ['CREATED_AT_DESC'],
 *     first: 10,
 *   },
 * });
 * ```
 */
export function useSiteMetadataQuery<
  S extends SiteMetadatumSelect,
  TData = {
    siteMetadata: ConnectionResult<InferSelectResult<SiteMetadatumWithRelations, S>>;
  },
>(
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, SiteMetadatumFilter, SiteMetadatumOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, SiteMetadatumSelect>;
  } & Omit<
    UseQueryOptions<
      {
        siteMetadata: ConnectionResult<InferSelectResult<SiteMetadatumWithRelations, S>>;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useSiteMetadataQuery(
  params: {
    selection: ListSelectionConfig<SiteMetadatumSelect, SiteMetadatumFilter, SiteMetadatumOrderBy>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildListSelectionArgs<
    SiteMetadatumSelect,
    SiteMetadatumFilter,
    SiteMetadatumOrderBy
  >(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: siteMetadatumKeys.list(args),
    queryFn: () => getClient().siteMetadatum.findMany(args).unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch SiteMetadatum list without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchSiteMetadataQuery({
 *   selection: {
 *     fields: { id: true },
 *     first: 10,
 *   },
 * });
 * ```
 */
export async function fetchSiteMetadataQuery<S extends SiteMetadatumSelect>(params: {
  selection: {
    fields: S;
  } & Omit<ListSelectionConfig<S, SiteMetadatumFilter, SiteMetadatumOrderBy>, 'fields'> &
    HookStrictSelect<NoInfer<S>, SiteMetadatumSelect>;
}): Promise<{
  siteMetadata: ConnectionResult<InferSelectResult<SiteMetadatumWithRelations, S>>;
}>;
export async function fetchSiteMetadataQuery(params: {
  selection: ListSelectionConfig<SiteMetadatumSelect, SiteMetadatumFilter, SiteMetadatumOrderBy>;
}) {
  const args = buildListSelectionArgs<
    SiteMetadatumSelect,
    SiteMetadatumFilter,
    SiteMetadatumOrderBy
  >(params.selection);
  return getClient().siteMetadatum.findMany(args).unwrap();
}
/**
 * Prefetch SiteMetadatum list for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchSiteMetadataQuery(queryClient, { selection: { fields: { id: true }, first: 10 } });
 * ```
 */
export async function prefetchSiteMetadataQuery<S extends SiteMetadatumSelect>(
  queryClient: QueryClient,
  params: {
    selection: {
      fields: S;
    } & Omit<ListSelectionConfig<S, SiteMetadatumFilter, SiteMetadatumOrderBy>, 'fields'> &
      HookStrictSelect<NoInfer<S>, SiteMetadatumSelect>;
  }
): Promise<void>;
export async function prefetchSiteMetadataQuery(
  queryClient: QueryClient,
  params: {
    selection: ListSelectionConfig<SiteMetadatumSelect, SiteMetadatumFilter, SiteMetadatumOrderBy>;
  }
): Promise<void> {
  const args = buildListSelectionArgs<
    SiteMetadatumSelect,
    SiteMetadatumFilter,
    SiteMetadatumOrderBy
  >(params.selection);
  await queryClient.prefetchQuery({
    queryKey: siteMetadatumKeys.list(args),
    queryFn: () => getClient().siteMetadatum.findMany(args).unwrap(),
  });
}
