/**
 * Single item query hook for NodeTypeRegistry
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { nodeTypeRegistryKeys } from '../query-keys';
import type { NodeTypeRegistrySelect, NodeTypeRegistryWithRelations } from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type { NodeTypeRegistrySelect, NodeTypeRegistryWithRelations } from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const nodeTypeRegistryQueryKey = nodeTypeRegistryKeys.detail;
/**
 * Query hook for fetching a single NodeTypeRegistry
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useNodeTypeRegistryQuery({
 *   name: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useNodeTypeRegistryQuery<
  S extends NodeTypeRegistrySelect,
  TData = {
    nodeTypeRegistry: InferSelectResult<NodeTypeRegistryWithRelations, S> | null;
  },
>(
  params: {
    name: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, NodeTypeRegistrySelect>;
  } & Omit<
    UseQueryOptions<
      {
        nodeTypeRegistry: InferSelectResult<NodeTypeRegistryWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useNodeTypeRegistryQuery(
  params: {
    name: string;
    selection: SelectionConfig<NodeTypeRegistrySelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<NodeTypeRegistrySelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: nodeTypeRegistryKeys.detail(params.name),
    queryFn: () =>
      getClient()
        .nodeTypeRegistry.findOne({
          name: params.name,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch a single NodeTypeRegistry without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchNodeTypeRegistryQuery({
 *   name: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchNodeTypeRegistryQuery<S extends NodeTypeRegistrySelect>(params: {
  name: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, NodeTypeRegistrySelect>;
}): Promise<{
  nodeTypeRegistry: InferSelectResult<NodeTypeRegistryWithRelations, S> | null;
}>;
export async function fetchNodeTypeRegistryQuery(params: {
  name: string;
  selection: SelectionConfig<NodeTypeRegistrySelect>;
}) {
  const args = buildSelectionArgs<NodeTypeRegistrySelect>(params.selection);
  return getClient()
    .nodeTypeRegistry.findOne({
      name: params.name,
      select: args.select,
    })
    .unwrap();
}
/**
 * Prefetch a single NodeTypeRegistry for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchNodeTypeRegistryQuery(queryClient, { name: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchNodeTypeRegistryQuery<S extends NodeTypeRegistrySelect>(
  queryClient: QueryClient,
  params: {
    name: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, NodeTypeRegistrySelect>;
  }
): Promise<void>;
export async function prefetchNodeTypeRegistryQuery(
  queryClient: QueryClient,
  params: {
    name: string;
    selection: SelectionConfig<NodeTypeRegistrySelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<NodeTypeRegistrySelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: nodeTypeRegistryKeys.detail(params.name),
    queryFn: () =>
      getClient()
        .nodeTypeRegistry.findOne({
          name: params.name,
          select: args.select,
        })
        .unwrap(),
  });
}
