/**
 * Single item query hook for TableTemplateModule
 * @generated by @constructive-io/graphql-codegen
 * DO NOT EDIT - changes will be overwritten
 */

import { useQuery } from '@tanstack/react-query';
import type { UseQueryOptions, UseQueryResult, QueryClient } from '@tanstack/react-query';
import { getClient } from '../client';
import { buildSelectionArgs } from '../selection';
import type { SelectionConfig } from '../selection';
import { tableTemplateModuleKeys } from '../query-keys';
import type {
  TableTemplateModuleSelect,
  TableTemplateModuleWithRelations,
} from '../../orm/input-types';
import type { InferSelectResult, HookStrictSelect } from '../../orm/select-types';
export type {
  TableTemplateModuleSelect,
  TableTemplateModuleWithRelations,
} from '../../orm/input-types';
/** Query key factory - re-exported from query-keys.ts */
export const tableTemplateModuleQueryKey = tableTemplateModuleKeys.detail;
/**
 * Query hook for fetching a single TableTemplateModule
 *
 * @example
 * ```tsx
 * const { data, isLoading } = useTableTemplateModuleQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true, name: true } },
 * });
 * ```
 */
export function useTableTemplateModuleQuery<
  S extends TableTemplateModuleSelect,
  TData = {
    tableTemplateModule: InferSelectResult<TableTemplateModuleWithRelations, S> | null;
  },
>(
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, TableTemplateModuleSelect>;
  } & Omit<
    UseQueryOptions<
      {
        tableTemplateModule: InferSelectResult<TableTemplateModuleWithRelations, S> | null;
      },
      Error,
      TData
    >,
    'queryKey' | 'queryFn'
  >
): UseQueryResult<TData>;
export function useTableTemplateModuleQuery(
  params: {
    id: string;
    selection: SelectionConfig<TableTemplateModuleSelect>;
  } & Omit<UseQueryOptions<any, Error, any, any>, 'queryKey' | 'queryFn'>
) {
  const args = buildSelectionArgs<TableTemplateModuleSelect>(params.selection);
  const { selection: _selection, ...queryOptions } = params ?? {};
  void _selection;
  return useQuery({
    queryKey: tableTemplateModuleKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .tableTemplateModule.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
    ...queryOptions,
  });
}
/**
 * Fetch a single TableTemplateModule without React hooks
 *
 * @example
 * ```ts
 * const data = await fetchTableTemplateModuleQuery({
 *   id: 'some-id',
 *   selection: { fields: { id: true } },
 * });
 * ```
 */
export async function fetchTableTemplateModuleQuery<S extends TableTemplateModuleSelect>(params: {
  id: string;
  selection: {
    fields: S;
  } & HookStrictSelect<NoInfer<S>, TableTemplateModuleSelect>;
}): Promise<{
  tableTemplateModule: InferSelectResult<TableTemplateModuleWithRelations, S> | null;
}>;
export async function fetchTableTemplateModuleQuery(params: {
  id: string;
  selection: SelectionConfig<TableTemplateModuleSelect>;
}) {
  const args = buildSelectionArgs<TableTemplateModuleSelect>(params.selection);
  return getClient()
    .tableTemplateModule.findOne({
      id: params.id,
      select: args.select,
    })
    .unwrap();
}
/**
 * Prefetch a single TableTemplateModule for SSR or cache warming
 *
 * @example
 * ```ts
 * await prefetchTableTemplateModuleQuery(queryClient, { id: 'some-id', selection: { fields: { id: true } } });
 * ```
 */
export async function prefetchTableTemplateModuleQuery<S extends TableTemplateModuleSelect>(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: {
      fields: S;
    } & HookStrictSelect<NoInfer<S>, TableTemplateModuleSelect>;
  }
): Promise<void>;
export async function prefetchTableTemplateModuleQuery(
  queryClient: QueryClient,
  params: {
    id: string;
    selection: SelectionConfig<TableTemplateModuleSelect>;
  }
): Promise<void> {
  const args = buildSelectionArgs<TableTemplateModuleSelect>(params.selection);
  await queryClient.prefetchQuery({
    queryKey: tableTemplateModuleKeys.detail(params.id),
    queryFn: () =>
      getClient()
        .tableTemplateModule.findOne({
          id: params.id,
          select: args.select,
        })
        .unwrap(),
  });
}
